harness/canary

- packages/playground/src/pages/pipeline-edit-page.tsx
- packages/unified-pipeline/src/components/Canvas/Canvas.tsx
Minor changes for
- Hiding Problems panel for Visual view, by default.
- Disabling animation on first render of Pipeline Studio, rendering nodes by-default at 100% zoom.
> fix: Minor fixes for Pipeline Studio

- packages/playground/src/components/execution/execution-details.tsx
- packages/playground/src/layouts/PaddingListLayout.tsx
- packages/playground/src/pages/execution-details-page.tsx
- packages/playground/src/pages/execution-list-page.tsx
- packages/playground/src/pages/pipeline-list-page.tsx
- packages/playground/src/pages/pull-request-list-page.tsx
- packages/playground/src/pages/repo-execution-list-page.tsx
- packages/playground/src/pages/repo-pipeline-list-page.tsx
Add reusable layout wrapper for each list page 
- Create PaddingLayout Component
- Wrapping list page as below: execution-list-page, pipeline-list-page, repo-execution-list, repo-pipeline-list, pull-request-list
> Pages responsive layout fix

- packages/unified-pipeline/src/components/Canvas/Canvas.tsx
- Changes the position of Controls to Bottom right
- Hides controls other than zoom in/out.
> Fix controls on Pipeline Studio

- packages/playground/src/components/execution/key-value-table.tsx
- packages/playground/src/components/execution/step-execution.tsx
- packages/playground/src/pages/mocks/execution/mockExecution.ts
- added output data for execution output page
- removed unnecessary wrapper <div>
- fixed the parent padding that caused the padding of children moving right
- aligned the same children in the same level of the padding(called padding h*ll)
- added keyValueTable in the execution output page
> Execution output log page

- packages/canary/src/components/stacked-list.tsx
- packages/canary/src/components/treeview.tsx
- packages/playground/src/components/execution/execution-details.tsx
- packages/playground/src/components/execution/key-value-table.tsx
- packages/playground/src/components/execution/step-execution.tsx
- packages/playground/src/components/repo-summary-panel.tsx
- packages/playground/src/pages/mocks/execution/mockExecution.ts
- packages/playground/src/pages/repo-summary-page.tsx
- Fix build issues in canary and playground during `pnpm build`.
- Adding proper types wherever missing.
- Fix types for inputs and outputs
- Rename to `inputs` and `outputs`
- Fix mock data
- Fix table column header names
> chore: Fix build issues in canary and playground

- packages/canary/src/components/navbar-project-chooser.tsx
- packages/canary/src/components/search-box.tsx
Currently, pressing the K key will trigger global search dialog. Need to add CMD modifier.
> Playground: fix incorrect search shortcut key

- apps/gitness/src/App.tsx
- apps/gitness/src/components/Header.tsx
- apps/gitness/src/framework/context/AppContext.tsx
- apps/gitness/src/framework/hooks/useGetSpaceParam.ts
- apps/gitness/src/layouts/RepoLayout.tsx
- apps/gitness/src/pages/execution-list.tsx
- apps/gitness/src/pages/landing-page.tsx
- packages/canary/src/components/effects/spotlights-box.tsx
- packages/canary/src/components/resource-box.tsx
- packages/playground/src/components/home.tsx
- packages/playground/src/components/layout/top-bar-widget.tsx
- packages/playground/src/components/project-dropdown.tsx
- packages/playground/src/data/mockProjects.ts
- packages/playground/src/index.ts
- packages/playground/src/layouts/PipelineLayout.tsx
- packages/playground/src/layouts/RepoLayout.tsx
- packages/playground/src/pages/execution-list-page.tsx
- packages/playground/src/pages/repo-list-page.tsx
- Adding `ProjectDropdown` as a separate component.
- Moved fetching spaces logic to app context.
- Fix Repo layout to render Header (with Project Dropdown in it).
- Default routing to first space/project from space/project list.
- Fix type issues in `playground`.
> Fixing App navigation with project selection

- packages/playground/src/components/pull-request/pull-request-commits.tsx
- packages/playground/src/components/sha-badge.tsx
- packages/playground/src/index.ts
Fix 2 things:
1) The PR commits `<NodeGroup />` still uses dummy chaos icon, this should use a simple node icon as per PP
2) SHA badge on same view (and elsewhere) should be componentized
> Playground: add simple node icon to PR commits and componentize sha badge

- packages/canary/src/components/node-group.tsx
- packages/playground/src/components/commits-list.tsx
- packages/playground/src/components/pull-request/pull-request-commits.tsx
`<NodeGroup.Connector />` does not handle styling of first/last icons correctly.
> Playground: fix incorrectly styled first or last node connector icons

- packages/canary/src/components/button.tsx
The addition of compound variant and style tweak to 'sm' size prop for the Shad `<Button />` component caused the new AI button to misrender. 
Removed those changes from the Button component, whilst keeping in Badge.
Issue:
Fix:
> Playground: remove compound variant and sm change from Shad Button to fix AI button conflict

- packages/canary/src/components/input-otp.tsx
- packages/playground/src/pages/forgot-password-page.tsx
- packages/playground/src/pages/landing-page.tsx
- packages/playground/src/pages/new-password-page.tsx
- packages/playground/src/pages/otp-page.tsx
- packages/playground/src/settings/landing-settings.tsx
Added 3 housekeeping screens from Figma, accessible from `Landing` and the usual bottom right state selector:
Forgot password:
OTP verification:
Create password:
> Playground: 3 new screens: forgot pwd, new pwd, verify OTP

- packages/canary/src/components/table.tsx
- packages/playground/src/layouts/SandboxLayout.tsx
- packages/playground/src/layouts/SandboxRoot.tsx
- ShadCN `<Table />` modded to accept `disableXScroll` prop, which prevents horiz scrolling, with default now set to `overflow-x: auto`
- Table cell vertical alignment is now 'top' not 'middle':
- `More` navbar option now works for the sandbox views (temporary)
- Layout will get a new sticky component for fixing headers on scrolling panels (coming next commit)
> Playground: fix table auto x scroll, some layout component changes, new layout comps

- packages/canary/src/components/navbar.tsx
- packages/playground/src/layouts/RootLayout.tsx
- packages/playground/src/layouts/SandboxRoot.tsx
- Not sure why this broke overnight, but no Sandbox Layout screens from the navbar were loading this morning
- There were some discrepancies in `SandboxRoot` which caused the issue, although I'm not sure why this worked fine last night.
- Fixed.
> Playground: fixed Sandbox Layout screens not rendering

- packages/canary/src/components/icon.tsx
- packages/canary/src/icons/pr-merged.svg
- packages/playground/src/components/pull-request/pull-request-conversation-header.tsx
> Playground: updated PR header with new pr-merged icon from Pixel Point

- apps/gitness/src/App.tsx
- apps/gitness/src/framework/context/AppContext.tsx
- apps/gitness/src/pages/pipeline-edit/components/pipeline-studio-header-actions.tsx
- apps/gitness/src/pages/pipeline-edit/components/pipeline-studio-step-form.tsx
- apps/gitness/src/pages/pipeline-edit/components/pipeline-studio-step-palette.tsx
- apps/gitness/src/pages/pipeline-edit/components/pipeline-studio.tsx
- apps/gitness/src/pages/pipeline-edit/context/PipelineStudioDataProvider.tsx
- packages/canary/src/components/sheet.tsx
- packages/forms/src/form/RenderForm/RenderForm.tsx
- packages/playground/src/assets/form/run-step.tsx
- packages/playground/src/components/pipeline-studio/pipeline-studio-footer-bar/pipeline-studio-footer-bar.tsx
- packages/playground/src/components/pipeline-studio/step-form/step-form.tsx
- packages/playground/src/index.ts
- packages/playground/src/pages/pipeline-edit-page.tsx
- Focus first input when step drawer opens.
- Remove temporary code for api hooks (multiple places)
- Add run step identifier/ description in playground
- Fix execution redirect
> Multiple changes

- apps/gitness/src/pages/repo/repo-branch-list.tsx
- packages/canary/src/components/tooltip.tsx
- packages/playground/src/components/branches-list.tsx
- packages/playground/src/components/copy-button.tsx
- Fixed issues and opened up the conversation about tooltips and copied button with UI design(hold for this idea and waiting for the final design), currently decided to remove this idea
- Revised details based on PR #222 
- migrate copied Icon as a component in the playground
- hidden the column without api call or lack of response
> Branchlist with apis follow up

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/pipeline-edit/components/pipeline-studio-header-actions.tsx
- apps/gitness/src/pages/pipeline-edit/context/PipelineStudioDataProvider.tsx
This PR removes hardcoded branch name and passes default branch for the pipeline while starting an execution.
> fix: Pass default branch on Run pipeline

- apps/gitness/src/framework/hooks/usePagination.ts
- apps/gitness/src/pages/repo/repo-branch-list.tsx
- apps/gitness/src/pages/repo/repo-commits.tsx
- packages/playground/src/components/pagination.tsx
- packages/playground/src/index.ts
- packages/playground/src/pages/branches-list-page.tsx
- packages/playground/src/pages/commits-list-page.tsx
- packages/playground/src/pages/execution-list-page.tsx
- packages/playground/src/pages/pipeline-list-page.tsx
- packages/playground/src/pages/pull-request-list-page.tsx
- packages/playground/src/pages/repo-execution-list-page.tsx
- packages/playground/src/pages/repo-list-page.tsx
- packages/playground/src/pages/repo-pipeline-list-page.tsx
- packages/playground/src/pages/repo-webhooks-page.tsx
- packages/playground/src/pages/sandbox-executions-summary-page.tsx
- Pagination component refactored and added under playground/components
- Takes props such as total pages, prev page, next page etc as discussed in standup on 9/30
- Ellipsis logic added to the component
- New Pagination component added in all listing pages of playground
- Next step would be to add this component to gitness, in a subsequent PR. 
- Screen shots attached are from playground.
> Integrating refactored pagination into playground

- apps/gitness/src/pages/repo/repo-branch-list.tsx
- packages/playground/src/components/branches-list.tsx
- Solved undefined issues for getting data from useCalculateCommitDivergenceMutation
- Used the index in branch list for getting the data of useCalculateCommitDivergenceMutation, instead of splitting props in BranchList components
- Add default setting for the default branch in the first row of the branch list
> Branchlist-behind-ahead-apicall

- apps/gitness/src/pages/repo/repo-create-page.tsx
- packages/playground/src/pages/sandbox-repo-create-page.tsx
- Makes sure `success button` only visible when API call returns no errors. 
- Persists form data in case of an error, so user can make changes. 
- Removes `setTimeout`, and reduces state management within the component. Utilizes `react-query's` inbuilt states. 
Below screen recordings should make bug fix clear:
Earlier:
https://github.com/user-attachments/assets/903009b9-de0a-4f6a-ae8d-3240829e3563
Now:
https://github.com/user-attachments/assets/19115816-a0b6-4c3a-aea2-a46c659f5ade
> Minor fixes to account for API error in repo-create-page

- packages/playground/src/components/repo-summary.tsx
In Sandbox:
`Repo > Summary` now truncates the file name column and applies a line clamp = 1 to the commit msg.
> Playground: repo summary add line clamp and truncate

- apps/gitness/src/pages/pull-request-list-page.tsx
- packages/canary/src/components/list-actions.tsx
- packages/playground/src/hooks/useCommonFilter.tsx
- packages/playground/src/index.ts
https://github.com/user-attachments/assets/f8c1f097-1e24-49e6-961e-e0e97cfb1472
---
---
> [!NOTE]
>  Label will be bold if that filter is applied and on clicking the current selected filter item, the filter will be removed
> Add common filter hook with sort filter

- apps/gitness/src/framework/hooks/useLogs.ts
- packages/canary/src/components/treeview.tsx
- packages/playground/src/App.tsx
- packages/playground/src/components/execution/console-logs.tsx
- packages/playground/src/components/execution/step-execution.tsx
- packages/playground/src/components/pipeline-list.tsx
- packages/playground/src/utils/TimeUtils.ts
- Logs cleanup when navigating from one step to another in Execution tree view.
- Replacing Icon noir with Canary icons.
- Fix few type issues in `packages/playground`.
- Fix time formatting for console logs.
- Fixing Execution list view for different execution statuses.
> fix: Minor fixes for Execution listing and details page

- packages/canary/src/components/search-box.tsx
This is a very short term fix for the Gitness-specific issue where the `<Searchbox />` component cannot handle tailwind padding, and therefore the left icon overlays the text.
This is a symptom of how the products/modules build tailwind, which must be addressed. Once addressed, this fix will no longer be required.
> Playground: very temporary fix for Gitness searchbox padding issue

- apps/gitness/src/RouteDefinitions.ts
- apps/gitness/src/hooks/useGetPullRequestTab.ts
- apps/gitness/src/layouts/PullRequestLayout.tsx
This allows capability reuse across multiple pages and components wherever selected Pull request section needs to be known.
> chore: Extract route match logic for Pull request tabs as a hook

- apps/gitness/src/pages/pipeline-list.tsx
- apps/gitness/src/pages/pull-request-list-page.tsx
- apps/gitness/src/pages/repo/repo-branch-list.tsx
- apps/gitness/src/pages/repo/repo-commits.tsx
- apps/gitness/src/pages/repo/repo-files.tsx
- apps/gitness/src/pages/repo/repo-list.tsx
- apps/gitness/src/pages/repo/repo-summary.tsx
- apps/gitness/src/pages/repo/repo-webhooks.tsx
- packages/canary/src/components/list-actions.tsx
- packages/canary/src/components/search-box.tsx
- packages/playground/src/components/filter.tsx
- packages/playground/src/hooks/useCommonFilter.tsx
- packages/playground/src/index.ts
Summary:
Added filters for repo and children screens.
Filter status across screens:
Link: https://harness.atlassian.net/wiki/spaces/CDNG/pages/22066757999/Unified+Pipeline+UI+filter+progress
> Add filters to repo and children screens

- apps/gitness/src/components/Header.tsx
- apps/gitness/src/framework/context/AppContext.tsx
- apps/gitness/src/pages/create-project.tsx
- Adds a `+ Create a new project` option to Project selector dropdown.
- Reroutes to the newly created project and also selects it in the dropdown.
- Makes reaching `/create-project` easier.
https://github.com/user-attachments/assets/1f246c01-b1f4-4f2f-b715-6caf94d79b73
> feat: Add "+ Create a new project" option to Project selector dropdown

- apps/gitness/package.json
- apps/gitness/src/App.tsx
- apps/gitness/src/pages/profile-settings/profile-settings-keys-container.tsx
- apps/gitness/src/pages/profile-settings/profile-settings-keys-page.tsx
- apps/gitness/src/pages/profile-settings/ssh-key-create/ssh-key-create-dialog.tsx
- apps/gitness/src/pages/profile-settings/ssh-key-create/ssh-key-create-form.tsx
- apps/gitness/src/pages/profile-settings/token-create/token-create-dialog.tsx
- apps/gitness/src/pages/profile-settings/token-create/token-create-form.tsx
- apps/gitness/src/pages/profile-settings/token-create/token-success-dialog.tsx
- apps/gitness/src/pages/profile-settings/token-create/token-success-form.tsx
- packages/canary/src/components/button.tsx
- packages/playground/src/components/copy-button.tsx
- packages/playground/src/components/ssh-key-create-dialog.tsx
- packages/playground/src/components/ssh-key-create-form.tsx
- packages/playground/src/components/token-create-dialog.tsx
- packages/playground/src/components/token-create-form.tsx
- packages/playground/src/index.ts
- packages/playground/src/pages/sandbox-settings-account-keys-page.tsx
- pnpm-lock.yaml
- Implemented new functionality for creating and managing personal access tokens, including a token creation form and success dialog.
- Added support for SSH key management, with a new form for adding SSH keys and associated dialogs.
- Updated the profile settings page to include buttons for adding new tokens and SSH keys.
- Integrated new components into the Playground package, including TokenCreateDialog, SshKeyCreateDialog, and their respective forms, to provide reusable UI elements for token and SSH key management.
- Demoed in standup on 10/9. 
Complete Flow:
https://github.com/user-attachments/assets/7d7808ae-bcbf-4271-a2a6-dd463f7eb08d
Error handling:
https://github.com/user-attachments/assets/668b0500-8f54-491a-8cc0-d7f61fca6f39
> Create token and key flow 

- apps/gitness/package.json
- apps/gitness/src/RouteDefinitions.ts
- apps/gitness/src/components/FileContentViewer.tsx
- apps/gitness/src/components/FileExplorer.tsx
- apps/gitness/src/components/FileViewer.tsx
- apps/gitness/src/global.d.ts
- apps/gitness/src/pages/repo/repo-files.tsx
- apps/gitness/src/utils/git-utils.ts
- apps/gitness/src/utils/path-utils.ts
- packages/playground/src/components/file-explorer.tsx
- packages/playground/src/components/repo-summary.tsx
- packages/playground/src/layouts/SandboxLayout.tsx
- packages/playground/src/pages/sandbox-repo-code-page.tsx
- packages/yaml-editor/src/components/CodeEditor.tsx
- pnpm-lock.yaml
Adds Link to BreadCrumbs shown for Repo Code file destinations
Adds File Explorer sort and display folders first and then files
Adds File Content Viewer that uses monaco code editor to display content and lang-map to provide the proper language as per the filetype
Code View Content
Markdown Preview
> feat: [PIPE-22045]: file explorer in gitness

- apps/gitness/src/pages/pipeline-list.tsx
- apps/gitness/src/pages/pull-request-list-page.tsx
- apps/gitness/src/pages/repo/repo-branch-list.tsx
- apps/gitness/src/pages/repo/repo-commits.tsx
- apps/gitness/src/pages/repo/repo-list.tsx
- apps/gitness/src/pages/repo/repo-webhooks.tsx
Fixed for below listing pages:
- Pipelines
- Repositories
- Webhooks
- Pull requests
- Branches
Samples:
> feat: Adding "No data" and "No search results" views for listing pages

- apps/gitness/src/layouts/PullRequestLayout.tsx
- apps/gitness/src/pages/pull-request/pull-request-conversation-page.tsx
- apps/gitness/src/pages/pull-request/utils.ts
- packages/playground/src/components/pull-request/pull-request-panel.tsx
- packages/playground/src/components/pull-request/sections/pull-request-changes-section.tsx
- packages/playground/src/components/pull-request/sections/pull-request-check-section.tsx
- packages/playground/src/layouts/SandboxPullRequestCompareLayout.tsx
- packages/playground/src/pages/pull-request-conversation-page.tsx
For the moment, we won’t have a checks tab and we will navigate traffic from pr page in the prpanel check section to the execution log details page
also other minor fixes 
- fix bypass state in pr panel
- hide chevron in change section when there is nothing to show
- fix css in panel
> feat: [pipe-22240]: pr checks

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-branch-rules-container.tsx
- apps/gitness/src/pages/repo-sandbox/repo-settings-general-container.tsx
- apps/gitness/src/utils/repo-branch-rules-utils.ts
- packages/playground/src/components/repo-settings/repo-branch-settings-rules/reducers/repo-branch-settings-reducer.ts
- packages/playground/src/components/repo-settings/repo-branch-settings-rules/repo-branch-settings-rules-data.tsx
- packages/playground/src/components/repo-settings/repo-branch-settings-rules/repo-branch-settings-rules-fields.tsx
- packages/playground/src/components/repo-settings/repo-branch-settings-rules/repo-branch-settings-rules-schema.tsx
- packages/playground/src/components/repo-settings/repo-branch-settings-rules/types.ts
- packages/playground/src/components/repo-settings/repo-settings-general/repo-settings-general-delete.tsx
- packages/playground/src/components/repo-settings/repo-settings-general/repo-settings-general-rules.tsx
- packages/playground/src/components/repo-settings/repo-settings-general/repo-settings-general-security.tsx
- packages/playground/src/components/repo-settings/repo-settings-general/types.ts
- packages/playground/src/pages/repo-branch-settings-rules-page.tsx
- packages/playground/src/pages/repo-settings-general-page.tsx
- Adds the `repo-branch-rules-page` to `gitness` with minor fixes. 
- Uses HTTP restful URL pattern, no query params. 
- changes button to `update rule` on rule edit. 
- Minor fixes such as increasing pipe size, text no longer breaking, icons made smaller, etc.
- Adds `dropdown` in input to `include/exclude` button. 
e2e vid:
https://github.com/user-attachments/assets/e9218506-17a8-4b13-b90b-040f60a86580
> Integrate rules list

- apps/gitness/src/App.tsx
- apps/gitness/src/framework/hooks/useGetRepoId.ts
- apps/gitness/src/framework/hooks/useGetRepoPath.ts
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-branch-rules-container.tsx
- apps/gitness/src/pages/repo-sandbox/repo-settings-general-container.tsx
- apps/gitness/src/utils/repo-branch-rules-utils.ts
- packages/playground/src/App.tsx
- packages/playground/src/components/alert-delete-dialog-form.tsx
- packages/playground/src/components/alert-delete-dialog.tsx
- packages/playground/src/components/repo-settings/repo-settings-general/repo-settings-general-delete.tsx
- packages/playground/src/components/repo-settings/repo-settings-general/repo-settings-general-form.tsx
- packages/playground/src/components/repo-settings/repo-settings-general/repo-settings-general-rules.tsx
- packages/playground/src/components/repo-settings/repo-settings-general/repo-settings-general-tooltip.tsx
- packages/playground/src/components/repo-settings/repo-settings-general/types.ts
- packages/playground/src/index.ts
- packages/playground/src/pages/mocks/repo-settings/mockRepoData.ts
- packages/playground/src/pages/mocks/repo-settings/mockRulesData.ts
- packages/playground/src/pages/repo-branch-settings-rules-page.tsx
- packages/playground/src/pages/repo-settings-general-page-playground-container.tsx
- packages/playground/src/pages/repo-settings-general-page.tsx
- packages/playground/src/pages/sandbox-repo-settings-page.tsx
- Introduces `useGetRepoId` to get the repo ID. 
- Creates a completely reusable `Delete Alert` dialog. 
- Adds default file to pages that are not yet implemented. 
- integrates delete repo with the `alert dialog`. 
- Adds drop down menu to repo-rules with options to edit/delete. 
- Adds `no-data` placeholder for rules-list. 
- This should complete our repo/branch rules flow
e2e vid:
https://github.com/user-attachments/assets/ae54f25f-0f68-4879-b824-864a72a510fe
> Finish integrate rules list

- apps/gitness/src/layouts/RepoLayout.tsx
- apps/gitness/src/layouts/RepoSandboxLayout.tsx
- packages/playground/src/pages/signin-page.tsx
- Removes forgot password link from `signin`. 
- Takes 3 tabs to move to `signin`. 
- TnC no longer overlaps with the `singin` component. 
-  Also fixes tab nav. Uses `isActive` from `Navlink`. Persists on refresh. 
3 tabs to signin - 
https://github.com/user-attachments/assets/e1d82054-cd67-46bb-8a72-2489519260c9
No overlap-
https://github.com/user-attachments/assets/a48ca12d-a85c-4eb3-807b-fe5ec42aa9dd
New tab-nav -
https://github.com/user-attachments/assets/af244d60-3361-4ef4-b08e-038f9c970c92
> fix singin page

- packages/playground/src/components/loaders/skeleton-list.tsx
feat: only show skeleton loader if the API is taking longer than a certain time
- add a customisable (default 300ms) delay before showing the skeleton list loader
- fade-in the loader for a smoother experience
> feat: delay showing loader for small duration

- apps/gitness/src/pages/execution-list.tsx
- apps/gitness/src/pages/pipeline-list.tsx
- apps/gitness/src/pages/profile-settings/profile-settings-keys-container.tsx
- apps/gitness/src/pages/profile-settings/profile-settings-keys-page.tsx
- apps/gitness/src/pages/pull-request-commits-page.tsx
- apps/gitness/src/pages/pull-request-list-page.tsx
- apps/gitness/src/pages/repo/repo-branch-list.tsx
- apps/gitness/src/pages/repo/repo-commits.tsx
- apps/gitness/src/pages/repo/repo-list.tsx
- apps/gitness/src/pages/repo/repo-webhooks.tsx
- apps/gitness/src/pages/sandbox-execution-list.tsx
- apps/gitness/src/pages/sandbox-pipeline-list.tsx
- packages/playground/src/components/pagination.tsx
- packages/playground/src/pages/sandbox-settings-account-page.tsx
Integrates pagination on following pages:
1. Tokens and Keys > SSH keys
2. Pull Request Details > Commits
Also, cleans up Pagination component to avoid conditional rendering based on presence/absence of pagination response headers.
> feat: Add pagination on few more pages, cleanup conditional rendering logic

- apps/gitness/src/pages/pull-request/pull-request-changes-filter.tsx
hide some pr filters on the pr changes tab since they arent usuable atm
> feat: [pipe-21741]: hide pr filters for now on changes tab

- apps/gitness/src/pages/repo/repo-create-page.tsx
- packages/playground/src/App.tsx
- packages/playground/src/data/mockCreateRepoData.ts
- packages/playground/src/pages/sandbox-repo-create-page.tsx
- Adds gitignore/license dropdown to `create repo`
- mocks data in playground
- minor fixes to form in `create repo` page
> Add gitignore/license options to create repo page

- CODEOWNERS
This PR adds the initial CODEOWNERS file to protect the `views`, `canary` and `ui` packages, and the `design-system` app.
> chore: [XD-42]: Add CODEOWNERS file

- packages/unified-pipeline/src/utils/ParserUtils.tsx
Currently we are showing step script in the step display name in pipeline studio. This change to show step name as display name, if not fallback to current approach.
> step name should be considered as precedence in step display name

- apps/gitness/src/pages-v2/repo/repo-list.tsx
- packages/ui/src/views/repo/repo-list/repo-list-page.tsx
- packages/ui/src/views/repo/repo-list/repo-list.tsx
- packages/ui/src/views/repo/repo-list/types.ts
The loading and error states are currently handled directly in the repo-list page. Ideally, these states should be passed as props to the view, enabling the view to handle rendering for the Loading, Error, or No Data states in a more modular way.
In several pages/views, multiple ternary operators are being used, which can reduce code readability and maintainability. Let's try using if conditions instead for rendering different data states.
The source of truth for loading, error, and data states should come from the react-query hook and be passed as props from the page to the view.
Refer to the changes in this PR as a reference for effectively managing data states.
> Handled loading, error and no data states in view

- packages/ui/src/components/button.tsx
- packages/ui/src/components/dropdown-menu.tsx
- packages/ui/src/components/tabs.tsx
- packages/ui/src/views/repo/components/branch-selector/branch-selector-dropdown.tsx
- packages/ui/src/views/repo/repo-summary/components/summary-panel.tsx
This pull request introduces minor style adjustments for the `Branch Selector`, `Filters` (updated border color), and `Summary Panel` (updated description area: text color and size.) components, as well as a small refactoring of the `Text` component.
**Screenshots:**
Before
After
> feat: minor styling improvements

- apps/gitness/src/pages/profile-settings/profile-settings-general-page.tsx
Currently, there is a theme selector on the profile settings page which is now obsolete and needs to be removed.
We have a dedicated theme settings page which should be used for theme selection.
We removed the theme selector from profile settings page as part of this PR. Here's how the profile settings page look after removing the theme selector:
> Removed theme selector from general settings

- apps/gitness/src/pages-v2/repo/repo-summary.tsx
- packages/ui/src/views/repo/repo-list/repo-list.tsx
- packages/ui/src/views/repo/repo-summary/components/edit-repo-details-dialog.tsx
- packages/ui/src/views/repo/repo-summary/components/summary-panel.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
repo description in a dialog as per new figma design
also added full width for summary page acc to figma - https://www.figma.com/design/Lu5QJyq9tQEjHMeQmQhbAd/Gitness-Product-Design---Stage-2?node-id=5318-41915&node-type=canvas&t=kwQAdKoUWXZT5HPm-0
> fix: repo description in a dialog

- apps/gitness/src/components/RootWrapper.tsx
- apps/gitness/src/components/stores/recent-pinned-nav-links.store.ts
- packages/ui/src/components/manage-navigation/draggable-item.tsx
- packages/ui/src/components/manage-navigation/index.tsx
- packages/ui/src/components/navbar/types.ts
- packages/ui/src/views/layouts/SandboxRoot.tsx
1. Passing "useNav" to `SandboxRoot` component.
2. Disabling permanently pinned component from drag and drop.
> Rerfactor and Add disable drag feature for permanently pinned menu items

- apps/gitness/src/pages-v2/repo/repo-list.tsx
The dropdown for switching between spaces was not present previously on the Repo List page.
By adding Breadcrumbs to the page, the user shall now be able to switch between spaces using the dropdown in breadcrumbs.
https://github.com/user-attachments/assets/62556789-5e4d-494f-a3a8-2cec750b418c
> Added breadcrumbs to repo list page

- apps/gitness/src/pages-v2/repo/repo-layout.tsx
Fixed settings menu overlap with Breadcrumbs.
After Fix:
https://github.com/user-attachments/assets/35cac714-c08f-4504-afb1-0adb7f16c8bb
Before Fix:
https://github.com/user-attachments/assets/39bbd434-42b9-4d5d-a50d-74459cc4b50a
> Fixed Settings Menu Overlap with Breadcrumbs

- apps/gitness/package.json
- apps/gitness/src/styles.css
- packages/ui/package.json
- packages/ui/src/index.ts
- packages/ui/tailwind.ts
- packages/ui/vite.config.ts
This PR removes unnecessary CSS build tasks, switches to use the built CSS from the ui package and adds missing `files` entry in ui `package.json`
> Fix UI package scope

- apps/gitness/src/components-v2/file-content-viewer.tsx
- apps/gitness/src/components-v2/file-editor.tsx
- apps/gitness/src/components-v2/git-commit-dialog.tsx
- apps/gitness/src/components/FileContentViewer.tsx
- apps/gitness/src/components/FileEditor.tsx
- apps/gitness/src/components/GitCommitDialog.tsx
- apps/gitness/src/components/GitCommitForm.tsx
- apps/gitness/src/pages-v2/repo/repo-code.tsx
- apps/gitness/src/pages-v2/repo/repo-list.tsx
- apps/gitness/src/pages-v2/repo/repo-sidebar.tsx
- apps/gitness/src/pages-v2/repo/repo-summary.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/es/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/components/commit-copy-actions.tsx
- packages/ui/src/components/git-commit-dialog/git-commit-dialog.tsx
- packages/ui/src/views/repo/pull-request/pull-request-list-page.tsx
- packages/ui/src/views/repo/repo-list/repo-list-page.tsx
- packages/ui/src/views/repo/repo-list/repo-list.tsx
fixes : 
1. **commit changes onSuccess navigation**
2. **default branch for repo summary/files**
3. **commit changes to current branch**
4. **repo list no data state**
5. **PR list no data state**
6. **Monospace font for Commit Sha's across the pages**
> fix: repo list no data state

- apps/design-system/src/App.tsx
This PR redirects requests to the root of the design system app to the view-preview route. This is a temporary measure until the component aspect of the design system app is ready.
> chore: Redirect the root of the design system app to  temporarily

- packages/ui/src/components/badge.tsx
- packages/ui/src/components/filters/filters-bar/actions/variants/checkbox.tsx
- packages/ui/src/views/repo/components/branch-info-bar.tsx
- packages/ui/src/views/repo/components/branch-selector/branch-selector-dropdown.tsx
- packages/ui/src/views/repo/components/index.ts
- packages/ui/src/views/repo/repo-summary/components/recent-push-info-bar.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
This pull request adds information about the currently selected branch, as well as information about new branches that have recently appeared
**:warning: Note**
At the moment it uses test data which is not related to the real data.
**Screenshots:**
`BranchInfoBar`
`RecentPushInfoBar`
> feat: add BranchInfoBar and RecentPushInfoBar components

- apps/gitness/src/components/FileEditor.tsx
- apps/gitness/src/pages/pipeline-edit/theme/monaco-theme.ts
This pull request brings new color scheme for code blocks
> feat: update color theme for monaco-editor

- packages/ui/src/components/filters/filters-bar/actions/views.tsx
- packages/ui/src/components/filters/filters-bar/filters-bar.tsx
- packages/ui/src/components/filters/filters.tsx
- packages/ui/src/components/filters/manage-views.tsx
- packages/ui/src/components/filters/triggers/view-trigger.tsx
- packages/ui/src/components/stacked-list.tsx
- packages/ui/src/views/repo/components/file-last-change-bar.tsx
- packages/ui/src/views/repo/components/summary/summary.tsx
- packages/ui/src/views/repo/pull-request/pull-request-list-page.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
This pull request updates the `Repo Summary` page, specifically the `FileLastChangeBar` component, and fixes type and validation issues in the `Filters` component.
- [Repo Summary Preview](https://deploy-preview-590--harness-xd-review.netlify.app/view-preview/repo-summary)
- [Pull Request List Preview](https://deploy-preview-590--harness-xd-review.netlify.app/view-preview/pull-request-list)
**Screenshots:**
Before: **Repo Summary**
After: **Repo Summary**
**Filters**
fixed bug when views logic is disabled from filtering but the save button is still displayed
corrected data display and their check if for some reason they are missing - in this case Views is not displayed
corrected types for easy checking when passing parameters and also added examples
> feat: updating the Summary page display and fixing filtering issues

- apps/design-system/package.json
- apps/design-system/src/pages/view-preview/view-preview.tsx
- apps/design-system/src/pages/view-preview/view-settings.module.css
- apps/design-system/src/pages/view-preview/view-settings.tsx
- pnpm-lock.yaml
This PR adds initial support for themes in the view preview. The view switcher has also been replaced by a view settings panel.
https://github.com/user-attachments/assets/ed469f68-a47d-441a-b439-30beca3d101a
> feat: Add theme support to view preview

- packages/ui/src/styles.css
Update for --canary-success token. Previously, the value for the light theme incorrectly included a dark mode variable.
Before:
After:
> Update light-std-std styles.css

- apps/gitness/src/App.tsx
- apps/gitness/src/pages-v2/user-management/stores/admin-list-store.tsx
- apps/gitness/src/pages-v2/user-management/user-management-container.tsx
- packages/ui/src/views/index.ts
- packages/ui/src/views/user-management/components/users-list.tsx
- packages/ui/src/views/user-management/index.ts
- packages/ui/src/views/user-management/types.ts
- packages/ui/src/views/user-management/user-management-page.tsx
- Adds the `admin-users-list` page to `gitness`.
- Role binding data is currently left empty as its not available in the API.
https://github.com/user-attachments/assets/fde6bee0-9b86-440a-ae3f-c83dd07b83c4
> Admin user list

- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- packages/ui/src/components/badge.tsx
- packages/ui/src/components/dropdown-menu.tsx
- packages/ui/src/components/tabs.tsx
- packages/ui/src/components/textarea.tsx
- packages/ui/src/views/layouts/PullRequestLayout.tsx
- packages/ui/src/views/repo/components/branch-selector/branch-selector-dropdown.tsx
- packages/ui/src/views/repo/pull-request/compare/pull-request-compare-page.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-header.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-comment-box.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-panel.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-timeline-item.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/sections/pull-request-changes-section.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/sections/pull-request-line-title.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/sections/pull-request-merge-section.tsx
- packages/ui/src/views/repo/repo-summary/components/clone-repo-dialog.tsx
**Description**:
This pull request introduces a refactoring of the header components for the detailed `PR` page as well as style adjustments. 
**TODO** (points that need to be finalized and fixed in separate PR's)
- Refactor Page Construction: in `apps/gitness`, revise the way the page is built. Currently, the page is constructed entirely from individual components. Instead, we should use a single component named `PullRequestConversationView` and pass it the required props, similar to the approach used on other pages.
- In the `Overview section` on the `Conversation tab`, the commit history need to be displayed (currently missing), and the components and styles require refactoring.
- A state needs to be added for the dropdown where we select how we plan to merge this PR (currently, it …
> feat: enhance PR layout with tab nav and UI improvements

- apps/gitness/src/routes.tsx
Currently, routes which are sibling of `/` do not render with App shell, which includes side nav and breadcrumbs. This PR fixes it.
**Sample**:
**Before**:
**After**:
> fix: Ensure App Shell renders for all applicable routes 

- apps/gitness/src/components-v2/breadcrumbs/breadcrumbs.tsx
- apps/gitness/src/routes.tsx
- Undo changes done in Breadcrumbs component done in PR https://github.com/harness/canary/pull/560.
- Project selection in the breadcrumbs doesn't work correctly due to this change.
https://github.com/user-attachments/assets/55acf0a9-9e5e-400d-9833-44ef580d376c
> fix: Revert changes in Breadcrumbs component

- packages/ui/src/components/navbar-skeleton/item.tsx
- packages/ui/src/components/navbar-skeleton/root.tsx
- packages/ui/src/components/navbar/navbar.tsx
- packages/ui/src/shared-style-variables.css
- packages/ui/src/views/repo/webhooks/webhook-list/repo-webhook-list-page.tsx
- packages/ui/tailwind.ts
- Restored the pattern and gradients in Navigation, moved the colors to variables
- Converted the glow gradient of the active item in Navigation into variables
- Restored the gradient on the active Tab
> fix: fix gradients at navbar and tabs

- apps/gitness/src/components-v2/file-content-viewer.tsx
- apps/gitness/src/framework/hooks/useDownloadRawFile.ts
https://github.com/user-attachments/assets/ac9aafe5-71c7-44c6-a392-a3d551ead7cb
> Fixed api route for download file and view raw file

- apps/portal/package.json
- package.json
This PR sets the min Node version 18.17.1.
fixes #691
> chore: set min node version to 18.17.1

- packages/ui/src/components/button-with-options.tsx
- packages/ui/src/components/button.tsx
- packages/ui/src/shared-style-variables.css
- packages/ui/src/styles.css
- packages/ui/src/views/repo/pull-request/compare/components/pull-request-compare-button.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-header.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-panel.tsx
- packages/ui/src/views/repo/pull-request/utils.ts
- packages/ui/src/views/repo/repo-branch-rules/components/repo-branch-rules-fields.tsx
- packages/ui/tailwind.ts
This pull request makes the following fixes:
- refactoring and fixing the common `ButtonWithOptions` component [[Issue](https://github.com/harness/canary/issues/688)]
- fix colors in `Button themes`
- fix naming `color tokens for buttons` 
leads to a unified style instead of `--canary-backround-button` => `--canary-button-background` based on the design system
- fix `tag color` for dark theme
- minor adjustments and update `tailwind config` for button colors 
**Screenshots:**
fix colors in `Button themes`
**Before:**
`Disable state:`
`Success state:`
**After:**
`Disable state:`
`Success state:`
fix `tag color` for dark theme
**Before**
**After:**
> refactor: styles and components on PR pages

- apps/portal/src/content/docs/components/accordion.mdx
This PR removes exploratory code that was added in the initial version of the `Accordion` docs.
refs #694
> fix: Remove exploratory code

- apps/portal/astro.config.ts
- apps/portal/src/styles.css
The PR removes unneeded inclusions of tailwind utilities and moves `@harnessio/ui/styles.css` to have precedence over portal app styles.
fixes #740
> fix: Ensure that UI lib styles have precedence in portal app

- packages/ui/package.json
This PR bumps the version of the UI library to `0.0.1-alpha.0`
fixes #744
> chore: ui lib v0.0.1-alpha.0

- apps/gitness/src/pages-v2/repo/repo-commit-details-diff.tsx
- apps/gitness/src/pages-v2/repo/repo-commit-details.tsx
- apps/gitness/src/routes.tsx
- packages/ui/src/views/repo/repo-commit-details/components/commit-diff.tsx
- packages/ui/src/views/repo/repo-commit-details/repo-commit-details-view.tsx
- Removes `file-tree` from commit details in `gitness`. 
- Still visible in the `design-system`.
> fix: remove file tree from commit details page

- packages/pipeline-graph/package.json
> chore: Bump `@harnessio/pipeline-graph` to v1.0.0-alpha.0

- apps/gitness/src/App.tsx
- apps/gitness/src/components-v2/app-shell.tsx
- apps/gitness/src/components-v2/breadcrumbs/breadcrumbs.tsx
- apps/gitness/src/components-v2/breadcrumbs/project-dropdown.tsx
- apps/gitness/src/framework/context/AppContext.tsx
- apps/gitness/src/framework/routing/types.ts
- apps/gitness/src/pages-v2/landing-page-container.tsx
- apps/gitness/src/pages-v2/signin.tsx
- apps/gitness/src/routes.tsx
- This PR adds support for `asLink` prop that handles rendering of non-link elements in Breadcrumbs, for e.g. Project Selector.
- Also fixes the flow where list of spaces if fetched if not available in App context while rendering the Project selector. Additionally, also removes duplicate api calls from Landing page.
- `<AppProvider /` now wraps around `<AppShell />` instead, since few routes outside of the App shell, such as `/signin` etc., do not need access to App context.
> fix: Add "asLink" prop to allow rendering non-link breadcrumbs

- packages/ui/src/components/dialog.tsx
This PR restores the open/close animation to the `Dialog` component.
|Before|After|
|------|------|
|![Before](https://github.com/user-attachments/assets/d544ec84-9947-4d51-a9a2-bd00ee20c643)|![After](https://github.com/user-attachments/assets/06d40743-cc56-41ff-a7b6-be7d8f182af3)|
fixed #779
> feat: Restore open/close animation to Dialog component

- packages/ui/src/components/button-with-options.tsx
- packages/ui/src/views/repo/repo-branch-rules/components/repo-branch-rules-fields.tsx
- packages/ui/src/views/repo/repo-branch-rules/repo-branch-settings-rules-page.tsx
This pull request make minor adjustments to the styles for the `Create Rule` page after review by the design team
**Before:**
**After**
**Before:**
https://github.com/user-attachments/assets/55d886dd-e515-434f-a11d-9b47c472a549
**After:**
https://github.com/user-attachments/assets/c5a48e42-0312-4289-8811-27388dd113dc
**Before:**
**After:**
**Before:**
**After:**
> fix: styles for the Create Rule page

- apps/design-system/src/pages/view-preview/root-view-wrapper-store.tsx
- apps/design-system/src/pages/view-preview/root-view-wrapper.tsx
- apps/design-system/src/pages/view-preview/view-preview.tsx
- apps/design-system/src/subjects/views/repo-create/index.tsx
- apps/design-system/src/subjects/views/repo-create/repo-create-store.tsx
- apps/design-system/src/subjects/views/repo-import/index.tsx
- apps/design-system/src/subjects/views/signin/index.tsx
- apps/design-system/src/subjects/views/signup/index.tsx
- apps/gitness/src/components-v2/app-shell.tsx
This pull-request brings previews for:
- signin page - https://deploy-preview-812--harness-xd-review.netlify.app/view-preview/signin
- signup page - https://deploy-preview-812--harness-xd-review.netlify.app/view-preview/signup
- create repo page - https://deploy-preview-812--harness-xd-review.netlify.app/view-preview/repo-create
- import repo page - https://deploy-preview-812--harness-xd-review.netlify.app/view-preview/repo-import
And also brings menu items for sidebar navigation
> feat: add preview pages

- packages/ui/src/shared-style-variables.css
- packages/ui/src/views/repo/components/branch-info-bar.tsx
- packages/ui/src/views/repo/components/branch-selector/branch-selector-dropdown.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-list-header.tsx
https://docs.google.com/spreadsheets/d/1kaR5TYxFxE6esk2JxO5VJdPVPFWHtVW7efQ5ZdTK7Go/edit?pli=1&gid=472839805#gid=472839805
This PR fixes the following issues from the above sheet:
- Clicking on Repoisitories in breadcrumbs navigates to incorrect path
- Change branch -> Click on "xx commits behind" -> 404 page
- Commit details page throwing 404 when navigated from commits page
- While using Light Theme, monaco editor highlights file changes in black background color
- In Light theme, open pull request count is shown in white color, and hence it seems to not exist
- MFE: PR compare - changes - diff view has black background in light theme
- MFE : click on repo name in breadcrumb navigates to wrong path
> Fixed a few issues from MFE Bugbash India sheet

- apps/design-system/src/subjects/views/pull-request-compare/pull-request-compare.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-compare.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- apps/gitness/src/pages-v2/repo/repo-code.tsx
- packages/ui/src/views/repo/pull-request/compare/pull-request-compare-page.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-side-bar.tsx
- packages/ui/src/views/repo/pull-request/details/components/changes/pull-request-changes.tsx
- packages/ui/src/views/repo/repo-branch/components/create-branch-dialog.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
PR includes fixes for the following bugs : 
1. Repo Summary - huge line in readme was adding horizontal scroll 
2. PR conversation and changes page - scroll comment into view if commentId copied and link shared
3. Repo Files - files and folders sorting
4. PR compare/conversation - Search in reviewers doesnt work
5. PR conversation - searching for labels collapses it and shuts it off. Eventually it vanishes
6. PR compare/conversation - same query param is used to filter source and target branch
> fix: Repo Files sort, PR comments, reviewers labels and branch search

- apps/gitness/src/pages/pipeline-edit/utils/time-utils.ts
Used Math.abs() on time difference to ensure time are always shown as "X ago"
> feat: [pipe-24076]: fix issue with future time

- apps/design-system/src/subjects/views/repo-empty/repo-empty-view.tsx
- apps/gitness/src/framework/routing/types.ts
- apps/gitness/src/pages-v2/repo/repo-summary.tsx
- apps/gitness/src/routes.tsx
- packages/ui/src/views/repo/repo-summary/repo-empty-view.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
- Currently the `file-create` view breaks for an empty repo. (see attached video) Lets pick this up as a seperate PR. 
cc: @shaurya-harness 
https://github.com/user-attachments/assets/c986fe2b-d9b3-452f-a652-abec0e8647c0
> feat: add APIs and navigations

- packages/pipeline-graph/examples/src/main.tsx
- packages/pipeline-graph/src/components/canvas/canvas.css
- packages/pipeline-graph/src/components/canvas/canvas.tsx
- packages/ui/src/views/pipeline-edit/components/pipeline-studio-internal.tsx
- packages/ui/src/views/pipeline-edit/components/pipeline-studio-yaml-view.tsx
- packages/ui/src/views/pipeline-edit/pipeline-edit.tsx
- packages/ui/src/views/pipeline-edit/pipeline-studio.tsx
- packages/yaml-editor-playground/src/index.tsx
- packages/yaml-editor/src/components/YamlEditor.tsx
- react downgrade 18>17 fixes
- show move cursor while move canvas - pipeline-graph
- expose yamlEditorConfig (folding and minimap props of monaco editor) - yaml-editor
- fix "left line flickering"  - workaround - yaml-editor
> PS - Multiple improvements

- apps/gitness/src/components-v2/file-content-viewer.tsx
- apps/gitness/src/framework/hooks/useDownloadRawFile.ts
- apps/gitness/src/hooks/useAPIPath.ts
This hook adds required prefix to the API Path for MFE including window.apiURL along with /code and also adds routingId as a query param.
Before:
const rawURL = `${isMFE ? '/code' : ''}/api/v1/repos/${repoRef}/raw/${fullResourcePath}?git_ref=${fullGitRef}`
After:
const rawURL = useAPIPath(`/api/v1/repos/${repoRef}/raw/${fullResourcePath}?git_ref=${fullGitRef}`)
> Added useAPIPath hook to check for mfe condition

- Dockerfile
- Dockerfile.mfe
Update:
Using `alpine` as a base image instead of Nodejs dropped it from ~300mb to ~75mb!
> split docker images for mfe and standalone builds

- apps/design-system/src/subjects/views/pull-request-compare/pull-request-compare.tsx
- apps/design-system/src/subjects/views/pull-request-conversation/pull-request-changes.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-changes.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-compare.tsx
- packages/ui/src/hooks/use-memory-cleanup.ts
- packages/ui/src/styles.css
- packages/ui/src/views/repo/pull-request/compare/components/pull-request-compare-diff-list.tsx
- packages/ui/src/views/repo/pull-request/compare/pull-request-compare-page.tsx
- packages/ui/src/views/repo/pull-request/compare/pull-request-compare.types.ts
- packages/ui/src/views/repo/pull-request/components/in-view-diff-renderer.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-diff-viewer.tsx
- packages/ui/src/views/repo/pull-request/details/components/changes/pull-request-changes-filter.tsx
- packages/ui/src/views/repo/pull-request/details/components/changes/pull-request-changes.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-comment-box.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-overview.tsx
- packages/ui/src/views/repo/pull-request/details/pull-request-changes-page.tsx
- packages/ui/src/views/repo/pull-request/details/pull-request-details-types.ts
- packages/ui/src/views/repo/pull-request/details/pull-request-utils.ts
- packages/ui/src/views/repo/pull-request/utils.ts
PR changes page diffs optimizations :
1. scrollbar flicker on viewing diffs out of viewport
2. diff memory cleanup by toggling diff below viewport
3. jump to diff file on clicking filename in "x files changed" dropdown
> feat: [pipe-24076]: PR changes page diffs optimizations - scrollbar flickering and in view diffInstance cleanup

- packages/ui/src/components/alert/AlertContainer.tsx
- packages/ui/src/views/execution/console-logs.tsx
- packages/ui/src/views/execution/execution-header.tsx
- packages/ui/src/views/execution/execution-status.tsx
- packages/ui/src/views/execution/key-value-table.tsx
- packages/ui/src/views/execution/pipeline-status.tsx
- packages/ui/src/views/execution/step-execution.tsx
- packages/ui/src/views/repo/components/commits-list.tsx
- packages/ui/src/views/repo/repo.types.ts
- packages/ui/src/views/repo/webhooks/webhook-executions/repo-webhook-executions-page.tsx
This PR adds `avatarUrl` support to the `RepoCommitsView`. This PR also adds lint fixes that were left behind by another PR.
Fixes #951
> Add avatar support to `RepoCommitsView`

- packages/ui/src/views/repo/repo-commits/repo-commits-view.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
Making the below pages full width:
1. Repo Overview
2. Repo Files
3. Repo Files > File View
4. Repo Files > File Edit
5. Repo Files > Blame
6. Repo Commits
> Update Repo and commit page to full width

- packages/canary/src/components/navbar.tsx
- packages/ui/src/components/navbar-project-chooser.tsx
- packages/ui/src/components/navbar-skeleton/group.tsx
- packages/ui/src/components/navbar-skeleton/item.tsx
Updated spacing values ​​to visually match Figma design + fixed hover in nav, because previously it looked like this:
I fixed that, and now it's shows correctly:
> Nav spacings

- packages/ui/package.json
- packages/ui/vite-base.config.ts
This PR adds files that were missing from the `files` entry in the `package.json` file and ensures the `tailwind.config` entry is processed.
> chore: add exported files to files entry

- apps/design-system/src/subjects/views/execution/pipeline-execution-graph.tsx
- packages/pipeline-graph/src/components/nodes/leaf-container.tsx
- packages/pipeline-graph/src/components/nodes/parallel-container.tsx
- packages/pipeline-graph/src/components/nodes/serial-container.tsx
- packages/pipeline-graph/src/pipeline-graph-internal.tsx
- packages/pipeline-graph/src/render/render-node-content.tsx
- packages/pipeline-graph/src/types/nodes.ts
- packages/ui/src/components/pipeline-nodes/parallel-group-node.tsx
- packages/ui/src/components/pipeline-nodes/serial-group-node.tsx
- packages/ui/src/components/pipeline-nodes/stage-node.tsx
- packages/ui/src/components/pipeline-nodes/step-node.tsx
- packages/ui/src/components/pipeline-nodes/types.ts
- Integrates drawer to render on click of step.
- Refactor `readonly` prop to `mode` of type `'Edit' | 'Execution'` for extensibility.
https://github.com/user-attachments/assets/d7b0eaca-320a-40e5-8421-2e00c433d81f
> feat: Integrate Drawer with pipeline graph

- packages/ui/src/components/navbar-skeleton/item.tsx
- packages/ui/src/components/navbar/navbar-item/index.tsx
- packages/ui/src/views/labels/labels-list-page.tsx
- packages/ui/src/views/repo/webhooks/webhook-list/components/repo-webhook-list.tsx
- Fixes nav on `repo-settings` page. Fixes hover inside `webhook-list`. 
https://github.com/user-attachments/assets/f232bf1b-0c90-4263-99e2-11c267435394
- Fixes icon on navbar. 
Earlier: 
Now: 
- Allow `labels` page to occupy as much width as available and align to the left with `webhooks` and `settings`.
> Fixes across pages

- packages/yaml-editor-playground/src/examples/data-flow/YamlEditorWrapper.tsx
- packages/yaml-editor/src/components/BlameEditor.tsx
- packages/yaml-editor/src/components/CodeEditor.tsx
- packages/yaml-editor/src/components/DiffEditor.tsx
- packages/yaml-editor/src/components/YamlEditor.tsx
- packages/yaml-editor/src/constants/monaco-common-default-options.ts
- use same default options for all editors
- 13px default font size
- hide unnecessary elements
> Yaml Editor fixes

- packages/ui/src/components/treeview.tsx
- packages/ui/src/views/execution/execution-status.tsx
- packages/ui/src/views/pipelines/components/execution-status-badge.tsx
- packages/ui/src/views/pipelines/components/execution-status-icon.tsx
> Fixed success icon color

- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/components/floating-add-button.tsx
> fix: style add button

- packages/ui/src/shared-style-variables.css
This pull request makes corrections to the gradients for the widget on the `Repo Summary` page
**Dark Std Std**
**Light Std Std**
**Light Std Prot**
> feat: add widget gradient color variables for light and dark themes

- apps/gitness/src/AppMFE.tsx
- apps/gitness/src/framework/context/MFEContext.tsx
- apps/gitness/src/pages-v2/repo/repo-summary.tsx
- packages/ui/src/views/repo/components/token-dialog/clone-credential-dialog.tsx
- packages/ui/src/views/repo/repo-summary/repo-empty-view.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
fixes:
empty repo page based on is_empty from repoMetadata
profile keys route is different for NGUI - passed navigate hook as part of customUtil
clone credential token generation api is different for NGUI, goes through gateway and is passed as a hook from NGUI - added the customHook to be used in case of MFE
> fix: repo summary empty state and generateToken from NGUI MFE

- apps/gitness/src/App.tsx
- packages/ui/src/components/commit-copy-actions.tsx
- packages/ui/src/components/file-additions-trigger.tsx
- packages/ui/src/components/file-explorer.tsx
- packages/ui/src/components/markdown-viewer/index.tsx
- packages/ui/src/components/more-actions-tooltip.tsx
- packages/ui/src/components/more-submenu.tsx
- packages/ui/src/components/navbar/navbar-item/index.tsx
- packages/ui/src/components/navbar/navbar-user/index.tsx
- packages/ui/src/components/navbar/navbar.tsx
- packages/ui/src/components/no-data.tsx
- packages/ui/src/components/path-breadcrumbs.tsx
- packages/ui/src/components/settings-menu.tsx
- packages/ui/src/components/styled-link.tsx
- packages/ui/src/components/tabnav.tsx
- packages/ui/src/context/RouterContext.tsx
- packages/ui/src/context/index.ts
**Migration - Part 1**
Removes references of `react-router-dom` from `packages/ui/src/components`.
Usage with `react-router-dom` `v6`
```
<RouterProvider>
<Routes>
<Route path="/" element={<Home />} />
<Route path="/about" element={<About />} />
</Routes>
</RouterProvider>
```
Usage with `react-router-dom` `v5` : Uses `Switch`
```
<RouterProvider>
<Navigation />
<Switch>
<Route path="/" exact component={Home} />
<Route path="/about" exact component={About} />
</Switch>
</RouterProvider>
```
> chore: Remove dependency on 'react-router-dom' from 'packages/ui'

- packages/ui/src/components/navbar-new/app-sidebar.tsx
- packages/ui/src/components/navbar-new/sidebar-item.tsx
- packages/ui/src/components/navbar-new/sidebar-user.tsx
Used the new `useRouterContext()` utility for importing React Router Dom elements instead of using the package itself.
> Remove react-router-dom dependencies from sidebar

- Dockerfile
- Dockerfile.mfe
we were using pnpm-10 for docker, which started failing with a frozen lockfile error.
but it works locally with pnpm-9, so i've pushed that change.
> fix: use pnpm 9 for docker

- apps/portal/src/content/docs/components/radial-input.mdx
- packages/ui/src/views/components/RadialInput.tsx
- packages/ui/src/views/index.ts
- packages/ui/src/views/secrets/secrets-header.tsx
basically updated the radial component in the secrets header to be reusuable
> feat: create a radial reusuable component

- apps/design-system/src/pages/view-preview/app-view-wrapper.tsx
Sidebar provider was missing from Design System, hence breaking the page. This PR adds the missing Sidebar Provider and makes a few layout changes for the new sidebar to work.
https://github.com/user-attachments/assets/6e05a7aa-ffbc-46e1-96d0-6d12f84aa8d3
> Add sidebar provider and make layout changes for new sidebar

- apps/gitness/src/components-v2/app-shell.tsx
- apps/gitness/src/pages-v2/repo/repo-create-page.tsx
- packages/ui/locales/en/component.json
- packages/ui/locales/fr/component.json
- packages/ui/src/views/repo/repo-create/index.tsx
https://github.com/user-attachments/assets/e0d335c5-4155-4749-be83-5e5f11f6f5d3
> fix: duplicate toaster

- apps/gitness/src/pages-v2/pull-request/hooks/usePRCommonInteractions.ts
- packages/ui/src/shared-style-variables.css
:host was added to make styles work for Canary components in NGUI without having to import shared styles in index.scss
But, adding :host breaks styles inside a PortalContainer (Dialogs, Drawers, etc.) in MFE. Hence, removed it for now.
> Removed host from shared styles

- apps/gitness/src/AppMFE.tsx
- apps/gitness/src/hooks/useLoadMFEStyles.ts
- apps/gitness/src/styles/AppMFE.css
- packages/ui/src/context/portal-context.tsx
- packages/ui/src/shared-style-variables.css
This PR aims to fix the styling for Canary Components rendered in NGUI without having to import the Shared Styles separately in NGUI index.scss
Adding :host selector for CSS variables fixed this issue previously, but was breaking the styling for Radix UI elements rendered inside a container. That issue is also taken care of in this PR.
Before Change:
https://github.com/user-attachments/assets/85e82f41-3baf-4559-9b64-e71e62ae924e
After Change:
https://github.com/user-attachments/assets/57f7c580-775a-4300-b588-8d617ab16899
Standalone Test:
https://github.com/user-attachments/assets/b45f8142-72c5-4da9-a78c-0af778748c6c
> Fix canary components styling inside a Shadow Root

- packages/ui/src/components/sheet.tsx
In this [PR](https://github.com/harness/canary/pull/1292), the display of the "Settings" and "More" submenus in the sidebar was broken.
The issue occurred when `modal=false`.
> fix: fix sheet component when modal false

- apps/gitness/src/components-v2/breadcrumbs/breadcrumbs.tsx
- packages/ui/package.json
- packages/ui/src/components/alert-dialog.tsx
- packages/ui/src/components/app-sidebar/app-sidebar.tsx
- packages/ui/src/components/app-sidebar/sidebar-item.tsx
- packages/ui/src/components/app-sidebar/sidebar-search-legacy.tsx
- packages/ui/src/components/app-sidebar/sidebar-search/sidebar-search.tsx
- packages/ui/src/components/button-with-options.tsx
- packages/ui/src/components/dialog.tsx
- packages/ui/src/components/language-selector/language-dialog.tsx
- packages/ui/src/components/more-submenu.tsx
- packages/ui/src/components/navbar-skeleton/group.tsx
- packages/ui/src/components/navbar-skeleton/item.tsx
- packages/ui/src/components/settings-menu.tsx
- packages/ui/src/components/sheet.tsx
- packages/ui/src/components/sidebar/sidebar.tsx
- packages/ui/src/components/topbar.tsx
- packages/ui/src/context/theme/types.ts
- packages/ui/src/shared-style-variables.css
- packages/ui/src/styles.css
- packages/ui/src/views/layouts/main-content-layout.tsx
- packages/ui/src/views/layouts/subheader-wrapper.tsx
- packages/ui/src/views/repo/repo-files/index.tsx
- packages/ui/src/views/repo/repo-sidebar/index.tsx
- packages/ui/tailwind.ts
- Increased icon sizes from 12px to 14px for "More", "User Management", and "Settings" menu items
- Added Inset mode support for sidebar with corresponding spacing
- Updated navigation elements styling with light/dark theme support
- Implemented new submenu spacing system (228px in Inset mode, 220px in regular mode)
- Integrated `useTheme` hook across sidebar components for consistent theme handling
- Updated color variables in `shared-style-variables.css`
- Added new style variants for light theme
- Implemented special topbar styles for light theme
- Sheet: added `isLightTheme` variant for proper theme-based rendering
- Breadcrumbs: updated hover effects based on current theme
- NavbarSkeleton: reworked styling system with gradient support for active elements
- SidebarSearchLegacy: …
> feat: new light theme / inset theme for light and black theme

- packages/ui/src/components/tabnav.tsx
fix summary line
-Can we make the line under "Summary" to be 2px instead of 1px and use a dark black color?
> fix: fix summary line

- packages/ui/src/views/connectors/connector-entity-form.tsx
- packages/ui/src/views/connectors/connector-reference/connector-reference.tsx
- packages/ui/src/views/connectors/connectors-pallete-drawer.tsx
- packages/ui/src/views/unified-pipeline-studio/components/palette-drawer/components/step-palette-content-layout.tsx
- packages/ui/src/views/unified-pipeline-studio/components/palette-drawer/components/step-palette-item-layout.tsx
fix connector form and pallette issues:
search doesn't work (eg. typing "github" returns 0 results)
header and content padding is too much on both drawers (footer has the correct padding)
entire card is not clickable when selecting a connector
in connector reference screen, "select an existing connector" line is extra
> feat: fix connector form and pallette

- .eslintrc.json
This PR removes the ESLint rule to restrict canary imports now that the canary package has been removed.
> chore: remove unneeded eslint rule

- apps/portal/src/content/docs/components/dropdown-menu.mdx
- packages/ui/src/components/dropdown-menu.tsx
This PR adds documentation for the `DropdownMenu` components.
Fixes #1224
> feat: add documentation for the `DropdownMenu` components

- apps/gitness/src/App.tsx
- apps/gitness/src/framework/context/AppRouterProvider.tsx
- apps/gitness/src/routes.tsx
- Moves `RouterContextProvider` inside `RouterProvider` to allow calling `useNavigate` hooks and pass down the correct implementation of `navigate` function to be used via `useRouterContext`.
- This fixes the unexpected re-routing issue seen while visiting Pull Requests list page.
**Without fix:**
https://github.com/user-attachments/assets/74d1266a-37dc-4af3-99eb-740b651a0129
**With fix:**
https://github.com/user-attachments/assets/b959600e-814f-4305-849a-463eaf1765f4
> fix: Add App Router Provider to avoid re-routing issue

- apps/design-system/src/App.tsx
- apps/design-system/src/AppRouterProvider.tsx
- apps/gitness/src/AppMFE.tsx
- apps/gitness/src/routes.tsx
Fixed the same issue mentioned here #1413 for mfe and design-system
Updated `window.location` to `useLocation`, 
since mfe would break if window.location is used, as it will contain path for both parent app and child mfe
https://github.com/user-attachments/assets/85c78e20-bda7-406b-b46f-b66348fc6b44
https://github.com/user-attachments/assets/e767f97d-0d77-4163-b80a-acda6891eb3c
> fix: added router issue for both mfe and design-system

- apps/portal/astro.config.ts
- apps/portal/src/wrap-code-blocks.ts
This PR adds a small rehype plugin to wrap all code blocks in an extra div which adds the `dark` and `dark-std-std` classes temporarily until the whole page can be modified to apply these classes without breaking the experience.
|Before|After|
|------|------|
|![Before](https://github.com/user-attachments/assets/b7bb2215-b4a4-415d-acf8-247786525b5f)|![After](https://github.com/user-attachments/assets/826bd83e-fb0e-4a35-a569-c79cb542153a)|
Fixes #1425
> fix: Wrap code blocks with dark and dark-std-std classes

- apps/portal/astro.config.ts
- apps/portal/src/components/CompactIconGrid.astro
- apps/portal/src/components/docs-page/component-example.tsx
- apps/portal/src/components/docs-page/example.tsx
- apps/portal/src/components/layout/PageFrame.astro
- apps/portal/src/content/docs/components/accordion.mdx
- apps/portal/src/styles.css
This PR alters the code example component to render with the example code collapsed by default.
|Before|After|
|------|------|
|![Before](https://github.com/user-attachments/assets/51b0acd8-bd41-4948-9331-06b555c7ef52)|![After](https://github.com/user-attachments/assets/d1ed7650-1c96-45c2-bdbf-9f0680229c56)|
||![After](https://github.com/user-attachments/assets/b20f544e-6a0f-451f-b938-b544d555c6d3)|
|![Before](https://github.com/user-attachments/assets/45e7b752-5eeb-4a26-afd5-55d4e3ea8380)|![After](https://github.com/user-attachments/assets/9d92504c-556d-4cf2-902b-d11b8aa1c11c)|
||![After](https://github.com/user-attachments/assets/f9241f0f-505c-4994-a94a-4728614536d7)|
fixes #1464
> feat: Collapse example code by default

- apps/design-system/src/subjects/views/repo-branches/index.tsx
- apps/gitness/src/components-v2/branch-selector-container.tsx
- apps/gitness/src/components-v2/create-branch-dialog.tsx
- apps/gitness/src/pages-v2/repo/repo-branch-list.tsx
- apps/gitness/src/pages-v2/repo/repo-sidebar.tsx
- apps/gitness/src/pages-v2/repo/repo-tags-list-container.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/components/toast/use-toast.ts
- packages/ui/src/views/repo/components/branch-selector-v2/branch-selector-dropdown.tsx
- packages/ui/src/views/repo/components/branch-selector-v2/branch-selector.tsx
- packages/ui/src/views/repo/components/branch-selector/branch-selector.tsx
- packages/ui/src/views/repo/components/branch-selector/types.ts
- packages/ui/src/views/repo/repo-branch/components/create-branch-dialog.tsx
- packages/ui/src/views/repo/repo-branch/repo-branch-list-view.tsx
- packages/ui/src/views/repo/repo-branch/types.ts
This PR introduces a new component that encapsulates all data-fetching logic for the CreateBranchDialog UI component, following the common approach described in the [wiki](https://github.com/harness/canary/wiki/State-Management-Patterns) 
Key changes include:
1. Added a new reusable `CreateBranchDialog` component in `apps/gitness/src/components-v2/create-branch-dialog.tsx` that provides a consistent interface for branch creation throughout the application.
2. Improved the branch selector component by adding a `preSelectedTab` prop that allows pre-selecting either branches or tags tab when opening the selector. We need it to preselect Tag tab, when user selects Create Branch menu from a specific tag on Tags page
3. Integrated the toast notification system for branch creation with a new …
> changes in branch selector

- packages/ui/tailwind-utils-config/components/badge.ts
From the design tokens, `--cn-set-gray-solid-border` has been removed. Hence updating the default border as `--cn-set-gray-surface-border`.
> Update badge component with correct fallback and default border color

- apps/design-system/src/subjects/views/project-create/project-create-view.tsx
- apps/gitness/src/framework/routing/types.ts
- apps/gitness/src/pages-v2/create-project.tsx
- apps/gitness/src/routes.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/components/button.tsx
- packages/ui/src/views/project/create-project-page.tsx
This PR enhances the Create Project page by adding an "Import project" option alongside the existing "Create project" functionality. This improvement provides users with a clear path to either create a new project from scratch or import an existing one.
- Added a visual separator with "or" text between the primary actions
- Implemented a new "Import project" button that routes users to the `/import` path
- Enhanced the layout to accommodate both options in a visually balanced way
- Added new translation strings for both English and French:
- `views:createProject.or`: "or" / "ou"
- `views:createProject.importProject`: "Import project" / "Importer un projet"
This enhancement improves user experience by providing clear pathways for both creating new projects and importing existing ones …
> Added Import Page button to the Create Project page

- packages/ui/src/components/commit-suggestions-dialog/commit-suggestions-dialog.tsx
- packages/ui/src/views/auth/forgot-password-page.tsx
- packages/ui/src/views/auth/new-password-page.tsx
- packages/ui/src/views/auth/otp-page.tsx
- packages/ui/src/views/auth/signin-page.tsx
- packages/ui/src/views/auth/signup-page.tsx
- packages/ui/src/views/labels/label-form-page.tsx
- packages/ui/src/views/pipelines/create-pipeline-dialog/create-pipeline-dialog.tsx
- packages/ui/src/views/profile-settings/components/profile-settings-keys-create-dialog.tsx
- packages/ui/src/views/profile-settings/components/profile-settings-token-create-dialog.tsx
- packages/ui/src/views/profile-settings/profile-settings-general-page.tsx
- packages/ui/src/views/repo/repo-branch/components/create-branch-dialog.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-form.tsx
This PR enhances form validation across the application by removing unnecessary validation checks that block form submissions, improving user experience by allowing users to attempt submissions even when validation errors are present.
- Removed `isValid` checks from form submission buttons in multiple components, the submit button should not be disabled from pressing
- Server-side validation errors will still be properly displayed
- Form fields will still show individual validation errors to guide users
- Added proper Alert components to display server errors in authentication forms
> Remove the disabled state from the submit button in forms

- packages/ui/src/components/tag.tsx
- packages/ui/tailwind-utils-config/components/tag.ts
The tag class was breaking the `Show Code` section in the portal app, hence we decided to prefix all the design system classes with "cn-" going forward.
This PR fixes the UI for the `Show Code` section in the portal app.
> Prefixed tag classes with "cn-"

- packages/ui/locales/en/component.json
- packages/ui/locales/fr/component.json
- packages/ui/src/components/searchable-dropdown/searchable-dropdown.tsx
- packages/ui/src/components/sorts/index.ts
- packages/ui/src/components/sorts/multi-sort.tsx
- packages/ui/src/components/sorts/sort-context.tsx
- packages/ui/src/components/sorts/sort-select.tsx
- packages/ui/src/components/sorts/sort.tsx
- packages/ui/src/components/sorts/type.ts
Added support for sort with sort selection and multi-sort
TODO - Once single-sort design is ready, create new component under Sort
```
<Sort.Root {..props}> <br>
<Sort.Select>       // list sort to select from
<Sort.MultiSort>. //  Add additional sorts .. Update sort order
</Sort.Root>
```
This screenshot is just an example usage of sort and pr-list-page does not contain any sort
> feat: added support for genenric sort

- packages/forms/package.json
- packages/forms/src/core/utils/utils.ts
fixes getDefaultValuesFromFormDefinition if inputs are not readily available
> fix: getDefaultValuesFromFormDefinition if inputs are not readily available

- packages/ui/src/components/dropdown-menu.tsx
- packages/ui/src/components/filters/filters-field.tsx
- packages/ui/src/components/git-commit-dialog/git-commit-dialog.tsx
- packages/ui/src/components/radio.tsx
- packages/ui/src/components/split-button.tsx
- packages/ui/src/views/labels/label-form-page.tsx
- packages/ui/src/views/labels/labels-list-page.tsx
- packages/ui/src/views/project/project-import.tsx
- packages/ui/src/views/repo/pull-request/components/labels/labels-filter.tsx
- packages/ui/src/views/repo/pull-request/details/components/changes/pull-request-changes-filter.tsx
- packages/ui/src/views/repo/pull-request/details/components/changes/pull-request-changes.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-panel.tsx
- packages/ui/src/views/repo/repo-branch-rules/components/repo-branch-rules-fields.tsx
- packages/ui/src/views/repo/repo-create/index.tsx
- packages/ui/src/views/repo/repo-import/repo-import-mulitple.tsx
- packages/ui/src/views/repo/repo-import/repo-import.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-form.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-security.tsx
- packages/ui/src/views/repo/webhooks/webhook-create/components/create-webhooks-form-fields.tsx
Added optional attribute for checkbox and radio instances so that they are not required. We missed adding it while migrating to the new design system.
> Add optional attribute for checkbox and radio instances

- packages/ui/src/components/sorts/sort-select.tsx
On selecting a sort from sort-select does not open the sort dropdown to further configure the order of the sort
> fix: auto-open sort dropdown on selecting a sort option

- packages/ui/src/components/checkbox.tsx
- packages/ui/src/components/dropdown-menu.tsx
- packages/ui/src/components/filters/filters-field.tsx
- packages/ui/src/components/git-commit-dialog/git-commit-dialog.tsx
- packages/ui/src/components/radio.tsx
- packages/ui/src/components/split-button.tsx
- packages/ui/src/components/switch.tsx
- packages/ui/src/views/labels/label-form-page.tsx
- packages/ui/src/views/labels/labels-list-page.tsx
- packages/ui/src/views/project/project-import.tsx
- packages/ui/src/views/repo/pull-request/components/labels/labels-filter.tsx
- packages/ui/src/views/repo/pull-request/details/components/changes/pull-request-changes-filter.tsx
- packages/ui/src/views/repo/pull-request/details/components/changes/pull-request-changes.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-panel.tsx
- packages/ui/src/views/repo/repo-branch-rules/components/repo-branch-rules-fields.tsx
- packages/ui/src/views/repo/repo-create/index.tsx
- packages/ui/src/views/repo/repo-import/repo-import-mulitple.tsx
- packages/ui/src/views/repo/repo-import/repo-import.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-form.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-security.tsx
- packages/ui/src/views/repo/webhooks/webhook-create/components/create-webhooks-form-fields.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/BooleanInput.tsx
The `optional` prop will now apply only to the label and not to the element.
The `optional` prop is now renamed to `showOptionalLabel`.
Validation can be taken care of by validation libraries, so we are no longer taking into account the optional attribute for setting the required attribute of the elements.
> Change in the Optional prop behavior for Radio, Switch and Checkbox

- packages/core-design-system/scripts/sd-file-generators.js
It will build the pure transparent color like:
```css
--cn-pure-transparent: lch(from var(--cn-pure-black) l c h / 0);
```
> Fix pure transparent token studio script build

- apps/portal/src/content/docs/components/advanced-table.mdx
- apps/portal/src/content/docs/components/table-v2.mdx
- packages/ui/src/components/table-v2.tsx
- packages/ui/tailwind-utils-config/components/table-v2.ts
- Fixes link-cell / linked-row styles and behavior. 
- Renames `advanced-table` to `data-table`
> Minor table fixes

- packages/ui/src/views/connectors/connector-entity-form.tsx
- packages/ui/src/views/connectors/connectors-list/utils.ts
- packages/ui/src/views/connectors/connectors-pallete-drawer.tsx
- packages/ui/src/views/repo/components/list-control-bar.tsx
1. Added connector info like name, type and other params under meta to not collide with connector spec names in form
2. Updated resetFilter fn to not pass any value, since changes has been added to reset selected filters based on param
3. Updated connector logo map for new connectors that got added
4. Fixed the issue where input quert is getting cleared on closing the drawer in connectors pallete
> fix: Minor issue fixes on connectors list and details page

- apps/portal/src/content/docs/components/button.mdx
- apps/portal/src/content/docs/components/split-button.mdx
- apps/portal/src/content/docs/components/toggle-group.mdx
- apps/portal/src/content/docs/components/toggle.mdx
- packages/ui/src/components/button.tsx
- packages/ui/src/components/split-button.tsx
- packages/ui/src/components/toggle-group.tsx
- packages/ui/src/components/toggle.tsx
> Update Button component default size and Add disabled state for SplitButton

- packages/ui/src/components/dropdown-menu.tsx
- packages/ui/tailwind-design-system.ts
Add icon colors for multi-type input icons and support setting icon color in dropdown menu.
https://github.com/user-attachments/assets/8a77a98d-ea5f-4b41-b831-e7123a31d569
> Icon colors for multi-type input

- packages/ui/global.d.ts
- packages/ui/src/components/drawer/DrawerRoot.tsx
- packages/ui/vite-base.config.ts
Root cause -
vaul pkg seems to have some custom styles, which is getting injected into document head by default,
this would not work for components under shadow-dom
Resolutions
1. We can import the style file directly into ui pkg styles, which would then by imported dynamically under mfe
- Tried this approach, but some style selector in vaul pkg seems to be broken, due to which our build would fail on import
2. We can duplicate whole styles under vaul pkg into ui pkg
- Maintenance overhead
3. Import the styles from vaul as raw and inject it under portalContainer, while initializing drawer.root
- Went with this approach
https://github.com/user-attachments/assets/2f633478-2676-4734-887c-02ecd5cf0a59
> fix: support for drawer animation under mfe

- apps/portal/src/content/docs/components/card-select.mdx
- packages/ui/src/components/card-select.tsx
- packages/ui/tailwind-utils-config/components/card-select.ts
This PR takes care of the following:
- Changes `orientation` prop to `layout`
- Adds an option for `grid` layout where the user can pass `rows` and `cols` to structure the grid
- Adds `overflow` to the the horizontal and vertical layouts
- Modifies the docs to reflect all these changes
https://github.com/user-attachments/assets/26a5af85-f008-4bc9-877e-ca55225aaa7e
> Card Select grid layout and other minor updates

- apps/design-system/src/subjects/views/templates/view-only.tsx
- packages/ui/locales/en/component.json
- packages/ui/locales/fr/component.json
- packages/ui/src/components/command.tsx
- packages/ui/src/components/index.ts
- packages/ui/src/components/node-group.tsx
- packages/ui/src/components/sidebar/sidebar.tsx
- packages/ui/src/components/widgets.tsx
- packages/ui/src/views/execution/step-execution.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-diff-viewer.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-comment-box.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-timeline-item.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/regular-and-code-comment.tsx
- packages/ui/tailwind-utils-config/components/table-v2.ts
- new `Page` component (for quickly creating a page) – contains atoms: `Page.Root`, `Page.Header`, `Page.Content`
- `Page.Header` – a template component for page headers of any type, includes many settings for building any kind of header
- `Widgets` component – a list of widgets for displaying entity data
- `ViewOnly` component – a component for displaying entity data in read-only mode
- made a fix in the Table so that horizontal scrolling works when needed
[Loom with an overview](https://www.loom.com/share/b8e4a742256e4f58b4dc82b642925006?sid=52cd6b26-3b7c-46d3-8a69-fa2144d46542)
> Templates widgets

- apps/gitness/src/components-v2/breadcrumbs/breadcrumbs.tsx
- apps/gitness/src/components-v2/mfe/app-shell.tsx
- apps/gitness/src/components-v2/standalone/app-shell.tsx
- packages/ui/src/views/layouts/main-content-layout.tsx
* fix: remove sidebar from mfe
Adds reverted changes back.
> Fix mfe navbar (#1903)

- packages/ui/src/styles/styles.css
- packages/ui/src/views/repo/pull-request/components/pull-request-diff-viewer.tsx
> Update styles for new diff line widgets and adjust layout in pull request diff viewer

- apps/design-system/src/subjects/views/search-page/search-results-store.ts
- packages/ui/src/views/search/components/search-results-list.tsx
- packages/ui/src/views/search/search-page.tsx
Adds styling fixes, and also adds a expand/collapse behaviour.
Collapsed:
Expanded:
> Search followup 1

- packages/ui/src/components/toast/toaster.tsx
> fix success toast vertical alignment

- apps/design-system/src/subjects/views/search-page/search-page-preview.tsx
- apps/gitness/src/pages-v2/search-page.tsx
- packages/ui/src/views/search/components/search-results-list.tsx
- packages/ui/src/views/search/search-page.tsx
Adds missing parity items on search page:
- Repo filter (if you're NOT in repo scope_
- Language filter
- Clear filter
- query syncing to maintain state
Note: design looks broken right now due to the `horizontal` variant of the Select not working correctly. Reported that issue separately to the PP team.
> feat: add search filters support

- apps/design-system/src/subjects/views/repo-list/repo-list.tsx
- apps/gitness/src/pages-v2/repo/repo-list.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/components/file-additions-trigger.tsx
- packages/ui/src/views/components/FilterGroup.tsx
- packages/ui/src/views/repo/components/path-action-bar.tsx
- packages/ui/src/views/repo/repo-branch/repo-branch-list-view.tsx
- packages/ui/src/views/repo/repo-list/repo-list-page.tsx
- packages/ui/src/views/repo/repo-list/types.ts
- packages/ui/src/views/repo/repo-summary/repo-empty-view.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
- packages/ui/src/views/repo/repo-tags/repo-tags-list-page.tsx
- packages/ui/src/views/search/search-page.tsx
Integrate "favorite" filter on Repo listing page
https://github.com/user-attachments/assets/ab2a3ef3-8190-45b4-83bc-88575247be19
---
- Renames button labels from `+ Create New File` to just `Create File`.
- Fixes button variant.
- Fixes headers for pages under Repository to same equal top spacing.
> feat: Integrate "favorite" filter on Repo listing page, few other miscellaneous changes

- apps/design-system/src/subjects/views/repo-create/index.tsx
- apps/design-system/src/subjects/views/repo-create/repo-create-store.tsx
- apps/gitness/src/pages-v2/repo/repo-create-page.tsx
- packages/ui/src/views/repo/repo-create/index.tsx
Removes dropdown and uses input (defaulted to `main`) that allows entry of custom name.
> add input to create repo form for default branch

- apps/gitness/src/pages-v2/repo/repo-layout.tsx
- packages/ui/src/components/repo-subheader.tsx
- packages/ui/src/components/tabs.tsx
- packages/ui/tailwind-utils-config/components/tabs.ts
**FIX**
1.  ***Empty Repository Behavior*** -  When a repository had `no files`, we `disabled` other tab options like Files, Commits, Tags, Pull Requests, Branches, and Search.
https://github.com/user-attachments/assets/51315cf5-5d5a-473a-b510-4418eb55a76b
> Disabled tab access for empty repo

- packages/ui/src/components/tabs.tsx
For some reason a tab content is focusable by default. Now the focus goes directly to the inner components
> fix tabs content focus issue

- packages/ui/src/components/dropdown-menu.tsx
- packages/ui/src/components/inputs/base-input.tsx
- packages/ui/src/components/inputs/search-input.tsx
- packages/ui/src/components/inputs/text-input.tsx
- packages/ui/src/views/repo/pull-request/components/labels/label-value-selector.tsx
- packages/ui/src/views/repo/pull-request/components/labels/pull-request-labels-header.tsx
https://github.com/user-attachments/assets/6e7508ce-629a-4ac4-b9bd-c66341ef3981
> Fix PR labels keyboard navigation and layout

- packages/ui/src/components/file-explorer.tsx
- packages/ui/src/views/repo/pull-request/details/components/changes/pull-request-changes-explorer.tsx
> fix overflow of file item

- apps/gitness/src/pages-v2/repo/repo-sidebar.tsx
- packages/ui/src/components/no-data.tsx
- packages/ui/src/views/labels/components/labels-list-view.tsx
- packages/ui/src/views/profile-settings/components/profile-settings-keys-list.tsx
- packages/ui/src/views/profile-settings/components/profile-settings-tokens-list.tsx
- packages/ui/src/views/profile-settings/profile-settings-keys-page.tsx
- packages/ui/src/views/project/project-general/project-general-page.tsx
- packages/ui/src/views/project/project-members/components/member-list.tsx
- packages/ui/src/views/project/project-members/projects-member-page.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-header.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-timeline-item.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-delete.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-form.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-rules.tsx
- packages/ui/src/views/repo/repo-tags/components/repo-tags-list.tsx
- packages/ui/src/views/repo/repo-tags/repo-tags-list-page.tsx
- packages/ui/src/views/repo/webhooks/webhook-list/components/repo-webhook-list.tsx
- packages/ui/src/views/user-management/components/page-components/actions/actions.tsx
- packages/ui/src/views/user-management/components/page-components/content/components/users-list/users-list.tsx
Refactoring of the dialog trigger on other repo page:
- files
- pull request page
- tags
- repo settings
- general settings
- users list page
After modals closed, a focus returns to triggers, but not the page body.
> Refactor dialog trigger on other repo page

- packages/ui/src/views/labels/components/label-tag.tsx
- packages/ui/src/views/repo/pull-request/components/labels/label-value-selector.tsx
- additionally added more space to the search placeholder
> fix label with no value
