- apps/playground/public/styles.css
- apps/playground/src/assets/mock.ts
- apps/playground/src/pages/Execution.tsx
- apps/storybook/src/stories/screens/Execution.stories.tsx
- packages/canary/package.json
- packages/canary/src/components/treeview.tsx
- Added missing background for select file inside a folder.
- Added a playground page for rendering Tree View component.
> Fix selected file background in Tree View component

- apps/storybook/src/stories/screens/PRList.stories.tsx
> feat: [pipe-20761]: add pr listing page

- apps/storybook/src/stories/design-system/Colors.stories.tsx
- packages/canary/src/styles.css
- packages/canary/tailwind.config.js
e.g. bg-shade-0 will display background color of white (for light mode) or black for (dark mode).
> Mapped all Pixel Point grey shades for theme adaptive presentation

- apps/storybook/src/stories/design-system/Colors.stories.tsx
- packages/canary/src/styles.css
- packages/canary/tailwind.config.js
> feat: semantic colors for theming

- packages/playground/src/components/pull-request/interfaces.ts
- packages/playground/src/components/pull-request/pull-request-conversation.tsx
- packages/playground/src/components/pull-request/pull-request-filters.tsx
- packages/playground/src/components/pull-request/utils.tsx
> feat: [pipe-20916]: add pr filter for pr page

- packages/canary/src/styles.css
- packages/playground/src/components/pull-request/pull-request-conversation-header.tsx
- packages/playground/src/components/pull-request/pull-request-list.tsx
- packages/playground/src/components/pull-request/pull-request-side-bar.tsx
fix colors and use tailwind tokens
> feat: [pipe-20916]: fix colors and use tailwind tokens

- packages/canary/src/styles.css
- packages/playground/src/components/pull-request/pull-request-side-bar.tsx
> feat: [pipe-20916]: fix warning color

- packages/playground/src/components/pull-request/interfaces.ts
- packages/playground/src/components/pull-request/mocks/mockChangesData.ts
- packages/playground/src/components/pull-request/mocks/mockPullReqMetadata.ts
- packages/playground/src/components/pull-request/pull-request-conversation.tsx
- packages/playground/src/components/pull-request/pull-request-panel.tsx
> feat: [pipe-20916]: start skeleton of pr panel

- packages/canary/src/styles.css
- packages/canary/tailwind.config.js
- packages/playground/src/components/contact-card.tsx
- packages/playground/tailwind.config.js
Review comments from https://github.com/harness/canary/pull/119
> chore: [PIPE-21142]: Review comments from PR#119

- packages/playground/src/components/pull-request/interfaces.ts
- packages/playground/src/components/pull-request/pull-request-conversation.tsx
- packages/playground/src/components/pull-request/pull-request-panel.tsx
- packages/playground/src/components/pull-request/sections/pull-request-changes-section.tsx
- packages/playground/src/components/pull-request/sections/pull-request-check-section.tsx
added a changes section component and pulled the mocked data/api to the parent component
> feat: [pipe-20916]: fix changes section and pull stuff to parent lvl

- packages/playground/src/components/pull-request/mocks/mockChecksData.ts
- packages/playground/src/components/pull-request/mocks/mockPullReqMetadata.ts
> feat: [pipe-20916]: fix data

- packages/canary/src/components/icon.tsx
- packages/canary/src/icons/no-data-cog.svg
- packages/canary/src/icons/no-data-folder.svg
- packages/canary/src/icons/no-data-merge.svg
- packages/canary/src/icons/no-search-magnifying-glass.svg
- packages/playground/src/components/loaders/skeleton-list.tsx
- packages/playground/src/components/no-list-data.tsx
- packages/playground/src/components/no-search-results.tsx
- packages/playground/src/components/playground/list-settings.tsx
- packages/playground/src/components/repo-list.tsx
- packages/playground/src/layouts/RepoExecutionLayout.tsx
- packages/playground/src/pages/execution-list-page.tsx
- packages/playground/src/pages/pipeline-list-page.tsx
- packages/playground/src/pages/pull-request-list-page.tsx
- packages/playground/src/pages/repo-execution-list-page.tsx
- packages/playground/src/pages/repo-list-page.tsx
- packages/playground/src/pages/repo-pipeline-list-page.tsx
Add a state chooser
- Data loaded
- Loading
- No data
- No search matches
> Show list states

- packages/yaml-editor-playground/src/App.css
- packages/yaml-editor-playground/src/configurations/inline-actions/inline-actions-def.ts
- packages/yaml-editor-playground/src/examples/data-flow/YamlEditorWrapper.tsx
- packages/yaml-editor/package.json
- packages/yaml-editor/src/components/YamlEditor.tsx
- packages/yaml-editor/src/hooks/useDecoration.tsx
Highlighting code using paths. Optionally we can pass revealInCenter.
> Add selection feature to yaml-editor

- packages/playground/src/components/no-list-data.tsx
- packages/playground/src/pages/execution-details-page.tsx
- packages/playground/src/pages/pipeline-edit-page.tsx
- packages/playground/src/pages/pr-details.tsx
Fix type issues encountered while building `playground` package.
> Fix build issues for `playground` package

- packages/playground/src/components/pull-request/sections/pull-request-check-section.tsx
> feat: [pipe-20916]: fix grid in check section

- packages/playground/src/components/execution/key-value-table.tsx
- Add recursive component currently and fix complex padding style of children components and border 
- ![Screenshot 2024-08-30 at 4 32 06 PM](https://github.com/user-attachments/assets/9d669c35-84a1-47c4-a1de-78c812ccef23)
- Change arrow from left to right from accordion extension
> Input accordion advanced

- packages/playground/src/components/pull-request/sections/pull-request-changes-section.tsx
- packages/playground/src/data/mockCodeOwner.ts
- packages/playground/src/data/mockOverviewRealData.ts
add codeOwnersTable to changes section
will fix styling in next pr
> feat: [pipe-20916]: add codeOwnersTable to changes section

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/pull-request-list-page.tsx
- packages/playground/src/components/no-data.tsx
- packages/playground/src/components/no-search-results.tsx
- packages/playground/src/components/pull-request/interfaces.ts
- packages/playground/src/components/pull-request/pull-request-list.tsx
- packages/playground/src/index.ts
- packages/playground/src/pages/branches-page.tsx
- packages/playground/src/pages/commits-list-page.tsx
- packages/playground/src/pages/execution-list-page.tsx
- packages/playground/src/pages/pipeline-list-page.tsx
- packages/playground/src/pages/pull-request-changes-page.tsx
- packages/playground/src/pages/pull-request-checks-page.tsx
- packages/playground/src/pages/pull-request-commits-page.tsx
- packages/playground/src/pages/pull-request-conversation-page.tsx
- packages/playground/src/pages/pull-request-list-page.tsx
- packages/playground/src/pages/repo-execution-list-page.tsx
- packages/playground/src/pages/repo-list-page.tsx
- packages/playground/src/pages/repo-pipeline-list-page.tsx
add pr list page in gitness app
> feat: [pipe-20916]: add pr list page in gitness app

- packages/playground/src/components/no-data.tsx
Fixing review comment from https://github.com/harness/canary/pull/136
> Fixing review comment from PR #136

- apps/gitness/src/pages/pull-request-list-page.tsx
- packages/playground/src/components/pull-request/pull-request-list.tsx
- packages/playground/src/pages/pull-request-list-page.tsx
update pr list component to use linkcomponent
> feat: [pipe-20916]: fix pr list on gitness app

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/repo-list.tsx
- packages/playground/src/components/repo-list.tsx
- packages/playground/src/index.ts
- packages/playground/src/pages/repo-list-page.tsx
> feat: repo list api integration

- packages/playground/src/components/pull-request/utils.tsx
- packages/playground/src/pages/create-pipeline-page.tsx
> feat: [pipe-21741]: fix lint issue and import

- packages/canary/src/components/icon.tsx
- packages/canary/src/icons/create-workspace.svg
- packages/playground/src/components/layout/top-bar-widget.tsx
- packages/playground/src/pages/create-workspace-page.tsx
- packages/playground/src/pages/landing-page.tsx
- packages/playground/src/settings/branches-settings.tsx
- packages/playground/src/settings/commits-settings.tsx
- packages/playground/src/settings/landing-settings.tsx
- packages/playground/src/settings/list-settings.tsx
- packages/playground/src/settings/menu.tsx
- packages/playground/src/settings/pull-request-changes-settings.tsx
- packages/playground/src/settings/pull-request-checks-settings.tsx
- packages/playground/src/settings/pull-request-commits-settings.tsx
- packages/playground/src/settings/pull-request-conversation-settings.tsx
Background effects not yet present.
> Playground: create workspace screen

- packages/playground/src/components/image-carousel.tsx
- packages/playground/src/components/pull-request/interfaces.ts
- packages/playground/src/components/pull-request/pull-request-comment-box.tsx
- packages/playground/src/components/pull-request/pull-request-description-box.tsx
- packages/playground/src/components/pull-request/pull-request-overview.tsx
- packages/playground/src/components/pull-request/pull-request-timeline-item.tsx
- packages/playground/src/pages/pull-request-conversation-page.tsx
add simple commenting and reply system
**NOTE: will have to implement a similiar commenting and reply system as gitness this is just to progress forward
https://github.com/user-attachments/assets/ba079eda-37c0-4e8f-8bc4-68299f1f31d8
> feat: [pipe-21741]: add simple commenting and reply system

- packages/playground/src/pages/pull-request-changes-page.tsx
- packages/playground/src/settings/pull-request-changes-settings.tsx
Implement the newer `<Button variant="split" />` with dropdown.
> Playground: update PR changes view split button

- apps/gitness/src/pages/pipeline-edit/utils/time-utils.ts
- apps/gitness/src/pages/repo/repo-summary.tsx
- apps/gitness/src/utils/git-utils.ts
- packages/playground/src/components/branch-chooser.tsx
- packages/playground/src/components/repo-summary-panel.tsx
- packages/playground/src/components/repo-summary.tsx
- packages/playground/src/index.ts
- packages/playground/src/pages/commits-list-page.tsx
- packages/playground/src/pages/repo-summary-page.tsx
https://github.com/user-attachments/assets/901f3ac0-8e11-4403-a0f8-ec07a6fcb031
> feat: Integrating all apis on Repo Summary page

- packages/canary/src/components/badge.tsx
- packages/canary/src/components/button.tsx
- packages/playground/src/components/pull-request/pull-request-changes.tsx
- packages/playground/src/components/pull-request/pull-request-list.tsx
- packages/playground/src/components/repo-list.tsx
- packages/playground/src/pages/pull-request-changes-page.tsx
Box headers are currently not complete per PP figma, this PR will add the missing comps:
- Copy button
- Colourized badges for + and - changes
- Viewed checkbox
- Settings button
> Playground: PR changes view box header completion

- packages/canary/src/components/button.tsx
- packages/canary/src/styles.css
- packages/canary/tailwind.config.js
- packages/playground/src/pages/create-pipeline-page.tsx
- Accommodates future custom button border gradients
> Playground: add new variant to Button comp to replicate PP ai-button

- apps/gitness/src/App.tsx
- apps/gitness/src/layouts/PullRequestLayout.tsx
- apps/gitness/src/pages/execution-list.tsx
- apps/gitness/src/pages/pull-request-commits-page.tsx
- apps/gitness/src/pages/repo/repo-commits.tsx
Gitness App : repo commits page
added commits list page at repo level
TODO : branch selection should fetch new commits as per the new branch
> Gitness App : repo commits page

- apps/gitness/package.json
- apps/gitness/src/components/Header.tsx
- apps/gitness/src/framework/context/AppContext.tsx
- apps/gitness/src/layouts/PullRequestLayout.tsx
- apps/gitness/src/pages/create-project.tsx
- apps/gitness/src/pages/execution-list.tsx
- apps/gitness/src/pages/pipeline-edit/utils/time-utils.ts
- apps/gitness/src/pages/pipeline-list.tsx
- apps/gitness/src/pages/pull-request-commits-page.tsx
- apps/gitness/src/pages/pull-request-list-page.tsx
- apps/gitness/src/pages/repo/repo-list.tsx
- apps/gitness/src/pages/repo/repo-summary.tsx
- apps/gitness/src/pages/signin.tsx
- packages/playground/src/components/repo-list.tsx
- packages/playground/src/components/repo-summary-panel.tsx
- packages/playground/src/components/repo-summary.tsx
- packages/playground/src/pages/signin-page.tsx
- pnpm-lock.yaml
This fixes the issue where API response was getting wrapped in `content` key.
from
`return { content: data, ... } as TResponse;`
to
`return { data, ... } as TResponse;`
> fix: Upgrading code repo api client package to fix api response structure

- apps/gitness/package.json
- apps/gitness/src/framework/hooks/useSpaceSSE.tsx
- apps/gitness/src/pages/pull-request/context/pull-request-data-provider.tsx
- apps/gitness/src/pages/pull-request/hooks/useActivityFilters.ts
- apps/gitness/src/pages/pull-request/hooks/useDataFilters.ts
- apps/gitness/src/pages/pull-request/types/types.ts
- apps/gitness/src/pages/pull-request/utils.ts
- packages/playground/package.json
- packages/playground/src/components/pull-request/interfaces.ts
- packages/playground/src/utils/utils.ts
- pnpm-lock.yaml
add pr page provider, utils, hooks and types
> feat: [pipe-21741]: add pr page provider, utils, hooks and types

- packages/canary/src/components/icon.tsx
- packages/canary/src/icons/add-file.svg
- packages/canary/src/icons/add-folder.svg
- packages/playground/src/App.tsx
- packages/playground/src/components/branch-chooser.tsx
- packages/playground/src/index.ts
- packages/playground/src/layouts/RootLayout.tsx
- packages/playground/src/layouts/SandboxLayout.tsx
- packages/playground/src/layouts/SandboxRepo.tsx
- packages/playground/src/layouts/SandboxRoot.tsx
- packages/playground/src/pages/sandbox-repo-code-page.tsx
- packages/playground/src/pages/sandbox-repo-list-page.tsx
- packages/playground/src/pages/sandbox-repo-single-page.tsx
- packages/playground/src/pages/sandbox-repo-summary-page.tsx
- packages/playground/src/settings/sandbox-settings.tsx
> Playground: new screen - build Repositories > Code using new layout approach

- packages/canary/src/icons/file.svg
- packages/canary/src/icons/folder.svg
- packages/playground/src/App.tsx
- packages/playground/src/components/branch-chooser.tsx
- packages/playground/src/components/repo-summary-panel.tsx
- packages/playground/src/components/repo-summary.tsx
- packages/playground/src/layouts/RootLayout.tsx
- packages/playground/src/layouts/SandboxLayout.tsx
- packages/playground/src/layouts/SandboxRoot.tsx
- packages/playground/src/pages/sandbox-landing-page.tsx
- packages/playground/src/pages/sandbox-repo-code-page.tsx
- packages/playground/src/pages/sandbox-repo-list-page.tsx
- packages/playground/src/pages/sandbox-repo-summary-page.tsx
Minor tweaks:
- Remove presentational padding from `<Layout.Content />`
- Handle spacings/padding instead via `<Layout.View />`
- Showcase rendering the `Landing` page using `<Layout />`
> Playground: tweaks to sandbox layout & demo fullscreen view

- apps/gitness/src/pages/repo/repo-commits.tsx
- apps/gitness/src/pages/repo/repo-summary.tsx
- packages/playground/src/components/branch-chooser.tsx
- packages/playground/src/pages/commits-list-page.tsx
- packages/playground/src/pages/repo-summary-page.tsx
- packages/playground/src/pages/sandbox-repo-code-page.tsx
- packages/playground/src/pages/sandbox-repo-summary-page.tsx
added branch selection onClick and fetch summary and commits with updated gitRef
> branch selector onClick updates branch

- apps/gitness/src/pages/pipeline-edit/components/pipeline-studio-graph-view.tsx
- apps/gitness/src/pages/pipeline-edit/components/pipeline-studio-step-form.tsx
- apps/gitness/src/pages/pipeline-edit/components/pipeline-studio.tsx
- apps/gitness/src/pages/pipeline-edit/context/InteractionContextProvider.tsx
- apps/gitness/src/pages/pipeline-edit/context/PipelineStudioDataProvider.tsx
- apps/gitness/src/pages/pipeline-edit/utils/inline-actions.ts
- apps/gitness/src/pages/pipeline-edit/utils/step-form-utils.ts
- apps/gitness/src/pages/pipeline-edit/utils/yaml-utils.ts
- apps/gitness/tailwind.config.js
- packages/playground/src/components/form-inputs/ListInput.tsx
- packages/playground/src/components/pipeline-studio/pipeline-studio-footer-bar/pipeline-studio-footer-bar.tsx
- packages/unified-pipeline/src/components/Canvas/elements/Nodes/AtomicNode/AtomicNode.tsx
- packages/unified-pipeline/src/framework/InteractionContext/InteractionContext.tsx
- packages/unified-pipeline/src/index.ts
- packages/unified-pipeline/src/styles.css
- packages/unified-pipeline/tailwind.config.js
- Style for List input (grid)
- Use doc model to inserting item in the collection/array
- Border for selected step
- Latest pipeline commit info (bottom right corner)
- Small improvements
> Pipeline studio - multiple improvements

- apps/gitness/src/App.tsx
- apps/gitness/src/layouts/RepoLayout.tsx
- apps/gitness/src/pages/repo/repo-webhooks.tsx
- packages/playground/src/components/webhook-list.tsx
- packages/playground/src/data/mockWebhooksData.ts
- packages/playground/src/index.ts
added repo webhooks page to gitness
modified webhooks-list to adjust to the api structure
> repo webhooks page

- packages/playground/src/pages/create-project-page.tsx
- packages/playground/src/settings/landing-settings.tsx
@jessieyu777 - you might have been working on this last Friday, but I spotted the issue and it was quick to fix: the state was expecting 'workspace' not project.
> Playground: fixed create workspace not displaying

- packages/canary/src/components/icon.tsx
- packages/canary/src/components/navbar.tsx
- packages/canary/src/icons/pin.svg
- packages/canary/src/icons/unpin.svg
- packages/playground/src/components/more-submenu.tsx
- packages/playground/src/data/mockNavbarSubmenuData.ts
- packages/playground/src/layouts/RootLayout.tsx
- Add ability to pin/unpin `more` menu items to the main `navbar` pinned group
https://github.com/user-attachments/assets/6b352579-8d22-418e-ad7f-b0b8dd70e2fc
> Playground: hook up more menu pinning functionality

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/repo/repo-branch-list.tsx
- packages/canary/src/components/icon.tsx
- packages/canary/src/icons/no-data-branches.svg
- packages/playground/src/components/branches-list.tsx
- packages/playground/src/components/no-data.tsx
- packages/playground/src/index.ts
- packages/playground/src/pages/branches-list-page.tsx
- packages/playground/src/settings/branches-settings.tsx
- Add NoData status in branchlist
- Add copied status (not included copy function since not sure what we have to copied for)
- Fetch API in branchlist 
- Add initial Avatar for the use without data
-
> Repo branchlist with api

- apps/gitness/package.json
- apps/gitness/src/App.tsx
- apps/gitness/src/layouts/PullRequestLayout.tsx
- apps/gitness/src/pages/pull-request-list-page.tsx
- apps/gitness/src/pages/pull-request/context/pull-request-data-provider.tsx
- apps/gitness/src/pages/pull-request/hooks/usePRChecksDecision.ts
- apps/gitness/src/pages/pull-request/pull-request-conversation-page.tsx
- apps/gitness/src/pages/pull-request/types/types.ts
- apps/gitness/src/pages/pull-request/utils.ts
- apps/gitness/src/types.ts
- packages/playground/package.json
- packages/playground/src/components/pull-request/interfaces.ts
- packages/playground/src/components/pull-request/pull-request-conversation-header.tsx
- packages/playground/src/components/pull-request/pull-request-list.tsx
- packages/playground/src/components/pull-request/pull-request-overview.tsx
- packages/playground/src/components/pull-request/pull-request-panel.tsx
- packages/playground/src/components/pull-request/sections/pull-request-changes-section.tsx
- pnpm-lock.yaml
add api integrations for pr panel and merging
> feat: [pipe-21741]: add api integrations for pr panel and merging

- apps/gitness/src/App.tsx
- apps/gitness/src/layouts/RepoLayout.tsx
- apps/gitness/src/pages/repo/repo-files.tsx
- packages/playground/src/components/more-submenu.tsx
> Adds Repo Files page

- apps/gitness/src/pages/pull-request/context/pull-request-data-provider.tsx
- packages/playground/src/components/pull-request/sections/pull-request-changes-section.tsx
> feat: [pipe-21741]: fix line in panel

- apps/gitness/src/pages/repo/repo-commits.tsx
- packages/playground/src/components/pull-request/pull-request-system-comments.tsx
> feat: [pipe-21741]: fix types

- packages/playground/src/components/pull-request/pull-request-changes.tsx
- packages/playground/src/index.ts
- packages/playground/src/pages/pull-request-changes-page.tsx
> feat: [pipe-22104]: add changes page import

- apps/gitness/src/pages/repo/repo-files.tsx
- packages/canary/src/components/accordion.tsx
- packages/playground/src/components/file-explorer.tsx
- packages/playground/src/components/repo-summary.tsx
- packages/playground/src/pages/sandbox-repo-code-page.tsx
file explorer fetches details dynamically for every folder/subfolder in gitness
> feat: [PIPE-22045]: file explorer gitness

- packages/playground/src/components/branches-list.tsx
- Change the data from PR to SHA, 
- shortSHA in branch list table
UI in Gitness
UI in Playground
> Branchlist show diff in playground gitness

- apps/gitness/src/App.tsx
- apps/gitness/src/RouteDefinitions.ts
- apps/gitness/src/layouts/PullRequestLayout.tsx
https://github.com/user-attachments/assets/3d7dd101-ccfb-4e4c-9a06-17240530bab9
> feat: Pull Request tab pre-selection based on sub-route

- apps/gitness/src/framework/hooks/useLogs.ts
- apps/gitness/src/framework/hooks/useSpaceSSE.tsx
- apps/gitness/src/pages/execution/execution-details.tsx
- apps/gitness/src/pages/pull-request/context/pull-request-data-provider.tsx
- apps/gitness/src/types.ts
- packages/playground/src/components/execution/console-logs.tsx
Integrating Server sent events for Log streaming and Execution progress
> feat: Integrating Server sent events for Log streaming and Execution progress

- packages/playground/src/components/branches-list.tsx
- packages/playground/src/components/commit-copy-actions.tsx
- packages/playground/src/components/pull-request/pull-request-commits.tsx
- packages/playground/src/components/sha-badge.tsx
Migrate a commit-copy-action as a component used in the branchlist page & pull-request page
> Branchlist pullrequest sha clipboard

- apps/gitness/package.json
- apps/gitness/src/App.tsx
- apps/gitness/src/pages/pull-request/context/pull-request-data-provider.tsx
- apps/gitness/src/pages/pull-request/diff-utils.ts
- apps/gitness/src/pages/pull-request/pull-request-changes-page.tsx
- apps/gitness/src/pages/pull-request/pull-request-conversation-page.tsx
- apps/gitness/src/pages/pull-request/types/types.ts
- apps/gitness/src/pages/pull-request/utils.ts
- packages/playground/src/components/pull-request/pull-request-changes.tsx
- packages/playground/src/components/pull-request/utils.tsx
- pnpm-lock.yaml
add diff viewer in changes page - basic
> feat: [pipe-21741]: add diff viewer in changes page - basic

- apps/gitness/src/App.tsx
- apps/gitness/src/RouteDefinitions.ts
- apps/gitness/src/components/FileExplorer.tsx
- apps/gitness/src/components/FileViewer.tsx
- apps/gitness/src/pages/repo/repo-files.tsx
- packages/playground/src/components/file-explorer.tsx
File Explorer Exported out of Repo-Files Page
State maintained for opened folders in a Repo
> feat: [PIPE-22045]: file explorer

- apps/gitness/src/App.tsx
- apps/gitness/src/framework/context/AppContext.tsx
- apps/gitness/src/framework/hooks/useSpaceSSE.tsx
- apps/gitness/src/framework/hooks/useToken.ts
- apps/gitness/src/pages/landing-page.tsx
- apps/gitness/src/pages/logout.tsx
- apps/gitness/src/pages/signin.tsx
- Added `useToken` hook to get, set and delete token in local storage.
- Added `/logout` route to log user out and fix login 🔄 logout loop.
- Code cleanup
https://github.com/user-attachments/assets/77ea4424-c542-4c9c-99a7-d44b9622c57c
> fix: Fix login 🔄 logout loop

- apps/gitness/src/pages/pull-request-list-page.tsx
- apps/gitness/src/pages/pull-request/context/pull-request-data-provider.tsx
- apps/gitness/src/pages/pull-request/types/types.ts
- packages/playground/src/components/pull-request/pull-request-changes.tsx
- packages/playground/src/components/pull-request/pull-request-overview.tsx
- packages/playground/src/components/pull-request/utils.tsx
fix minor issues , increase limit on query for pullreq
avoid drymerge polling on other tabs
show starting line diff if at 0 or 1
> feat: [pipe-21741]: fix minor issues in diff viewer

- apps/gitness/src/components/Header.tsx
- packages/playground/src/components/project-dropdown.tsx
> fix: Fixing label for "Create Project", adding a "tick" next to selected project

- apps/gitness/package.json
- apps/gitness/src/pages/pipeline-edit/components/pipeline-studio-step-form.tsx
- apps/gitness/src/pages/repo/repo-branch-list.tsx
- pnpm-lock.yaml
- Includes token delete and listing api
> chore: Code service React Query api client upgrade

- apps/gitness/src/pages/pull-request/diff-utils.ts
- apps/gitness/src/pages/pull-request/pull-request-changes-filter.tsx
- apps/gitness/src/pages/pull-request/pull-request-changes-page.tsx
- apps/gitness/src/pages/pull-request/types/types.ts
- apps/gitness/src/pages/pull-request/utils.ts
- packages/canary/src/components/button.tsx
- packages/playground/src/components/pull-request/interfaces.ts
Add diff review api on changes tab
- can now approve and request changes on diff tab
- also added a primary button for split button
> feat: [pipe-21741]: add diff review api

- packages/playground/src/components/pull-request/interfaces.ts
- packages/playground/src/components/pull-request/pull-request-system-comments.tsx
> feat: [pipe-20916]: add delete review activity

- apps/gitness/package.json
- apps/gitness/src/pages/pipeline-edit/utils/__tests__/yaml-mocks/pipeline1.ts
- apps/gitness/src/pages/pipeline-edit/utils/__tests__/yaml-mocks/pipeline2.ts
- apps/gitness/src/pages/pipeline-edit/utils/__tests__/yaml-mocks/pipeline3.ts
- apps/gitness/src/pages/pipeline-edit/utils/__tests__/yaml-mocks/pipeline4.ts
- apps/gitness/src/pages/pipeline-edit/utils/__tests__/yaml-mocks/pipeline5.ts
- apps/gitness/src/pages/pipeline-edit/utils/__tests__/yaml-utils.test.ts
- apps/gitness/src/pages/pipeline-edit/utils/yaml-doc-utils.ts
- apps/gitness/src/pages/pipeline-edit/utils/yaml-utils.ts
- apps/gitness/tsconfig.json
- apps/gitness/vitest.config.ts
- pnpm-lock.yaml
- Added yaml doc update utils.
- Added vitest runner
> Yaml document update utils; added vitest

- apps/gitness/src/pages/pipeline-edit/theme/monaco-theme.ts
- packages/yaml-editor/src/components/BlameEditor.tsx
- packages/yaml-editor/src/types/blame.ts
- packages/yaml-editor/src/utils/blame-editor-utils.ts
- initials added
- visual tweaks
> BlameEditor updates

- apps/gitness/src/App.tsx
- apps/gitness/src/components/SandboxFileExplorer.tsx
- apps/gitness/src/components/SandboxFileViewer.tsx
- apps/gitness/src/layouts/RepoSandboxLayout.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-branch-list.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-commits.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-files.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-summary.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-webhooks.tsx
- apps/gitness/src/pages/sandbox-pipeline-list.tsx
- apps/gitness/src/pages/sandbox-pull-request-list-page.tsx
- Integrates all listing pages to the sandboxed layout
- Now, we can start picking up nested routes within these pages to migrate. 
Sandboxed layout in Gitness:
https://github.com/user-attachments/assets/341053c3-c29e-45e2-a89c-94811bfeeb7f
> Integrate Sandbox Layout

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/signup.tsx
- packages/playground/src/index.ts
- packages/playground/src/pages/landing-page.tsx
- packages/playground/src/pages/signin-page.tsx
- packages/playground/src/pages/signup-page.tsx
- Adds signup page with routing and API integration to gitness. 
https://github.com/user-attachments/assets/9aedd604-fc3c-42fe-8ad4-aba5ae9db98f
> Signup page

- apps/gitness/src/pages/pull-request-list-page.tsx
- packages/playground/src/components/pull-request/pull-request-list.tsx
fix icons and labels
- fix merge icon and draft icon and review required/draft text
> feat: [pipe-20761]: fix icons and labels

- apps/gitness/src/pages/landing-page.tsx
Minor type issue introduced in https://github.com/harness/canary/pull/292
> fix: Fix type issue introduced in PR #292

- apps/gitness/src/pages/repo-sandbox/repo-sandbox-header.tsx
- Quick fix for sandbox header
https://github.com/user-attachments/assets/557254eb-4fbf-4ad2-bfc3-f14d5a8dd2f2
> Fix sandbox header

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/profile-settings/profile-settings-keys-page.tsx
- packages/playground/src/App.tsx
- packages/playground/src/index.ts
- packages/playground/src/pages/forgot-password-page.tsx
- packages/playground/src/pages/new-password-page.tsx
- packages/playground/src/pages/otp-page.tsx
- packages/playground/src/pages/signin-page.tsx
- Integrates the UI and routing for auth pages. API support will be integrated once BE has added it.
https://github.com/user-attachments/assets/907ad0fa-84bf-4cbb-ad7a-0f36f25a806b
> Auth pages - UI 

- apps/gitness/src/App.tsx
- apps/gitness/src/components/RootLayoutWrapper.tsx
- apps/gitness/src/components/SandboxRootWrapper.tsx
- apps/gitness/src/pages/profile-settings/profile-settings-general-page.tsx
- packages/canary/src/components/navbar-user.tsx
- packages/canary/src/utils/StringUtils.ts
- packages/playground/src/layouts/RootLayout.tsx
- packages/playground/src/layouts/SandboxRoot.tsx
- packages/playground/src/layouts/types.ts
- Fixes `navbar` user. It now uses and displays the current user from `App Context`. 
- Adds `types` to `layouts`. 
- Removes`extractInitials` function and uses `getInitials` from `utils`
Gitness: (bottom left)
Playground: (bottom left)
> Fix navbar

- apps/gitness/src/pages/pull-request/context/pull-request-data-provider.tsx
- apps/gitness/src/pages/pull-request/pull-request-conversation-page.tsx
- packages/playground/src/components/pull-request/pull-request-conversation-header.tsx
- packages/playground/src/components/pull-request/pull-request-description-box.tsx
- packages/playground/src/components/pull-request/pull-request-panel.tsx
remove moment and fix panel in merge state
> feat: [pipe-20916]: remove moment and fix panel in merge state

- apps/gitness/src/pages/pull-request/pull-request-conversation-page.tsx
- packages/playground/src/components/pull-request/interfaces.ts
- packages/playground/src/components/pull-request/pull-request-panel.tsx
- packages/playground/src/components/pull-request/utils.tsx
- packages/playground/src/pages/pull-request-conversation-page.tsx
> feat: [pipe-20916]: add bypass

- apps/gitness/src/components/FileContentViewer.tsx
- apps/gitness/src/components/FileExplorer.tsx
- apps/gitness/src/components/FileViewer.tsx
- apps/gitness/src/components/GitBlame.tsx
- apps/gitness/src/components/GitCommitDialog.tsx
- apps/gitness/src/components/GitCommitForm.tsx
- apps/gitness/src/framework/hooks/useDownloadRawFile.ts
- apps/gitness/src/pages/repo/repo-files.tsx
- apps/gitness/src/types.ts
- apps/gitness/src/utils/git-utils.ts
- packages/yaml-editor/src/components/BlameEditor.tsx
- packages/yaml-editor/src/types/blame.ts
- packages/yaml-editor/src/utils/blame-editor-utils.ts
1. Adds git blame view
2. Adds Delete / Edit / Copy / View Raw functionality for FileViewer
3. Adds Git Commit Modal and form
> feat: [PIPE-22045]: git blame view in gitness

- packages/canary/src/components/icon.tsx
- packages/canary/src/icons/no-data-members.svg
- packages/playground/src/components/members-list.tsx
- packages/playground/src/components/no-data.tsx
- packages/playground/src/data/mockMembersData.ts
- packages/playground/src/pages/sandbox-settings-project-members-page.tsx
Add the members page in the playground with 4 different status: 
- data-loaded
- no-data
- loading
- no-search-matches
https://github.com/user-attachments/assets/923788de-d280-42c0-bdc3-4688db3b4984
> Project membership page

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/pull-request-list-page.tsx
- apps/gitness/src/pages/sandbox-pull-request-list-page.tsx
- packages/playground/src/App.tsx
- packages/playground/src/components/TabsTriggerItem.tsx
- packages/playground/src/components/branch-chooser.tsx
- packages/playground/src/components/pull-request/pull-request-compare-form.tsx
- packages/playground/src/layouts/RootLayout.tsx
- packages/playground/src/layouts/SandboxPullRequestCompareLayout.tsx
> feat: [pipe-22241]: add compare pr page

- packages/playground/src/components/pull-request/pull-request-compare-button.tsx
- packages/playground/src/components/pull-request/pull-request-compare-form.tsx
- packages/playground/src/layouts/SandboxPullRequestCompareLayout.tsx
refactored code and made it a bit cleaner
> feat: [pipe-22241]: add compare pr page- pt 2  

- packages/playground/src/App.tsx
- packages/playground/src/data/mockBranchList.ts
- packages/playground/src/index.ts
- packages/playground/src/layouts/RootLayout.tsx
- packages/playground/src/layouts/SandboxPullRequestCompareLayout.tsx
- packages/playground/src/layouts/types.ts
- packages/playground/src/pages/sandbox-pull-request-compare-page.tsx
> feat: [pipe-22241]: update compare pr page- pt 3

- apps/gitness/src/pages/execution-list.tsx
- apps/gitness/src/pages/execution/execution-details.tsx
- apps/gitness/src/pages/pipeline-edit/components/pipeline-studio-header-actions.tsx
- apps/gitness/src/pages/pipeline-edit/context/PipelineStudioDataProvider.tsx
- apps/gitness/src/pages/run-pipeline-dialog/run-pipeline-dialog.tsx
- apps/gitness/src/pages/run-pipeline-dialog/utils/utils.ts
- apps/gitness/src/types/pipeline-schema.ts
- packages/canary/src/components/dialog.tsx
- packages/canary/src/components/drawer.tsx
- packages/playground/src/components/form-inputs/Separator.tsx
- packages/playground/src/components/form-inputs/factory/factory.ts
- packages/playground/src/components/form-inputs/types.ts
- run pipeline dialog
- add runtime input in pipeline studio and execution pages
- separator input
- update overlay opacity to 0.5
- use pipeline inputs (from pipeline) to create form
> Run pipeline form

- packages/canary/src/components/navbar-project-chooser.tsx
- packages/canary/src/components/navbar.tsx
- packages/canary/src/components/search-box.tsx
Update navbar to reflect latest figma:
- Search box on new line
- Add product name (this seems to be a different font in the figma)
-
> Playground: update navbar header search position

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/repo-sandbox/repo-settings-general-container.tsx
- packages/playground/src/components/repo-settings/repo-settings-general/repo-settings-general-delete.tsx
- packages/playground/src/components/repo-settings/repo-settings-general/repo-settings-general-form.tsx
- packages/playground/src/components/repo-settings/repo-settings-general/repo-settings-general-security.tsx
- packages/playground/src/components/repo-settings/repo-settings-general/types.ts
- packages/playground/src/index.ts
- packages/playground/src/pages/repo-settings-general-page.tsx
- Adds the `repo-settings-rules-page` to gitness. 
- e2e vid:
https://github.com/user-attachments/assets/99761f23-f9c5-4454-94fa-0d4e69b19c98
> Integrate rules page

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/pull-request-list-page.tsx
- apps/gitness/src/pages/pull-request/pull-request-changes-page.tsx
- apps/gitness/src/pages/pull-request/pull-request-compare-page.tsx
- apps/gitness/src/pages/pull-request/types/types.ts
- apps/gitness/src/pages/sandbox-pull-request-list-page.tsx
- packages/playground/src/components/pull-request/pull-request-diff-viewer.tsx
- packages/playground/src/layouts/SandboxPullRequestCompareLayout.tsx
api integration - compare page
> feat: [pipe-22241]: api integration - compare page

- apps/gitness/src/pages/pipeline-edit/components/pipeline-studio-header-actions.tsx
- apps/gitness/src/pages/pipeline-edit/context/data-store/actions.ts
- apps/gitness/src/pages/pipeline-edit/context/data-store/reducer.ts
- apps/gitness/src/pages/pipeline-edit/context/data-store/types.ts
- apps/gitness/src/pages/run-pipeline-dialog/run-pipeline-dialog.tsx
- apps/gitness/src/pages/run-pipeline-dialog/run-pipeline-form.tsx
- split run pipeline dialog and form
- add isInitialized state - to prevent buttons flickering
> split run pipeline dialog and form

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-branch-rules-container.tsx
- packages/playground/src/App.tsx
- packages/playground/src/components/repo-settings/repo-branch-settings-rules/reducers/repo-branch-settings-reducer.ts
- packages/playground/src/components/repo-settings/repo-branch-settings-rules/repo-branch-settings-rules-data.tsx
- packages/playground/src/components/repo-settings/repo-branch-settings-rules/repo-branch-settings-rules-fields.tsx
- packages/playground/src/components/repo-settings/repo-branch-settings-rules/repo-branch-settings-rules-schema.tsx
- packages/playground/src/components/repo-settings/repo-branch-settings-rules/types.ts
- packages/playground/src/components/repo-settings/repo-settings-general/repo-settings-general-rules.tsx
- packages/playground/src/index.ts
- packages/playground/src/pages/mocks/repo-branch-settings/mockBypassUserData.ts
- packages/playground/src/pages/mocks/repo-branch-settings/mockData.ts
- packages/playground/src/pages/repo-branch-settings-rules-page.tsx
- Integrates the `repo-branch-settings-page` into gitness. 
e2e video:
https://github.com/user-attachments/assets/8c10d2b0-210d-42e3-8e97-8d2a26a68eeb
> Integrating branch rules

- packages/canary/src/components/navbar-user.tsx
- packages/playground/src/App.tsx
- packages/playground/src/layouts/RootLayout.tsx
- packages/playground/src/layouts/SandboxRoot.tsx
- packages/playground/src/layouts/types.ts
- packages/playground/src/pages/mocks/mockCurrentUserData.ts
Changes to navbar footer:
- Added dropdown menu (link to destinations are fake)
- Restored avatar stlying to match figmas
- Fixed padding
- Added absolute highlight on hover
> Playground: add dropdown menu to navbar footer

- packages/playground/src/components/branches-list.tsx
- packages/playground/src/components/pull-request/pull-request-compare-button.tsx
- packages/playground/src/components/pull-request/pull-request-side-bar.tsx
- packages/playground/src/layouts/SandboxPullRequestCompareLayout.tsx
- packages/playground/src/pages/branches-list-page.tsx
- packages/playground/src/pages/sandbox-pull-request-compare-page.tsx
add compare btn on branch list to create new pr based on branch selected
> feat: [pipe-22241]: add compare btn on branch list

- apps/gitness/src/hooks/useThunkReducer.tsx
- apps/gitness/src/pages/execution/execution-details.tsx
- apps/gitness/src/pages/pipeline-edit/components/pipeline-studio-header-actions.tsx
- apps/gitness/src/pages/pipeline-edit/components/pipeline-studio-panel.tsx
- apps/gitness/src/pages/pipeline-edit/components/pipeline-studio-step-palette.tsx
- apps/gitness/src/pages/pipeline-edit/components/pipeline-studio.tsx
- apps/gitness/src/pages/pipeline-edit/context/PipelineStudioDataProvider.tsx
- apps/gitness/src/pages/pipeline-edit/context/data-store/actions.ts
- apps/gitness/src/pages/pipeline-edit/context/data-store/reducer.ts
- apps/gitness/src/pages/pipeline-edit/context/data-store/types.ts
- packages/canary/src/components/input.tsx
- packages/playground/src/components/pipeline-studio/pipeline-studio-footer-bar/pipeline-studio-footer-bar.tsx
- packages/playground/src/components/pipeline-studio/popover-commit-info.tsx
- packages/playground/src/index.ts
- packages/playground/src/pages/pipeline-edit-page.tsx
- Latest commit info
- Branch selection
- Small improvements
> feat: [PIPE-22777]: Status bar updates

- apps/gitness/src/App.tsx
- apps/gitness/src/RouteDefinitions.ts
- apps/gitness/src/pages/pull-request-list-page.tsx
- apps/gitness/src/pages/pull-request/pull-request-compare-page.tsx
- apps/gitness/src/pages/pull-request/pull-request-conversation-page.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-branch-list.tsx
- apps/gitness/src/pages/repo/repo-branch-list.tsx
- packages/playground/src/components/branches-list.tsx
- packages/playground/src/components/pull-request/pull-request-compare-button.tsx
- packages/playground/src/components/pull-request/pull-request-compare-form.tsx
- packages/playground/src/layouts/SandboxPullRequestCompareLayout.tsx
add gitness integration for the button
- handle routing with or without diffRefs
- add messaging if head commit is the same
change formfield name
https://github.com/user-attachments/assets/a9635289-eac6-464e-af06-3edaf7cbe477
> feat: [pipe-22241]: add compare btn on branch list- on gitness

- packages/playground/src/components/project-settings/form-member-delete-dialog.tsx
- packages/playground/src/components/project-settings/form-member-edit-dialog.tsx
- packages/playground/src/components/project-settings/interfaces.ts
- packages/playground/src/components/project-settings/members-list.tsx
- packages/playground/src/components/project-settings/members-reducers/dialog-state-reducers.ts
- packages/playground/src/components/user-management/form-admin-remove-dialog.tsx
- packages/playground/src/components/user-management/form-user-delete-dialog.tsx
- packages/playground/src/components/user-management/form-user-edit-dialog.tsx
- packages/playground/src/components/user-management/form-user-reset-password.tsx
- packages/playground/src/components/user-management/interfaces.ts
- packages/playground/src/components/user-management/user-reducers/dialog-state-reducers.ts
- packages/playground/src/components/user-management/users-list.tsx
- packages/playground/src/pages/sandbox-settings-project-members-page.tsx
- packages/playground/src/pages/sandbox-settings-user-management-page.tsx
- Migrated` interfaces `and `props` from each page and components to `interfaces` file including user-management & project member
- Used string-based `enums` instead of using original `string` type
- Fixed the warnings on the browser:` aria-hidden` from `DropdownMenu `component
- Used `lodash-es` for changing first letters to uppercase
> Fixed: member-list-page & user-management page - playground 

- packages/playground/src/components/pull-request/hooks/useEmitCodeCommentStatus.ts
- packages/playground/src/components/pull-request/interfaces.ts
- packages/playground/src/components/pull-request/pull-request-panel.tsx
- packages/playground/src/components/pull-request/pull-request-system-comments.tsx
- packages/playground/src/components/pull-request/pull-request-system-label-item.tsx
- packages/playground/src/components/pull-request/pull-request-system-merge.tsx
- packages/playground/src/components/pull-request/pull-request-system-reviewer-add.tsx
- packages/playground/src/components/pull-request/pull-request-system-reviewer-delete.tsx
- packages/playground/src/components/pull-request/pull-request-system-title.tsx
add new activities and fix some of them
also refactor the pull request system comments file
> feat: [pipe-20916]: add new activities and fix some of them

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/empty-page.tsx
- packages/playground/src/components/no-data.tsx
- Adds empty pages for all routes
- adds an `onClick` prop to `no-data` component buttons (non-breaking). 
https://github.com/user-attachments/assets/2593e9e1-b8dd-4786-80eb-398b0ebdf7af
> Adds empty pages for all routes

- apps/gitness/src/layouts/PullRequestLayout.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-branch-rules-container.tsx
- PR page tab nav using `isActive` from `Navlink`. 
https://github.com/user-attachments/assets/177c96dc-bebf-4a16-be67-98d7ca4e8ec7
> Pull Request's page tab-nav

- apps/gitness/src/App.tsx
- apps/gitness/src/layouts/PullRequestSandboxLayout.tsx
- apps/gitness/src/pages/execution/sanbox-execution-details.tsx
- apps/gitness/src/pages/pipeline-create/pipeline-create-sandbox.tsx
- apps/gitness/src/pages/pull-request/sandbox-pull-request-conversation-page.tsx
- apps/gitness/src/pages/sandbox-execution-list.tsx
- packages/playground/src/index.ts
- packages/playground/src/pages/sandbox-create-pipeline-page.tsx
- Migrates most pages to sandbox except `pipeline-edit flow` and `execution-details`.
> Migrate pages to Sandbox

- apps/gitness/src/components/FileEditor.tsx
- apps/gitness/src/components/GitCommitDialog.tsx
- apps/gitness/src/components/GitCommitForm.tsx
- apps/gitness/src/pages/pull-request-list-page.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-summary.tsx
- apps/gitness/src/pages/repo/repo-summary.tsx
- apps/gitness/src/pages/sandbox-pull-request-list-page.tsx
add navigation to compare on empty pr list page AND  navigation to new file on add file click
> feat: [pipe-22241]: add navigation on compare

- packages/playground/src/App.tsx
- packages/playground/src/components/webhooks/create-webhook-form-data.ts
- packages/playground/src/components/webhooks/create-webhooks-form-fields.tsx
- packages/playground/src/components/webhooks/create-webhooks-form-schema.tsx
- packages/playground/src/components/webhooks/types.ts
- packages/playground/src/pages/repo-webhooks-create-page.tsx
- packages/playground/src/pages/repo-webhooks-page.tsx
- packages/playground/src/pages/sandbox-repo-settings-page.tsx
- Adds the `create-webhooks` page to playground. 
https://github.com/user-attachments/assets/dee8ce3f-3806-48ce-b81a-ad74072b7d98
> Webhooks create page

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-webhooks.tsx
- apps/gitness/src/pages/repo/repo-webhooks.tsx
- apps/gitness/src/pages/webhooks/create-webhook-container.tsx
- packages/playground/src/components/webhooks/create-webhook-form-data.ts
- packages/playground/src/components/webhooks/create-webhooks-form-fields.tsx
- packages/playground/src/components/webhooks/create-webhooks-form-schema.tsx
- packages/playground/src/components/webhooks/types.ts
- packages/playground/src/index.ts
- packages/playground/src/pages/repo-webhooks-create-page.tsx
- Integrates the `create-webhook` flow with APIs and routing to `Gitness`. 
- Edit/Delete `webhook` will be taken up later. 
- Demoed in standup on 11/1.
> Integrate create webhooks flow to gitness

- apps/gitness/src/pages/pull-request/context/pull-request-data-provider.tsx
- apps/gitness/src/pages/pull-request/pull-request-conversation-page.tsx
- packages/canary/src/components/node-group.tsx
- packages/playground/src/components/pull-request/pull-request-overview.tsx
- packages/playground/src/components/pull-request/pull-request-panel.tsx
- packages/playground/src/components/pull-request/pull-request-status-select-button.tsx
- packages/playground/src/components/pull-request/pull-request-timeline-item.tsx
- packages/playground/src/pages/pull-request-conversation-page.tsx
NOTE: im passing a usemutation call rn but will be refactored when i refactor provider code and components related to pr pages
add active/resolved state
> feat: [pipe-20916]: add active/resolved state

- packages/playground/src/App.tsx
- packages/playground/src/layouts/SandboxPullrequestLayout.tsx
- packages/playground/src/pages/sandbox-branches-list-page.tsx
- packages/playground/src/pages/sandbox-commits-list-page.tsx
- packages/playground/src/pages/sandbox-pull-request-conversation-page.tsx
- packages/playground/src/pages/sandbox-pull-request-list-page.tsx
- packages/playground/src/pages/sandbox-repo-execution-list-page.tsx
- packages/playground/src/pages/sandbox-repo-pipeline-list-page.tsx
- packages/playground/src/pages/sandbox-repo-single-page.tsx
- packages/playground/src/pages/sandbox-repo-webhooks-list-page.tsx
- Migrates playground to sandbox routes.
> Migrate playground to sandbox

- apps/gitness/src/pages/pull-request/pull-request-conversation-page.tsx
- packages/playground/src/components/pull-request/pull-request-overview.tsx
- packages/playground/src/components/pull-request/pull-request-side-bar.tsx
fix pr filters on overview activity
> feat: [pipe-20916]: fix pr filters

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-webhooks.tsx
- apps/gitness/src/pages/webhooks/create-webhook-container.tsx
- packages/playground/src/components/webhook-list.tsx
- packages/playground/src/components/webhooks/create-webhook-form-data.ts
- packages/playground/src/components/webhooks/create-webhooks-form-fields.tsx
- packages/playground/src/components/webhooks/create-webhooks-form-schema.tsx
- packages/playground/src/components/webhooks/types.ts
- packages/playground/src/pages/repo-webhooks-create-page.tsx
- Adds edit/delete webhook flow. Changes create-webhook schema to match closer to API. 
- Integrates dialog for delete on page. 
https://github.com/user-attachments/assets/7fe6b4f6-6e2f-45d2-a5b6-a5ece9d6fc7c
> Webhooks edit delete flow

- apps/gitness/src/components/FileViewer.tsx
- apps/gitness/src/pages/execution/execution-details.tsx
- apps/gitness/src/pages/pipeline-edit/utils/time-utils.ts
- apps/gitness/src/pages/repo/repo-files.tsx
- apps/gitness/src/styles.css
- packages/playground/src/components/branch-chooser.tsx
- packages/playground/src/components/file-explorer.tsx
- packages/playground/src/components/repo-summary.tsx
- packages/yaml-editor/src/components/CodeEditor.tsx
- packages/yaml-editor/src/components/DiffEditor.tsx
adds search implementation to file explorer
adds padding top to codeEditor and diffEditor
> feat: [PIPE-22045]: search files in repo/code explorer

- apps/gitness/src/framework/hooks/useLogs.ts
- apps/gitness/src/pages/execution-list.tsx
- apps/gitness/src/pages/execution/execution-details.tsx
- apps/gitness/src/pages/execution/sanbox-execution-details.tsx
- apps/gitness/src/pages/pipeline-list.tsx
- apps/gitness/src/pages/pull-request/context/pull-request-data-provider.tsx
- apps/gitness/src/pages/pull-request/hooks/usePRChecksDecision.ts
- apps/gitness/src/pages/pull-request/utils.ts
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-branch-list.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-commits.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-list.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-webhooks.tsx
- apps/gitness/src/pages/sandbox-execution-list.tsx
- apps/gitness/src/pages/sandbox-pipeline-list.tsx
- apps/gitness/src/pages/sandbox-pull-request-list-page.tsx
- apps/gitness/src/types.ts
- apps/gitness/src/utils/execution-utils.tsx
- packages/playground/src/components/execution/types.ts
- packages/playground/src/index.ts
-  Syncs up changes from non-sandbox listing pages to Sandbox listing pages under Repository.
- Code cleanup to remove redundant enums.
> fix: Add pagination related changes to Sandbox listing pages - part 1

- apps/gitness/src/App.tsx
- apps/gitness/src/components/SandboxRootWrapper.tsx
- apps/gitness/src/pages/empty-page.tsx
- apps/gitness/src/pages/landing-page.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-header.tsx
- packages/playground/src/App.tsx
- packages/playground/src/layouts/SandboxRoot.tsx
- Fixes side nav links and routes for Project level listing pages.
- Fixes text in placeholder pages for other modules in side nav.
- Cleans up Playground sandbox wrapper that rendered sandbox routes separately.
- Adds `Project Settings` side nav link.
> fix: Miscellaneous fixes around side nav links, fixing url structure

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/create-project.tsx
- apps/gitness/src/pages/logout.tsx
- apps/gitness/src/pages/pipeline-create/PipelineCreateDialog/PipelineCreateDialog.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-branch-list.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-commits.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-webhooks.tsx
- apps/gitness/src/pages/sandbox-execution-list.tsx
- apps/gitness/src/pages/sandbox-pipeline-list.tsx
- packages/playground/src/components/no-data.tsx
- packages/playground/src/pages/repo-webhooks-create-page.tsx
- packages/playground/src/pages/sandbox-repo-create-page.tsx
- packages/playground/src/pages/sandbox-repo-settings-page.tsx
- Fix executions list no data state
- fix repo scope list page top spacing
- fix logout flow
- fix create repo form and errors
- fix pipeline creation and project creation flow
> fix: executions no data state and list spacing

- apps/gitness/src/App.tsx
- apps/gitness/src/components/FileContentViewer.tsx
- apps/gitness/src/components/FileEditor.tsx
- apps/gitness/src/components/FileExplorer.tsx
- apps/gitness/src/components/FileViewer.tsx
- apps/gitness/src/components/SandboxFileViewer.tsx
- apps/gitness/src/pages/execution/execution-details.tsx
- apps/gitness/src/pages/execution/sanbox-execution-details.tsx
- apps/gitness/src/pages/pipeline-edit/utils/common-utils.ts
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-files.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-summary.tsx
- apps/gitness/src/pages/repo/repo-files.tsx
- apps/gitness/src/pages/repo/repo-summary.tsx
- apps/gitness/src/utils/common-utils.ts
- packages/canary/src/components/treeview.tsx
- packages/playground/src/components/execution/execution-details.tsx
- packages/playground/src/components/execution/stage-execution.tsx
- packages/playground/src/components/execution/step-execution.tsx
fixes sandbox repo code page and execution details - copy / download / step nav
> fix: sandbox repo code page and execution details - copy / download / step nav

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/project-settings/project-settings-members-page.tsx
- packages/playground/src/App.tsx
- packages/playground/src/pages/sandbox-settings-create-new-member-page.tsx
- Fixes the route for `create` new user, consistent with other create entity pages.
- Pluralizes `members` noun properly.
- Fixes minor type issues
> fix: Minor fixes on Project members page

- packages/playground/src/components/branches-list.tsx
- packages/playground/src/components/pull-request/pull-request-comment-box.tsx
- packages/playground/src/components/pull-request/pull-request-description-box.tsx
- packages/playground/src/components/pull-request/pull-request-overview.tsx
- packages/playground/src/components/pull-request/pull-request-system-comments.tsx
- packages/playground/src/components/pull-request/pull-request-system-label-item.tsx
- packages/playground/src/components/pull-request/pull-request-system-merge.tsx
- packages/playground/src/components/pull-request/pull-request-system-reviewer-add.tsx
- packages/playground/src/components/pull-request/pull-request-system-reviewer-delete.tsx
- packages/playground/src/components/pull-request/pull-request-system-title.tsx
use initials for avatar for now  on pr pages
> feat: [pipe-20916]: use initials for avatar

- packages/playground/src/components/pull-request/pull-request-changes.tsx
fix copy btn and add coming soon hovers on changes tab
> feat: [pipe-21741]: fix copy btn and add coming soon hovers

- apps/gitness/src/App.tsx
- apps/gitness/src/user-management/user-management-container.tsx
- packages/canary/src/components/icon.tsx
- packages/canary/src/icons/account.svg
- packages/playground/src/App.tsx
- packages/playground/src/components/user-management/form-admin-add-dialog.tsx
- packages/playground/src/components/user-management/form-admin-remove-dialog.tsx
- packages/playground/src/components/user-management/form-user-delete-dialog.tsx
- packages/playground/src/components/user-management/form-user-edit-dialog.tsx
- packages/playground/src/components/user-management/form-user-reset-password.tsx
- packages/playground/src/components/user-management/interfaces.ts
- packages/playground/src/components/user-management/user-reducers/dialog-state-reducers.ts
- packages/playground/src/components/user-management/users-list.tsx
- packages/playground/src/index.ts
- packages/playground/src/layouts/SandboxRoot.tsx
- packages/playground/src/pages/sandbox-settings-user-management-page.tsx
- packages/playground/src/utils/utils.ts
- Integrates all APIs for user management page. 
- `Create user` will be implemented in a followup PR. 
e2e vid:
https://github.com/user-attachments/assets/9626c9c3-797f-4ffe-8929-c13f73c863f3
> Integrates API's for user management

- apps/gitness/src/pages/execution/sanbox-execution-details.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-files.tsx
- apps/gitness/src/styles.css
- packages/canary/src/components/search-box.tsx
- packages/playground/src/components/execution/console-logs.tsx
- packages/playground/src/components/execution/step-execution.tsx
- packages/playground/src/styles.css
fix search in file-explorer and adds search to executions logs
> fix search in file-explorer and adds search to executions logs

- apps/gitness/src/pages/pull-request/pull-request-compare-page.tsx
fix route from compare to pr detail page
> feat: [pipe-20916]: fix navigate route

- apps/gitness/src/pages/pipeline-edit/pipeline-edit.tsx
> fix: add sandbox layout to studio page

- packages/playground/src/components/pull-request/pull-request-compare-form.tsx
> fix: [pipe-23088]: fix text in pr creation

- packages/playground/src/components/pull-request/pull-request-compare-form.tsx
- packages/playground/src/layouts/SandboxPullRequestCompareLayout.tsx
make description optional in pr compare page
> fix: [pipe-23117]: make description optional

- apps/gitness/src/framework/queryClient.ts
- apps/gitness/src/pages/profile-settings/profile-settings-general-page.tsx
- apps/gitness/src/pages/repo-sandbox/repo-sandbox-list.tsx
- apps/gitness/src/pages/repo/repo-create-page.tsx
- user profile should not trigger logout
- cancelling repo creation should not crash
- handle api errors on repo list page
- disable automatic retries for GET calls
> fix: settings page should not trigger logout

- apps/gitness/src/pages/pull-request/types/types.ts
- packages/playground/src/components/pull-request/pull-request-compare-button.tsx
- packages/playground/src/layouts/SandboxPullRequestCompareLayout.tsx
- packages/playground/src/pages/sandbox-pull-request-conversation-page.tsx
dont have disable on create pr and pick pr title from commits
> fix: [pipe-23087]: dont have disable on create pr

- apps/gitness/src/pages/pull-request/sandbox-pull-request-conversation-page.tsx
- packages/playground/src/components/pull-request/pull-request-comment-box.tsx
> fix: [pipe-23109]: fix initials in comment box

- packages/playground/src/layouts/SandboxPullRequestCompareLayout.tsx
> fix: [pipe-23115]: fix wide gap on compare page

- packages/playground/src/components/repo-clone/clone-repo-dialog.tsx
- packages/playground/src/components/repo-clone/clone-repo-form.tsx
- packages/playground/src/pages/sandbox-repo-summary-page.tsx
e2e vid:
https://github.com/user-attachments/assets/7d0a6ebf-aae3-4b2a-9d64-2ee9a42e13c2
> Integrate clone repo dialog to playground

- apps/gitness/src/pages/repo-sandbox/repo-sandbox-summary.tsx
- packages/playground/src/components/repo-clone/clone-repo-dialog.tsx
- packages/playground/src/components/repo-clone/clone-repo-form.tsx
- packages/playground/src/index.ts
- packages/playground/src/pages/sandbox-repo-summary-page.tsx
- Adds clone repo to `gitness`. 
- Adds create token flow to clone in repo-summary page. 
https://github.com/user-attachments/assets/92993506-66e0-483c-ae09-4ba364c15c18
> Integrate clone repo flow into gitness

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/pipeline/project-pipeline-list.tsx
- apps/gitness/src/pages/project-settings/project-settings-members-page.tsx
- apps/gitness/src/pages/project-settings/project-settings-new-member-page.tsx
- packages/playground/src/index.ts
- added new member page 
- added new dropdown component for listing available users
https://github.com/user-attachments/assets/15e79481-dccc-448d-9b46-3d2c4dea80ed
- the status of no available users
- test api for duplicate users
> New Member Page with Dropdown & Api Call

- packages/views/src/components/pull-request/pull-request-timeline-item.tsx
> fix: [pipe-23098]: Can do empty comment on reply

- apps/gitness/src/pages/pipeline-create/PipelineCreateDialog/PipelineCreateForm.tsx
https://github.com/user-attachments/assets/22f2014e-3153-4ddc-945f-cd38ee194d07
> fix: [PIPE-23284]: Set repo default branch as selected by default in create pipeline form

- apps/gitness/src/layouts/PullRequestLayout.tsx
- packages/views/src/components/pull-request/pull-request-conversation-header.tsx
> fix: [pipe-23106]: fix branch link not clickable

- apps/gitness/src/pages/pull-request/pull-request-list-page.tsx
- packages/views/src/components/pull-request/pull-request-list.tsx
- Adds api call to repo-details in PR list page to fix this.
> PIPE-23144: Pull Request API doesn't return total PRs info

- apps/gitness/src/components/FileContentViewer.tsx
- apps/gitness/src/components/FileExplorer.tsx
- apps/gitness/src/components/GitCommitForm.tsx
- apps/gitness/src/pages/pipeline-edit/context/InteractionContextProvider.tsx
- apps/gitness/src/pages/pipeline-edit/context/PipelineStudioDataProvider.tsx
- apps/gitness/src/pages/pipeline/repo-pipeline-list.tsx
- apps/gitness/src/pages/project-settings/project-settings-general-page.tsx
- apps/gitness/src/pages/project-settings/project-settings-new-member-page.tsx
- apps/gitness/src/pages/repo/repo-list.tsx
- apps/gitness/src/pages/repo/repo-settings-general-container.tsx
- apps/gitness/src/utils/repo-branch-rules-utils.ts
- packages/canary/src/components/meter.tsx
- packages/playground/src/components/pipeline-list.tsx
- packages/views/src/components/branch-chooser.tsx
- packages/views/src/components/execution-list.tsx
- packages/views/src/components/execution/execution-tree-utils.tsx
- packages/views/src/components/execution/types.ts
- packages/views/src/components/file-explorer.tsx
- packages/views/src/components/pipeline-list.tsx
- packages/views/src/components/repo-list.tsx
- packages/views/src/components/repo-settings/repo-branch-settings-rules/types.ts
- packages/views/src/components/webhook-list.tsx
> Fix gitness type issues

- apps/gitness/src/pages/pull-request/context/pull-request-data-provider.tsx
- apps/gitness/src/pages/pull-request/pull-request-conversation-page.tsx
- packages/playground/src/components/pull-request/interfaces.ts
- packages/playground/src/components/pull-request/pull-request-panel.tsx
- packages/playground/src/components/pull-request/sections/pull-request-check-section.tsx
- packages/playground/src/components/pull-request/sections/pull-request-merge-section.tsx
- packages/views/src/components/pull-request/interfaces.ts
- packages/views/src/components/pull-request/pull-request-panel.tsx
- packages/views/src/components/pull-request/sections/pull-request-check-section.tsx
> chore: fix pr type issues

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/repo/repo-import-container.tsx
- apps/gitness/src/pages/repo/repo-list.tsx
- apps/gitness/src/pages/repo/repo-settings-general-container.tsx
- packages/views/src/components/repo-import-form-component.tsx
- packages/views/src/index.ts
- Adds `import-repo` form with API to `gitness`.
- Fixes minor issue in default branch update. 
- Issue of repo not opening (event stream possible fix) will be taken up as a separate PR. 
https://github.com/user-attachments/assets/f0552e99-aa65-4060-97ff-d444e66bb009
> feat: adding import repo api to gitness

- apps/gitness/src/pages/profile-settings/profile-settings-general-page.tsx
- packages/canary/src/styles.css
- packages/views/src/components/theme-provider.tsx
- packages/views/src/index.ts
This PR contains the initial theming changes to begin testing and playing around with theming.
- Added a Theme Toggle in Account Settings page
- Changed tailwind variables for light theme
- Modified theme-provider to automatically set theme to the selected system theme if the user has selected "System" as their theme preference
https://github.com/user-attachments/assets/cb408d15-2ddc-47fd-97b7-fc92606452c9
> Initial Theming Changes

- apps/gitness/src/pages/run-pipeline-dialog/run-pipeline-form.tsx
When a pipeline was created but not saved, and then if it was tried to run, the UI showed indefinite "Loading" state instead of showing the error message.
This issue is now fixed as part of this PR.
https://github.com/user-attachments/assets/f7479d79-add1-40cf-8cc6-365ed427647d
> PIPE-22234 Show error message instead of loading when relevant

- apps/gitness/src/components/FileEditor.tsx
- apps/gitness/src/components/GitCommitDialog.tsx
- apps/gitness/src/components/GitCommitForm.tsx
- apps/gitness/src/pages/pull-request/pull-request-compare-page.tsx
- apps/gitness/src/pages/repo/repo-summary.tsx
- packages/playground/tailwind.config.js
- packages/views/src/components/pull-request/pull-request-timeline-item.tsx
- packages/views/src/components/repo-summary-panel.tsx
- packages/views/src/layouts/SandboxPullRequestCompareLayout.tsx
- packages/views/tailwind.config.js
fixes new file input box - on edit view and commit modal
also fixes the PR comments issues
> fix newFile commit bug and PR comments bug

- apps/gitness/src/layouts/PullRequestLayout.tsx
fix infinite scroll issue on pr conversation page
> feat: [pipe-20916]: fix scroll

- apps/gitness/package.json
- apps/gitness/src/pages/pull-request/context/pull-request-data-provider.tsx
- apps/gitness/src/pages/pull-request/pull-request-changes-page.tsx
- apps/gitness/src/pages/pull-request/pull-request-conversation-page.tsx
- apps/gitness/src/pages/pull-request/stores/pull-request-store.tsx
- apps/gitness/src/pages/pull-request/types/types.ts
- packages/views/src/components/pull-request/interfaces-store.ts
- packages/views/src/components/pull-request/interfaces.ts
- packages/views/src/components/pull-request/pull-request-reviewers-header.tsx
- packages/views/src/components/pull-request/pull-request-reviewers-item.tsx
- packages/views/src/components/pull-request/pull-request-reviewers-list.tsx
- packages/views/src/components/pull-request/pull-request-side-bar.tsx
- packages/views/src/index.ts
- pnpm-lock.yaml
zustand poc for pr provider converted the data provider to use zustand store for all the variables
> feat: [pipe-20916]: zustand poc for pr provider

- package.json
- packages/forms/package.json
- packages/unified-pipeline/package.json
- packages/yaml-editor-playground/package.json
- packages/yaml-editor/package.json
- pnpm-lock.yaml
References:
Problem faced: https://github.com/lint-staged/lint-staged/issues/929#issuecomment-1789598499
https://github.com/lint-staged/lint-staged/issues/929#issuecomment-1195595223
https://github.com/lint-staged/lint-staged/issues/929#issuecomment-1211287774
Additional changes:
Added lint staged to all the packages where it is missing currently.
> Add lint staged to all packages and make its concurrency as 1

- apps/gitness/src/pages/pull-request/context/pull-request-data-provider.tsx
- apps/gitness/src/pages/pull-request/stores/pull-request-store.tsx
- packages/canary/src/components/text.tsx
- packages/views/src/components/pull-request/interfaces-store.ts
- packages/views/src/components/pull-request/interfaces.ts
- packages/views/src/components/pull-request/pull-request-reviewers-header.tsx
- packages/views/src/components/pull-request/pull-request-reviewers-item.tsx
- packages/views/src/components/pull-request/pull-request-reviewers-list.tsx
- packages/views/src/components/pull-request/pull-request-reviewers-tooltip.tsx
- packages/views/src/components/pull-request/pull-request-side-bar.tsx
Followup pr to comments from this pr:
https://github.com/harness/canary/pull/459
> feat: [pipe-20916]: follow up pr to zustand poc

- packages/yaml-editor/src/components/BlameEditor.tsx
- packages/yaml-editor/src/utils/blame-editor-utils.ts
Fixes:
- unable to select code across lines, it instead selects blame info
- blame is leaking on next line
> fix: [PIPE-23096]: [PIPE-23094]: BlameEditor fixes

- apps/gitness/package.json
- apps/gitness/src/pages/pipeline-edit/components/pipeline-studio-step-form.tsx
- apps/gitness/src/pages/pipeline-edit/components/pipeline-studio-step-palette.tsx
- apps/gitness/src/pages/pipeline-edit/components/pipeline-studio.tsx
- apps/gitness/src/pages/pipeline-edit/context/PipelineStudioDataProvider.tsx
- apps/gitness/src/pages/pipeline-edit/context/data-store/reducer.ts
- apps/gitness/src/pages/pipeline-edit/context/data-store/types.ts
- apps/gitness/src/pages/pipeline-edit/types/api-types.ts
- apps/gitness/src/pages/pipeline-edit/utils/api.ts
- apps/gitness/src/pages/pipeline-edit/utils/step-form-utils.ts
- packages/playground/src/components/pipeline-studio/step-form/step-form-section.tsx
- packages/playground/src/components/steps/group.tsx
- packages/playground/src/components/steps/harness-steps.ts
- packages/playground/src/components/steps/parallel.tsx
- packages/playground/src/components/steps/types.ts
- packages/views/src/components/form-inputs/ArrayInput.tsx
- packages/views/src/components/form-inputs/ListInput.tsx
- packages/views/src/components/form-inputs/common/InputLabel.tsx
- packages/views/src/components/pipeline-studio/step-form/step-form-section.tsx
- packages/views/src/components/steps/group.ts
- packages/views/src/components/steps/harness-steps.ts
- packages/views/src/components/steps/parallel.ts
- packages/views/src/components/steps/types.ts
- pnpm-lock.yaml
- Templates API integration
- Removed not used elements - like filters
- Added group edit (only group name)
- Align with style changes
> Step form improvements

- apps/gitness/src/pages/pull-request/pull-request-compare-page.tsx
- packages/views/src/layouts/SandboxPullRequestCompareLayout.tsx
- Enhancement to show if a PR already exists on the UI. 
- Button to the right will be fixed by @cjlee01 in a follow up PR. 
https://github.com/user-attachments/assets/c560c766-3787-4bf5-a028-c9f4c9e126c5
> feat: add src-target branch pr exists

- .github/workflows/build-and-deploy-storybook.yml
fix issue on forked repos where github actions don't run and the checks dont work
> chore: fix issue on forked repos

- apps/gitness/src/pages-v2/repo/repo-list.tsx
- packages/ui/package.json
- packages/ui/src/hooks/index.ts
- packages/ui/src/hooks/useCommonFilter.tsx
- packages/ui/src/index.ts
- packages/ui/src/views/repo-list/repo-list-page.tsx
- packages/ui/src/views/repo-list/repo-list.tsx
- packages/ui/tsconfig.json
- packages/ui/vite.config.ts
- Adds search functionality to `repo-list` page along with states for `no-search-results`.
- current implementation will be cleaned up when we get a component similar to `<Filter>` in the `UI` package. 
https://github.com/user-attachments/assets/949dbbe5-5d86-49da-90ef-2652aacc2455
> Add repo list features

- apps/gitness/src/App.tsx
- apps/gitness/src/pages/repo/repo-list.tsx
> move old routes to v1

- apps/gitness/src/App.tsx
- packages/ui/src/data/navbar-menu-data.ts
- packages/ui/src/views/empty-page.tsx
- packages/ui/src/views/index.ts
- Fixes all the routes under "More" section to render the placeholder "Empty" page.
- Moves `<EmptyPage />` component to `ui` package.
> chore: Fix routes under "More" section

- apps/gitness/src/App.tsx
Cause: https://github.com/harness/canary/pull/487/files#diff-7ec306351b8023b810b7acda25e815047c237f3cac0e612a2d2ad6358c8b4d70L27
> Fix theme provider import

- packages/ui/package.json
- packages/ui/src/components/branch-chooser.tsx
- packages/ui/src/components/form-field-set.tsx
- packages/ui/src/components/radio-group.tsx
- packages/ui/src/views/index.ts
- packages/ui/src/views/layouts/PullRequestCompareLayout.tsx
- packages/ui/src/views/layouts/layout.tsx
- packages/ui/src/views/pull-request/compare/components/pull-request-compare-button.tsx
- packages/ui/src/views/pull-request/compare/components/pull-request-compare-form.tsx
- packages/ui/src/views/pull-request/compare/components/pull-request-compare-tab-trigger-item.tsx
- packages/ui/src/views/pull-request/hooks/useDiffConfig.ts
- packages/ui/src/views/pull-request/types.ts
- packages/ui/src/views/pull-request/utils.ts
- packages/views/src/layouts/types.ts
- pnpm-lock.yaml
migrate pr compare page to ui package 
also added layout.tsx , branch-chooser.tsx, radio-group and form-field.set to components
NOTE: next pr will have route in app.tsx
> feat: [pipe-22241: fix comments from last pr- webhook list page

- packages/ui/src/views/repo/repo-layout/index.tsx
fix routing on breadcrumbs for pull requests
> feat: [pipe-20716]: fix routing on breadcrumbs fr prs

- apps/gitness/src/App.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-compare.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-list.tsx
- packages/ui/src/views/index.ts
- packages/ui/src/views/layouts/PullRequestCompareLayout.tsx
- packages/ui/src/views/repo/pull-request/compare/components/pull-request-compare-form.tsx
- packages/ui/src/views/repo/pull-request/pull-request-list-page.tsx
- packages/ui/src/views/repo/repo-layout/index.tsx
first version of pr compare page
> feat: [pipe-20716]: first version of pr compare page

- apps/gitness/src/pages-v2/repo/repo-summary.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
Handled Loading and No Data states correctly and passed the loading states as needed to the view layer.
After Fix:
https://github.com/user-attachments/assets/202cd649-9202-4a03-9559-0f5d49d26517
Before Fix:
https://github.com/user-attachments/assets/e50a3aa6-329f-4d22-89b9-9160a013700e
> Fixed Summary Page Flicker

- packages/ui/src/views/repo/webhooks/webhook-list/repo-webhook-list-page.tsx
remove star filter on webhook list page
> feat: [pipe-20716]: remove star filter on webhook list page

- apps/gitness/src/framework/context/ThemeContext.tsx
Currently light-mode is a work in progress. Until it is ready, dark mode should be set as the default theme in HOSS.
> chore: [XD-48]: Temporarily use dark mode as default

- packages/ui/src/views/repo/components/branch-selector/branch-selector.tsx
> feat: [pipe-23933]: fix issue on branch selector

- apps/gitness/src/pages-v2/repo/repo-list.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/es/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/components/search-box.tsx
- packages/ui/src/views/repo/repo-list/repo-list-page.tsx
- packages/ui/src/views/repo/repo-list/repo-list.tsx
- packages/ui/src/views/repo/repo-list/types.ts
https://github.com/user-attachments/assets/af20925c-0501-492f-9914-302ae466c38d
> Fixes flicker issue on repo-list page on clearing search

- apps/gitness/src/App.tsx
- apps/gitness/src/components/RootWrapper.tsx
- apps/gitness/src/components/stores/recent-pinned-nav-links.store.ts
- packages/ui/src/components/manage-navigation/index.tsx
- packages/ui/src/components/navbar/navbar-item/index.tsx
- packages/ui/src/components/navbar/navbar.tsx
- packages/ui/src/components/navbar/types.ts
- packages/ui/src/data/navbar-menu-data.ts
- packages/ui/src/data/pinned-menu-items-data.ts
- packages/ui/src/views/layouts/SandboxRoot.tsx
https://harness.slack.com/archives/C07QA52CWKH/p1733490169130969
> feat: [PIPE-23928]: Persist pinned and recent links in localStorage

- apps/design-system/src/pages/view-preview/repo-view-wrapper.tsx
- apps/design-system/src/pages/view-preview/root-view-wrapper.tsx
- apps/design-system/src/views/repo-list/repo-list-store.json
- apps/design-system/src/views/repo-list/repo-list.tsx
- apps/design-system/src/views/repo-summary/repo-summary-props.json
- apps/design-system/src/views/repo-summary/repo-summary.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
This pull request updates and fixes the data to ensure proper functionality of the preview.
**Before:**
https://deploy-preview-540--harness-xd-review.netlify.app/view-preview/repo-list
**After:**
https://deploy-preview-545--harness-xd-review.netlify.app/view-preview/repo-list
> fix: update data for preview to work

- apps/gitness/index.html
Added "dark-std-std" as the default theme class for the html tag in index.html
> Added default theme class to html tag in index.html

- packages/ui/src/styles.css
- packages/ui/src/views/layouts/PullRequestCompareLayout.tsx
- packages/ui/src/views/repo/pull-request/diff-viewer/pull-request-diff-viewer.tsx
fix styling and diff viewer on pr compare page
> feat: [pipe-23933]: fix styling and diff viewer

- apps/gitness/src/components-v2/file-content-viewer.tsx
- apps/gitness/src/components/FileContentViewer.tsx
- apps/gitness/src/components/FileEditor.tsx
- apps/gitness/src/components/FileExplorer.tsx
- apps/gitness/src/components/GitBlame.tsx
- apps/gitness/src/pages-v2/repo/repo-code.tsx
- packages/ui/src/views/repo/repo-files/index.tsx
fix: git blame and file edit render with correct route
PS: File Editor component changes in this PR is the old component and @3em is working on moving it to components-v2, the current PR only adds changes to make it render so that he can see the old component and how the route is working
> fix: git blame and file edit render with correct route

- apps/gitness/index.html
- packages/ui/package.json
- pnpm-lock.yaml
This PR ensures that the styles are loaded properly.
> fix: ensure styles are loaded properly in gitness

- apps/gitness/src/App.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-commits.tsx
- apps/gitness/src/pages-v2/pull-request/stores/pull-request-commit-store.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/es/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/views/repo/pull-request/commits/pull-request-commits.tsx
- packages/ui/src/views/repo/pull-request/commits/pull-request-commits.types.ts
- packages/ui/src/views/repo/pull-request/index.ts
> feat: [pipe-24078]: feat: [pipe-24078]: add pr commit view

- packages/ui/locales/en/views.json
- packages/ui/locales/es/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/views/repo/repo-sidebar/index.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
> fix design issues on repo summary page

- apps/gitness/src/framework/context/ThemeContext.tsx
https://github.com/user-attachments/assets/50229688-a200-4bf0-8bc6-f3e8ccf3b1a9
> Bring back user theme choice persistence

- packages/ui/src/components/icon.tsx
- packages/ui/src/components/no-data.tsx
- packages/ui/src/icons/no-data-error.svg
- packages/ui/src/views/repo/repo-list/repo-list-page.tsx
This pull request brings updated error state for repo list page
> feat: add error state for repo list page

- apps/gitness/src/App.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/es/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/components/more-submenu.tsx
- packages/ui/src/components/navbar/navbar-item/index.tsx
- packages/ui/src/components/navbar/navbar-skeleton/index.tsx
- packages/ui/src/components/navbar/navbar.tsx
- packages/ui/src/components/navbar/types.ts
- packages/ui/src/components/settings-menu.tsx
- packages/ui/src/views/repo/index.ts
- packages/ui/src/views/repo/repo-layout/index.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-form.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-rules.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-tooltip.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-sidebar.tsx
- packages/ui/src/views/repo/repo-settings/index.tsx
- packages/ui/src/views/repo/repo-settings/repo-settings-page.tsx
- packages/ui/src/views/repo/webhooks/webhook-list/repo-webhook-list-page.tsx
- packages/views/src/components/repo-settings/repo-settings-page.tsx
- Fixes design on the `repo-settings` page. Should now be pixel perfect. 
https://github.com/user-attachments/assets/2c328a52-45fc-4600-ab38-03333b400040
https://github.com/user-attachments/assets/ed025c46-d3df-4bd7-8d53-a3be1426b53b
> Repo Settings page fixes 

- packages/ui/src/styles.css
- packages/ui/tailwind.ts
> Update shadow for dark mode

- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-comment-box.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-overview.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-status-select-button.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-system-comments.tsx
add some features to comment box
- markdown viewer and write/preview tab
https://github.com/user-attachments/assets/5a24796b-dca5-4996-b1c4-e0e63f74f93f
> feat: [pipe-24076]: add some features to comment box

- apps/gitness/src/pages-v2/pipeline/create-pipeline-dialog.tsx
- apps/gitness/src/pages-v2/repo/repo-execution-list.tsx
- apps/gitness/src/pages-v2/repo/repo-pipeline-list.tsx
- apps/gitness/src/pages-v2/repo/transform-utils/branch-transform.ts
- apps/gitness/src/pages-v2/repo/transform-utils/pipeline-list-transform.ts
- packages/ui/src/views/pipelines/create-pipeline-dialog/create-pipeline-dialog.tsx
- packages/ui/src/views/pipelines/create-pipeline-dialog/types.ts
- packages/ui/src/views/pipelines/index.ts
- packages/ui/src/views/pipelines/pipeline-list/pipeline-list-page.tsx
> feat: [PIPE-24233]: pipeline create dialog

- apps/design-system/src/pages/view-preview/root-view-wrapper.tsx
- apps/design-system/src/utils.ts
- apps/gitness/src/components/RootWrapper.tsx
- apps/gitness/src/i18n/stores/i18n-store.ts
- packages/ui/src/components/navbar/navbar-user/index.tsx
- packages/ui/src/components/navbar/navbar.tsx
- packages/ui/src/icons/account.svg
- packages/ui/src/views/layouts/SandboxRoot.tsx
Theme selector:
Language selector:
> add theme and language selections in user menu

- packages/ui/locales/en/views.json
- packages/ui/locales/es/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/components/badge.tsx
- packages/ui/src/components/button.tsx
- packages/ui/src/components/copy-button.tsx
- packages/ui/src/components/tabs.tsx
- packages/ui/src/styles.css
- packages/ui/src/views/layouts/PullRequestCompareLayout.tsx
- packages/ui/src/views/layouts/SandboxLayout.tsx
- packages/ui/src/views/repo/pull-request/compare/components/pull-request-compare-button.tsx
- packages/ui/src/views/repo/repo-branch/components/create-branch-dialog.tsx
- packages/ui/src/views/repo/repo-branch/components/more-actions-tooltip.tsx
- packages/ui/src/views/repo/repo-branch/index.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-form.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-sidebar.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
Fixes most issues mentioned by Anastasia here: https://www.figma.com/board/fixeWSBEUYLHRd91yxwWsK/Light-Mode-fixes?node-id=3-11&t=p2yC2y8Eipu52q7G-1
Copied checkmark is now Grey:
Create branch form spacing is fixed:
Default Branch label now matches in color to other labels:
Added spacing between nav items:
Removed shadow from badge component:
Fixed target area of branch context menu:
Fixed spacing above header on commits list page:
Fixed nav tab gradient being cut-off:
Fixed nav right-border to be 1px:
Add File button is now an outline button:
> design review fixes

- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/es/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-overview.tsx
- packages/ui/src/views/repo/pull-request/details/pull-request-utils.ts
- packages/ui/src/views/repo/repo-branch/components/more-actions-tooltip.tsx
fix issues on pr conv page
- center elements , and add deleted comments
> feat: [pipe-24076]: fix issues on pr conv page

- packages/ui/src/views/repo/pull-request/components/pull-request-list.tsx
> feat: [pipe-24076]: fix field in pr list page

- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/es/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/views/repo/pull-request/components/pull-request-reviewers-header.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-comment-box.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-overview.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-timeline-item.tsx
fix menu in comments and comments
> feat: [pipe-24076]: fix menu in comments and comments

- apps/design-system/src/views/pipeline-list/pipeline-list.tsx
- apps/gitness/src/pages-v2/pipeline/create-pipeline-dialog.tsx
- apps/gitness/src/pages-v2/pipeline/stores/create-pipeline-dialog.store.ts
- apps/gitness/src/pages-v2/repo/transform-utils/branch-transform.ts
- packages/ui/src/views/pipelines/create-pipeline-dialog/create-pipeline-dialog.tsx
- packages/ui/src/views/pipelines/create-pipeline-dialog/types.ts
- Add store
- Show BE errors
- Remove API
- Add dialog to preview.
BE error
> feat: [PIPE-24233]: Improve create pipeline dialog

- apps/gitness/src/pages-v2/project/project-general-settings-container.tsx
- apps/gitness/src/pages-v2/project/stores/spaces-store.ts
- apps/gitness/src/routes.tsx
- packages/ui/src/views/project/index.ts
- packages/ui/src/views/project/project-general/project-general-page.tsx
- packages/ui/src/views/project/project-settings-page.tsx
- packages/ui/src/views/project/project.types.ts
- Integrates the `project-settings-general-page`. 
https://github.com/user-attachments/assets/e402ac5f-0c04-4c25-97bf-95d772aaed7f
> Adds project settings general page

- packages/ui/src/components/navbar/navbar-user/index.tsx
Adds advanced theme selector with Mode, Color and Contrast options in the dropdown menu.
> feat: advanced theme selector

- apps/gitness/src/pages-v2/pull-request/pull-request-compare.tsx
- packages/ui/src/views/repo/pull-request/compare/pull-request-compare-page.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-overview.tsx
> feat: [pipe-23933]: fix exist header

- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-system-comments.tsx
- packages/ui/src/views/repo/pull-request/details/pull-request-details-types.ts
> feat: [pipe-23933]: add force push actiivity

- apps/gitness/src/pages-v2/project/project-labels-list-container.tsx
- apps/gitness/src/pages-v2/project/stores/labels-store.tsx
- apps/gitness/src/routes.tsx
- packages/ui/locales/en/component.json
- packages/ui/locales/en/views.json
- packages/ui/locales/es/component.json
- packages/ui/locales/es/views.json
- packages/ui/locales/fr/component.json
- packages/ui/locales/fr/views.json
- packages/ui/src/views/project/index.ts
- packages/ui/src/views/project/project-labels/components/create-label-dialog.tsx
- packages/ui/src/views/project/project-labels/components/index.ts
- packages/ui/src/views/project/project-labels/components/label-tool-tip.tsx
- packages/ui/src/views/project/project-labels/components/labels-list-view.tsx
- packages/ui/src/views/project/project-labels/project-labels-list.tsx
- packages/ui/src/views/project/project-labels/types.ts
- packages/ui/src/views/project/project-settings-page.tsx
- Adds the create-edit-delete flow on the labels page in a project scope. 
https://github.com/user-attachments/assets/e839aea2-7863-4492-9833-be0bfc54397f
> Create, edit delete and list labels

- apps/gitness/src/pages-v2/pull-request/pull-request-layout.tsx
- packages/ui/src/views/layouts/PullRequestLayout.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-header.tsx
add edit title in pr header
https://github.com/user-attachments/assets/8b551132-e17e-474d-b650-29a9b39390e1
> feat: [pipe-230519]:add edit title

- apps/design-system/package.json
- packages/ui/package.json
- packages/ui/vite-base.config.ts
- packages/ui/vite.config.ts
- packages/yaml-editor/package.json
- pnpm-lock.yaml
This PR slims down what is required for a CI build on Netlify to speed up deployments of the design-system app.
> chore: build:ci script to speed up production build for design-system app

- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-system-comments.tsx
- packages/ui/src/views/repo/pull-request/details/pull-request-details-types.ts
> feat: [pipe-23533]: add branch restore activity

- apps/gitness/src/pages-v2/pull-request/hooks/usePRCommonInteractions.ts
- apps/gitness/src/pages-v2/pull-request/pull-request-changes.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-diff-viewer.tsx
- packages/ui/src/views/repo/pull-request/details/components/changes/pull-request-changes.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-comment-box.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-overview.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-system-title.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-timeline-item.tsx
- packages/ui/src/views/repo/pull-request/details/pull-request-changes-page.tsx
- packages/ui/src/views/repo/pull-request/details/pull-request-utils.ts
add pr features:
copy link and scroll to comment
attach image and video
> feat: [pipe-23530]: add pr features

- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-panel.tsx
fix button in pr panel in different states
> feat: [pipe-23520]: fix button in pr panel in different states

- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-panel.tsx
> feat: [pipe-23520]: add rebase

- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-system-label-item.tsx
> feat: [pipe-23536]: add label system activity

- apps/gitness/src/pages-v2/pull-request/pull-request-changes.tsx
- packages/ui/src/components/icon.tsx
- packages/ui/src/icons/collapse-diff.svg
- packages/ui/src/icons/expand-diff.svg
- packages/ui/src/views/repo/pull-request/components/pull-request-diff-viewer.tsx
- packages/ui/src/views/repo/pull-request/details/components/changes/pull-request-changes.tsx
- packages/ui/src/views/repo/pull-request/details/pull-request-changes-page.tsx
- packages/ui/src/views/repo/pull-request/details/pull-request-details-types.ts
adds PR changes page - full diff toggle and fixes comment scollIntoView only once
https://github.com/user-attachments/assets/3003c384-f7dc-4d02-a76a-e3e960f82057
> feat: [PIPE-23545]: PR changes page - full diff toggle and comment scoll once

- packages/ui/src/views/repo/pull-request/details/components/conversation/sections/pull-request-merge-section.tsx
> feat: [pipe-23521]: add command line instruction

- apps/design-system/src/pages/view-preview/pull-request-layout-wrapper.tsx
- apps/design-system/src/pages/view-preview/view-preview.tsx
- apps/design-system/src/subjects/views/pull-request-conversation/pull-request-conversation.tsx
- apps/design-system/src/subjects/views/pull-request-conversation/pull-request-panelData.ts
- apps/design-system/src/subjects/views/pull-request-conversation/pull-request-store.ts
add conversation page in design system
> feat: [pipe-24640]: add conversation page in design system

- apps/design-system/src/pages/view-preview/view-preview.tsx
- apps/design-system/src/subjects/views/pull-request-conversation/pull-request-commits.tsx
add commit page in design system
> feat: [pipe-24641]: add commit page in design system

- apps/design-system/src/pages/view-preview/view-preview.tsx
- apps/design-system/src/subjects/views/pull-request-conversation/pull-request-changes-data.ts
- apps/design-system/src/subjects/views/pull-request-conversation/pull-request-changes.tsx
- apps/design-system/src/subjects/views/pull-request-conversation/pull-request-provider-store.ts
> feat: [pipe-24642]: add changes in preview design

- apps/design-system/src/subjects/views/pull-request-conversation/pull-request-conversation.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-comment-box.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-description-box.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-overview.tsx
> feat: [pipe-24076]: add edit functino in pr desc

- packages/yaml-editor/package.json
> chore: Bump `@harnessio/yaml-editor` to v0.13.0

- apps/design-system/src/subjects/views/repo-files/components/repo-files-wrapper.tsx
- apps/gitness/src/pages-v2/repo/repo-code.tsx
- apps/gitness/src/pages-v2/repo/repo-create-page.tsx
- apps/gitness/src/pages-v2/repo/repo-sidebar.tsx
- apps/gitness/src/pages-v2/repo/repo-summary.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/views/repo/repo-files/index.tsx
fix issue where readme was not set to true on repo creation
https://github.com/user-attachments/assets/27c0779a-b8c8-4a12-9496-0740c1ee9289
> feat: [PIPE-24640]: fix readme not being true

- apps/gitness/src/pages-v2/pull-request/pull-request-commits.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-compare.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- apps/gitness/src/pages-v2/repo/repo-branch-list.tsx
- apps/gitness/src/pages-v2/repo/repo-code.tsx
- apps/gitness/src/pages-v2/repo/repo-commit-details.tsx
- apps/gitness/src/pages-v2/repo/repo-commits.tsx
- apps/gitness/src/pages-v2/repo/repo-summary.tsx
- packages/ui/src/components/commit-copy-actions.tsx
- packages/ui/src/views/repo/components/commits-list.tsx
- packages/ui/src/views/repo/components/file-last-change-bar.tsx
- packages/ui/src/views/repo/components/summary/summary.tsx
- packages/ui/src/views/repo/pull-request/commits/pull-request-commits.tsx
- packages/ui/src/views/repo/pull-request/compare/pull-request-compare-page.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-overview.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-system-comments.tsx
- packages/ui/src/views/repo/repo-branch/components/branch-list.tsx
- packages/ui/src/views/repo/repo-branch/types.ts
- packages/ui/src/views/repo/repo-commit-details/repo-commit-details-view.tsx
- packages/ui/src/views/repo/repo-commits/repo-commits-view.tsx
- packages/ui/src/views/repo/repo-files/index.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
- packages/ui/src/views/repo/repo.types.ts
clicking commit title brings you to the commit details page of that commit 
https://github.com/user-attachments/assets/7aa0f642-51c1-4cfe-a8de-fe9a03e094e7
> feat: [pipe-24076]: add link to commit details page

- apps/gitness/src/pages-v2/repo/repo-list.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/es/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/components/badge.tsx
- packages/ui/src/components/button-with-options.tsx
- packages/ui/src/views/repo/repo-list/repo-list-page.tsx
- packages/ui/src/views/repo/repo-list/repo-list.tsx
> Fix the repo list based on the designers' review

- packages/ui/src/components/checkbox.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-rules.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-security.tsx
- packages/ui/src/views/repo/webhooks/webhook-create/components/create-webhooks-form-fields.tsx
> Fix the webhook form and repo general settings based on the designers' review

- packages/ui/src/components/alert-dialog.tsx
- packages/ui/src/components/dialogs/delete-alert-dialog.tsx
- packages/ui/src/components/filters/filters-bar/actions/views.tsx
- packages/ui/src/components/filters/manage-views.tsx
- packages/ui/src/components/manage-navigation/index.tsx
- packages/ui/src/views/repo/repo-summary/components/edit-repo-details-dialog.tsx
- packages/ui/src/views/user-management/components/admin-dialog.tsx
- packages/ui/src/views/user-management/components/create-user-dialog.tsx
- packages/ui/src/views/user-management/components/delete-user-dialog.tsx
- packages/ui/src/views/user-management/components/edit-user-dialog.tsx
- packages/ui/src/views/user-management/components/reset-password-dialog.tsx
This PR namespaces the `AlertDialog` components and restores the open/close animations.
fixes #783
> feat: Namespace `AlertDialog` components and restore open/close animations

- packages/ui/src/components/card.tsx
- packages/ui/src/views/auth/forgot-password-page.tsx
- packages/ui/src/views/auth/new-password-page.tsx
- packages/ui/src/views/auth/otp-page.tsx
- packages/ui/src/views/auth/signin-page.tsx
- packages/ui/src/views/auth/signup-page.tsx
- packages/ui/src/views/create-project-page.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-timeline-item.tsx
- packages/views/src/components/create-project-page.tsx
- packages/views/src/components/forgot-password-page.tsx
- packages/views/src/components/new-password-page.tsx
- packages/views/src/components/otp-page.tsx
- packages/views/src/components/pull-request/pull-request-diff-viewer.tsx
- packages/views/src/components/pull-request/pull-request-timeline-item.tsx
- packages/views/src/components/signin-page.tsx
- packages/views/src/components/signup-page.tsx
This PR namespaces `Card` components.
fixes #784
> feat: namespace `Card` components

- packages/ui/src/components/carousel.tsx
- packages/ui/src/components/image-carousel.tsx
This PR namespaces the `Carousel` components.
fixes #785
> feat: Namespace `Carousel` components

- packages/ui/src/components/command.tsx
- packages/ui/src/components/search-files.tsx
This PR namespaces `Command` components.
fixes #786
> feat: Namespace `Command` components

- apps/gitness/src/pages-v2/pull-request/pull-request-commits.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-compare.tsx
- apps/gitness/src/pages-v2/repo/repo-commits.tsx
fix issue on view repo at commit button in commit list
https://github.com/user-attachments/assets/87a1941e-4aa0-4ab7-b66f-633ab8cb765d
> feat: [pipe-24076]: fix issue on view repo at commit button

- apps/gitness/src/pages/run-pipeline-dialog/run-pipeline-dialog.tsx
- packages/ui/src/components/command.tsx
- packages/ui/src/components/commit-suggestions-dialog/commit-suggestions-dialog.tsx
- packages/ui/src/components/dialog.tsx
- packages/ui/src/components/dialogs/exit-confirm-dialog.tsx
- packages/ui/src/components/git-commit-dialog/git-commit-dialog.tsx
- packages/ui/src/components/image-carousel.tsx
- packages/ui/src/components/navbar-project-chooser.tsx
- packages/ui/src/views/pipelines/create-pipeline-dialog/create-pipeline-dialog.tsx
- packages/ui/src/views/profile-settings/components/ssh-key-create/ssh-key-create-dialog.tsx
- packages/ui/src/views/profile-settings/components/token-create/token-create-dialog.tsx
- packages/ui/src/views/profile-settings/components/token-create/token-success-dialog.tsx
- packages/ui/src/views/project/project-labels/components/create-label-dialog.tsx
- packages/ui/src/views/project/project-members/components/invite-member-dialog.tsx
- packages/ui/src/views/repo/components/token-dialog/clone-credential-dialog.tsx
- packages/ui/src/views/repo/repo-branch/components/create-branch-dialog.tsx
This PR namespaces the `Dialog` components.
fixes #787
> feat: Namespace `Dialog` components

- apps/gitness/src/components-v2/file-content-viewer.tsx
- packages/ui/src/components/file-control-bars/file-viewer-control-bar.tsx
- packages/ui/src/components/file-control-bars/types.ts
adds repo files commits history section
> feat: add repo files commits history

- apps/gitness/src/routes.tsx
Minor bug fix from PR: https://github.com/harness/canary/pull/806
> Fix: Minor bug fix for PR compare route definition

- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-comment-box.tsx
fix issue on reply and resolve and not being able to reply and resolve and empty commment
> feat: [pipe-24076]: fix issue on reply and resolve

- packages/ui/locales/en/views.json
- packages/ui/src/views/repo/components/commits-list.tsx
- packages/ui/src/views/repo/pull-request/compare/pull-request-compare-page.tsx
bugfixes for pr pages
Cannot go into commit details just by clicking
"compare across forks" leads to 404
> feat: [pipe-24076]: bugfixes for pr pages

- packages/filters/src/Filters.tsx
- packages/filters/src/FiltersContent.tsx
- packages/filters/src/types.ts
Fixes 
1. filters order according to the order they were added
2. default value added for filter
> fix: updated filters rendering according to order

- packages/ui/src/views/repo/utils/filtering/pulls.ts
fix pr filter on pr list page on closed
> feat: [pipe-24076]: fix pr filter on pr list page

- apps/gitness/src/components-v2/breadcrumbs/breadcrumbs.tsx
- apps/gitness/src/routes.tsx
Tested for standalone and MFE.
For MFE - both account and project repos tested.
https://github.com/user-attachments/assets/0de56e8b-051c-49b8-94aa-1fc403f76b84
> fix: Fix breadcrumbs implementation to handle empty breadcrumb

- packages/ui/src/components/badge.tsx
- packages/ui/src/views/layouts/SandboxLayout.tsx
- packages/ui/src/views/pipelines/create-pipeline-dialog/create-pipeline-dialog.tsx
- packages/ui/src/views/pipelines/execution-list/execution-list-page.tsx
- packages/ui/src/views/pipelines/execution-list/execution-list.tsx
- packages/ui/src/views/pipelines/pipeline-list/pipeline-list-page.tsx
- packages/ui/src/views/pipelines/pipeline-list/pipeline-list.tsx
- packages/ui/src/views/repo/pull-request/compare/components/pull-request-compare-diff-list.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-item-description.tsx
- packages/ui/src/views/repo/pull-request/pull-request-list-page.tsx
- packages/ui/src/views/repo/repo-commit-details/components/commit-changes.tsx
- packages/ui/src/views/repo/repo-commit-details/components/commit-diff.tsx
This pull request brings small updates after PP design-review for next pages:
1. pull-request-list
**Before**
**After**
2. commit-details
**Before**
**After**
3. pipeline-list
**Before**
**After**
4. execution-list
**Before**
**After**
> fix: fixes after design-review

- packages/ui/src/views/repo/pull-request/compare/components/pull-request-compare-diff-list.tsx
- packages/ui/src/views/repo/pull-request/details/components/changes/pull-request-changes.tsx
- packages/ui/src/views/repo/repo-commit-details/components/commit-changes.tsx
update design on deleted files and large files based off issue
https://github.com/harness/canary/issues/749
> feat: [pipe-24078]: update design on deleted files and large files

- packages/ui/src/components/more-actions-tooltip.tsx
- packages/ui/src/views/layouts/PullRequestLayout.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-header.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-item-title.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-list.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/sections/pull-request-checks-section.tsx
- packages/ui/src/views/repo/webhooks/webhook-list/components/repo-webhook-list.tsx
Multiple fixes on PR page including text truncation, horizontal scroll etc. Clicking on webhook-list will get us into webhook details. Removes instances of replace where not needed.
> Pr page bug #2

- apps/design-system/src/pages/view-preview/view-preview.tsx
- apps/design-system/src/subjects/views/repo-empty/repo-empty-view.tsx
- packages/ui/src/views/repo/index.ts
- packages/ui/src/views/repo/repo-commit-details/components/commit-diff.tsx
- packages/ui/src/views/repo/repo-summary/repo-empty-view.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
https://github.com/user-attachments/assets/cdd17d0d-e40b-454c-8203-4928a7d24009
> feat: Adds the repo empty view

- packages/ui/src/views/repo/pull-request/pull-request-list-page.tsx
fix closed issue on filter
- navigating to closed we get a random filter applied
> feat: [pipe-24076]: fix closed issue on filter

- apps/gitness/src/AppMFE.tsx
Before fix:
https://github.com/user-attachments/assets/44c71252-a2a7-4a73-8570-6a51076176c7
After fix:
https://github.com/user-attachments/assets/b932f653-cce4-4265-9a83-f3d9ae273b0a
> Fixed breadcrumb failing API issue for MFE

- apps/gitness/src/AppMFE.tsx
- apps/gitness/src/pages-v2/repo/repo-list.tsx
Before fix:
https://github.com/user-attachments/assets/f2632dd0-d44e-47c2-8ec3-0adc6c58ca25
After fix:
https://github.com/user-attachments/assets/62dc5ea6-5508-4430-8107-f412b857d764
> Breadcrumb api call fix

- apps/gitness/src/framework/context/AppContext.tsx
- packages/ui/src/shared-style-variables.css
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-overview.tsx
Fixed the following issues from [Bugbash sheet](https://docs.google.com/spreadsheets/d/1vycKWFbGVsPRj9HTLjEzI-9PSic3V8DUcvwItHL2QpA/edit?gid=1992536314#gid=1992536314)
- Deleted PR comment has black background in light theme
- User avatar not displaying first letter (near comment textarea)
- When adding a comment, 0 is displayed till the API call completes
> Mfe bug fixes

- packages/ui/components.json
- packages/ui/src/components/icon.tsx
- packages/ui/src/components/index.ts
- packages/ui/src/components/sidebar/separator.tsx
- packages/ui/src/components/sidebar/sidebar.tsx
- packages/ui/src/components/sidebar/skeleton.tsx
- packages/ui/src/components/sidebar/use-is-mobile.tsx
- packages/ui/src/icons/sidebar-left.svg
- packages/ui/src/icons/sidebar-right.svg
- packages/ui/src/views/layouts/PullRequestLayout.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-header.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-item-title.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-list.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-comment-box.tsx
- packages/ui/src/views/repo/repo-summary/repo-empty-view.tsx
- packages/ui/src/views/repo/webhooks/webhook-list/components/repo-webhook-list.tsx
This PR adds the initial form of a new `Sidebar` component.
Fixes #726
> feat: Add initial `Sidebar` component

- apps/design-system/src/subjects/views/pull-request-compare/pull-request-compare.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-compare.tsx
- apps/gitness/src/styles/styles.css
- packages/ui/src/components/markdown-viewer/style.css
- packages/ui/src/views/repo/pull-request/compare/components/pull-request-compare-form.tsx
- packages/ui/src/views/repo/pull-request/compare/pull-request-compare-page.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-comment-box.tsx
add preview in desc box in compare page
and fix styling issue on images in markdown viewer
> feat: [pipe-24076]: add preview in desc box in compare page

- packages/ui/src/components/git-commit-dialog/git-commit-dialog.tsx
> feat: [pipe-24076]: fix bypass in commit dialog 

- apps/design-system/src/pages/view-preview/view-settings.tsx
- packages/ui/src/shared-style-variables.css
> feat: Update style tokens for light-std-std and introduce dark-std-high

- apps/gitness/src/routes.tsx
- Add remaining document titles in `routes.tsx`.
- Moved page titles to an enum.
> chore: Add remaining document titles

- apps/gitness/src/pages-v2/pull-request/pull-request-list.tsx
- apps/gitness/src/pages-v2/pull-request/stores/pull-request-list-store.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/views/repo/pull-request/components/pull-request-item-title.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-list.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/sections/pull-request-changes-section.tsx
- packages/ui/src/views/repo/pull-request/pull-request-list-page.tsx
bug fixes for pr pages
- fixed incorrect empty state - if repo has no open PR but some closed PRs
- fixed some css styling and text 
- fixed number in open and closed state in pr list
> feat: [pipe-24076]: bug fixes for pr pages

- apps/design-system/src/subjects/views/repo-webhooks-list/repo-webhooks-list-store.ts
- apps/design-system/src/subjects/views/repo-webhooks-list/repo-webhooks-list.tsx
- apps/gitness/src/pages-v2/webhooks/stores/webhook-store.tsx
- apps/gitness/src/pages-v2/webhooks/webhook-list.tsx
- packages/ui/src/components/more-actions-tooltip.tsx
- packages/ui/src/views/repo/webhooks/webhook-create/repo-webhook-create-page.tsx
- packages/ui/src/views/repo/webhooks/webhook-list/components/repo-webhook-list.tsx
- packages/ui/src/views/repo/webhooks/webhook-list/repo-webhook-list-page.tsx
- packages/ui/src/views/repo/webhooks/webhook-list/types.ts
- Updates webhook listing with the new [deisgn](https://www.figma.com/design/Lu5QJyq9tQEjHMeQmQhbAd/Gitness-Product-Design---Stage-2?node-id=5318-41915&p=f&t=z58rqnihCqJd9NVY-0)
- The new design required minor changes to the `webhooks-store` as well, along with other minor fixes to components such as `more-actions-tooltip`. 
https://github.com/user-attachments/assets/1249adc3-0603-4fdb-85a9-db7e48f349dc
> Updates webhook list page

- apps/portal/src/content/docs/components/button-group.mdx
Fixes [#868](https://github.com/harness/canary/issues/868)
> docs: added button-grp docs

- apps/portal/src/content/docs/components/multi-select.mdx
Fixes [#863](https://github.com/harness/canary/issues/863)
> docs: added support for multi-select

- apps/gitness/src/components-v2/git-commit-dialog.tsx
- packages/ui/src/components/git-commit-dialog/git-commit-dialog.tsx
fix bug in commit dialog where you dont get prompted to bypass rule when u commit a new rule
> feat: [pipe-24076]: fix bug in commit dialog

- packages/ui/src/components/button.tsx
- packages/ui/src/components/pagination.tsx
- packages/ui/src/views/repo/components/commits-list.tsx
- packages/ui/src/views/repo/pull-request/commits/pull-request-commits.tsx
This pull request brings small updates for pr-commits page
**Before**
**After**
> Fix pr commits design review

- apps/gitness/src/pages-v2/pull-request/pull-request-commits.tsx
- packages/ui/src/views/repo/pull-request/commits/pull-request-commits.tsx
> feat: [pipe-24076]: fix loading on pr commit page

- apps/gitness/src/routes.tsx
This PR returns required routes fields for `profile-settings` route
> fix: profile-settings routes fields

- apps/portal/src/content/docs/components/checkbox.mdx
> docs: added docs for checkbox

- apps/portal/src/content/docs/components/copy-button.mdx
> docs: added docs for copy-button

- packages/ui/src/components/button.tsx
- packages/ui/src/components/form-primitives/legend.tsx
- packages/ui/src/components/input.tsx
- packages/ui/src/components/language-selector/language-dialog.tsx
- packages/ui/src/components/theme-selector-v2/theme-dialog.tsx
- packages/ui/src/views/repo/components/commits-list.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
This PR adds `avatarUrl` to the `RepoSummaryView`
> feat: Add avatar url

- apps/portal/src/content/docs/components/alert-dialog.mdx
> docs: added doc for alert-dialog

- apps/portal/src/content/docs/components/calendar.mdx
> docs: added docs for calendar

- apps/portal/src/content/docs/components/button-options.mdx
> docs: added docs for button-options

- packages/ui/src/components/input-otp.tsx
- packages/ui/src/views/auth/otp-page.tsx
- packages/views/src/components/otp-page.tsx
This PR namespaces the `InputOTP` components.
fixes #789
> feat: Namespace `InputOTP` components

- apps/design-system/src/subjects/views/repo-summary/repo-summary-props.json
- packages/ui/src/shared-style-variables.css
- packages/ui/src/views/repo/components/summary/summary.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
- packages/ui/src/views/repo/repo.types.ts
- packages/ui/tailwind.ts
> Summary page fixes

- apps/design-system/src/subjects/views/execution-details/index.tsx
- packages/ui/src/views/execution/execution-header.tsx
- packages/ui/src/views/execution/execution-status.tsx
- packages/ui/src/views/execution/execution-tree.tsx
- packages/ui/src/views/execution/pipeline-status.tsx
- packages/ui/src/views/execution/step-execution.tsx
- packages/ui/src/views/execution/types.ts
> feat: PR #939 follow up

- apps/design-system/src/subjects/views/pipeline-edit/pipeline-edit.tsx
- packages/ui/src/views/pipeline-edit/components/graph-implementation/utils/step-icon-utils.tsx
- packages/ui/src/views/pipeline-edit/components/graph-implementation/utils/yaml-to-pipeline-graph.tsx
- packages/ui/src/views/pipeline-edit/components/pipeline-studio-graph-view.tsx
- packages/ui/src/views/pipeline-edit/components/pipeline-studio-internal.tsx
- packages/ui/src/views/pipeline-edit/pipeline-edit.tsx
- packages/ui/src/views/pipeline-edit/pipeline-studio.tsx
- expose getStepIcon prop on the PipelineEdit component
> expose getStepIcon

- packages/ui/src/components/input.tsx
- packages/ui/src/components/multi-select.tsx
- packages/ui/src/components/navbar-skeleton/item.tsx
- packages/ui/src/components/navbar/navbar-item/index.tsx
- packages/ui/src/components/navbar/navbar.tsx
- packages/ui/src/components/select.tsx
- packages/ui/src/components/stacked-list.tsx
- packages/ui/src/components/table.tsx
- packages/ui/src/components/tabs.tsx
- packages/ui/src/components/textarea.tsx
- packages/ui/src/shared-style-variables.css
- packages/ui/src/views/repo/components/branch-selector/branch-selector.tsx
- packages/ui/src/views/repo/repo-summary/components/edit-repo-details-dialog.tsx
Fixed the following issues from [this list](https://harness.slack.com/archives/C07QA52CWKH/p1738576216864009):
3, 6, 7, 9, 10
Fixed the following issues as well:
- Repo List hover color was not working
- Edit description dialog for a repo had two close buttons
> Figma fixes

- packages/ui/src/components/navbar-project-chooser.tsx
- packages/ui/src/components/navbar-skeleton/group.tsx
Updated navigation spacing settings to match design draft
> Navbar spacings update

- apps/design-system/src/subjects/views/execution-details/index.tsx
- packages/ui/src/components/tabs.tsx
- packages/ui/src/views/execution/execution-header.tsx
- packages/ui/src/views/execution/execution-status.tsx
- packages/ui/src/views/execution/execution-tabs.tsx
- packages/ui/src/views/execution/pipeline-status.tsx
> Update UI changes to Execution details in packages/ui/views

- apps/gitness/src/pages-v2/repo/repo-import-page.tsx
- packages/ui/src/views/repo/repo-import/repo-import.tsx
> feat: [pipe-24076]: add other import options

- packages/yaml-editor-playground/src/examples/data-flow/YamlEditorWrapper.tsx
- packages/yaml-editor/src/components/YamlEditor.tsx
- packages/yaml-editor/src/index.ts
https://github.com/user-attachments/assets/1a30e226-82b4-4597-a0e6-43780132a4fd
> feat: support for animating the yaml loading in

- apps/design-system/src/subjects/views/pipeline-edit/mocks/pipelineExecutionMock.tsx
- apps/design-system/src/subjects/views/pipeline-edit/nodes/custom-step-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-execution.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/components/execution-status.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/components/warning-label.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/parallel-group-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/serial-group-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/stage-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/step-node.tsx
- packages/pipeline-graph/src/components/canvas/canvas.tsx
- packages/pipeline-graph/src/context/canvas-provider.tsx
- packages/ui/src/views/execution/execution-status.tsx
- packages/ui/tailwind.ts
- Fix missing data prop for parallel steps
- Fine tune visual changes 
- Serial/parallel step padding and node gap
- Max canvas scale
- Right button click (Context) menu. -  check if event.button===0
> Execution view improvements

- packages/ui/src/components/file-control-bars/file-editor-control-bar.tsx
- packages/ui/src/components/file-control-bars/file-viewer-control-bar.tsx
- packages/ui/src/components/toggle-group.tsx
- packages/ui/src/views/pipeline-edit/components/visual-yaml-toggle.tsx
- packages/views/src/components/pipeline-studio/visual-yaml-toggle.tsx
> chore: namespaced toggle-group component

- packages/ui/src/components/button.tsx
- packages/ui/src/components/checkbox.tsx
- packages/ui/src/components/input.tsx
- packages/ui/src/components/navbar-skeleton/root.tsx
- packages/ui/src/components/radio.tsx
- packages/ui/src/components/select.tsx
- packages/ui/src/components/stacked-list.tsx
- packages/ui/src/components/table.tsx
- packages/ui/src/components/textarea.tsx
- packages/ui/src/views/landing-page.tsx
- packages/ui/src/views/repo/pull-request/compare/components/pull-request-compare-form.tsx
- packages/ui/src/views/repo/repo-summary/components/clone-repo-dialog.tsx
- packages/ui/tailwind.ts
Fixed the following high priority issues:
- closes #966  
- closes #962 
- closes #963 
- closes #979 
- closes #976 
- closes #960
> Fixed high priority fixes for Demo

- packages/ui/src/components/chat.tsx
The `Chat` component provides a modular and accessible chat UI, consisting of various subcomponents for structure, messages, typing indicators, separators, and input fields.
Ensure you have the necessary dependencies installed:
```sh
npm install @harnessio/ui
```
or if using pnpm:
```sh
pnpm add @harnessio/ui
```
---
```jsx
import { Chat } from "@harnessio/ui/components";
export default function ChatExample() {
return (
<Chat.Root>
<Chat.Body>
<Chat.Separator title="Today" />
<Chat.Message avatar={<Avatar />} time="10:30 AM">
Hello! How can I help you?
</Chat.Message>
<Chat.Typing avatar={<Avatar />} />
</Chat.Body>
<Chat.Footer>
<Chat.Input />
</Chat.Footer>
</Chat.Root>
);
}
function Avatar() {
return <div className="w-5 h-5 rounded-md"></div>;
}
```
---
The root container that wraps …
> New component: Chat

- apps/design-system/src/subjects/views/pipeline-edit/mocks/pipelineExecutionMock.tsx
- apps/design-system/src/subjects/views/pipeline-edit/nodes/custom-parallel-stage-group-content-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/nodes/custom-parallel-step-group-content-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/nodes/custom-serial-stage-group-content-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/nodes/custom-serial-step-group-content-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/nodes/custom-stage-content-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/nodes/custom-step-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/components/collapsed-group-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/parallel-group-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/serial-group-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/stage-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/step-node.css
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/step-node.tsx
https://github.com/user-attachments/assets/cd4d2dc3-f329-4db9-a5f0-860a977b2742
> Stacked nodes for collapsed state

- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- apps/gitness/src/pages-v2/repo/repo-code.tsx
- apps/gitness/src/pages-v2/repo/repo-summary.tsx
- apps/gitness/src/utils/common-utils.ts
- packages/ui/src/components/git-commit-dialog/git-commit-dialog.tsx
- packages/ui/src/hooks/use-event-listener.tsx
- packages/ui/src/utils/utils.ts
- packages/ui/src/views/repo/components/summary/summary.tsx
- packages/ui/src/views/repo/pull-request/compare/components/pull-request-compare-diff-list.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-diff-viewer.tsx
- packages/ui/src/views/repo/pull-request/details/components/changes/pull-request-changes-filter.tsx
- packages/ui/src/views/repo/pull-request/details/components/changes/pull-request-changes.tsx
- packages/ui/src/views/repo/pull-request/details/pull-request-utils.ts
- packages/ui/src/views/repo/pull-request/utils.ts
- packages/ui/src/views/repo/repo-commit-details/components/commit-diff.tsx
fix: bugbash fixes includes:
1. scroll comment into view - fix needed after PR changes page optimizations
2. format number according to locale util
3. default initials for avatar = 2
4. sort files and folders in repo summary view
5. git commit dialog - fix for new file creation , show error from api
6. resolver data to show "X resolved this conversation" in diff view
7. added translation store for missing files in PR components
> fix: bugbash fixes

- apps/gitness/src/pages-v2/pipeline/pipeline-edit/components/pipeline-studio-problems-panel.tsx
- apps/portal/src/content/docs/components/problems.mdx
- packages/ui/src/components/problems.tsx
1. Cleanup `selectedProblemIdx` prop.
2. Add `action` prop on `Problems` component to render an action per problem row.
> chore: Cleanup `Problems` component

- apps/design-system/src/subjects/views/pipeline-graph/pipeline-graph.tsx
- packages/ui/src/views/pipeline-edit/components/pipeline-studio-footer.tsx
- packages/ui/src/views/pipeline-edit/components/popover-commit-info.tsx
- packages/ui/src/views/pipeline-edit/index.ts
> feat: add PipelineStudioFooter component

- packages/ui/src/components/label-marker.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-header.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-system-label-item.tsx
> feat: [pipe-24076]: fix label on label activity

- packages/ui/src/components/manage-navigation/index.tsx
- packages/ui/src/views/repo/repo-summary/components/edit-repo-details-dialog.tsx
- packages/ui/src/views/user-management/components/admin-dialog.tsx
- packages/ui/src/views/user-management/components/create-user-dialog.tsx
- packages/ui/src/views/user-management/components/delete-user-dialog.tsx
- packages/ui/src/views/user-management/components/edit-user-dialog.tsx
- packages/ui/src/views/user-management/components/reset-password-dialog.tsx
https://github.com/user-attachments/assets/75d7713f-7936-4dd2-a160-1a3357d8c229
> Add close functionality for on click of X button for dialogs

- apps/gitness/src/pages-v2/repo/constants/import-providers-map.ts
- apps/gitness/src/pages-v2/repo/repo-import-multiple-container.tsx
- apps/gitness/src/pages-v2/repo/repo-import-page.tsx
- packages/ui/src/views/repo/repo-import/repo-import-mulitple.tsx
- packages/ui/src/views/repo/repo-import/repo-import.tsx
https://github.com/user-attachments/assets/cf24eae0-cb40-4cf2-909e-98f64576f66f
> Import multiple repos feature

- apps/design-system/src/subjects/views/execution/execution-graph.tsx
- apps/design-system/src/subjects/views/execution/execution-logs.tsx
- apps/design-system/src/subjects/views/execution/pipeline-execution-graph.tsx
- apps/design-system/src/subjects/views/pipeline-edit/mocks/pipelineExecutionMock.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-edit.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-execution.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/components/collapsed-group-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/components/execution-status.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/components/floating-add-button.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/components/warning-label.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/end-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/parallel-group-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/serial-group-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/stage-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/start-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/step-node.css
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/step-node.tsx
- packages/ui/src/shared-style-variables.css
- packages/ui/src/views/pipeline-edit/components/pipeline-studio-graph-view.tsx
- packages/ui/src/views/pipeline-edit/components/pipeline-studio-internal.tsx
- packages/ui/src/views/pipeline-edit/pipeline-edit.tsx
- packages/ui/src/views/pipeline-edit/pipeline-studio.tsx
- packages/ui/tailwind.ts
[Preview](https://deploy-preview-1002--harness-xd-review.netlify.app/view-preview/pipeline-studio)
Before:
After:
> feat: makes style improvements for graph

- packages/ui/src/components/chat/chat-preview-wrapper.tsx
- packages/ui/src/components/chat/chat.tsx
Also adds support for pressing the Enter key to send a message
> feat: add Chat.CodeBlock component

- apps/design-system/src/subjects/views/pipeline-edit/canvas/canvas-button.tsx
- apps/design-system/src/subjects/views/pipeline-edit/canvas/canvas-controls.tsx
- apps/design-system/src/subjects/views/pipeline-edit/mocks/demoExecutionMock.tsx
- apps/design-system/src/subjects/views/pipeline-edit/mocks/demoPSYaml.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-edit.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-execution.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/components/custom-port.tsx
- apps/design-system/src/subjects/views/pipeline-edit/utils/common-step-utils.ts
- apps/design-system/src/subjects/views/pipeline-edit/utils/step-icon-utils.tsx
- packages/pipeline-graph/examples/src/canvas/CanvasControls.tsx
- packages/pipeline-graph/package.json
- packages/pipeline-graph/src/context/canvas-provider.tsx
- packages/pipeline-graph/src/pipeline-graph-internal.tsx
- packages/ui/package.json
- packages/ui/src/views/pipeline-edit/components/graph-implementation/utils/step-icon-utils.tsx
- packages/ui/src/views/pipeline-edit/components/graph-implementation/utils/yaml-to-pipeline-graph.tsx
- packages/ui/src/views/pipeline-edit/components/pipeline-studio-graph-view.tsx
- packages/ui/src/views/pipeline-edit/components/pipeline-studio-internal.tsx
- packages/ui/src/views/pipeline-edit/index.ts
- packages/ui/src/views/pipeline-edit/pipeline-edit.tsx
- packages/ui/src/views/pipeline-edit/pipeline-studio.tsx
- Add reset button
- Add demo pipeline
- Expose props 
- Multiple small alignment
> Pipeline studio - multiple changes

- apps/design-system/src/subjects/views/pipeline-edit/pipeline-edit.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-execution.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/components/custom-port.tsx
- packages/ui/src/shared-style-variables.css
This pull request adds style updates for connecting lines between cards and token updates for animations 
Before:
After:
Before:
After:
> feat: update pipeline graph and port styling with design system tokens

- apps/design-system/src/hooks/useLogs.ts
- apps/design-system/src/hooks/useTree.tsx
- apps/design-system/src/subjects/views/execution/execution-logs.tsx
- apps/design-system/src/subjects/views/execution/mocks/mock-data.ts
- apps/design-system/src/subjects/views/execution/pipeline-execution-graph.tsx
- packages/ui/src/components/treeview.tsx
- packages/ui/src/views/execution/console-logs.tsx
- packages/ui/src/views/execution/execution-info.tsx
- packages/ui/src/views/execution/types.ts
- packages/ui/src/views/execution/utils.tsx
1. Refactors `<ExecutionInfo />` to use `LogsStore` now.
2. Adds a hook `useLogs` that handles logs to display in console based on step status.
3. Refactors `<ConsoleLogs />` to auto-scroll to the last log(at the bottom).
https://github.com/user-attachments/assets/5e73e77e-46ef-4215-a0eb-6643ac86cd55
> feat: Stream logs in real-time

- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-panel.tsx
- packages/ui/src/views/repo/repo-branch/components/create-branch-dialog.tsx
- packages/ui/src/views/repo/repo-create/index.tsx
fix issues:
also fix learn about readme 
MFE: after creating a branch - click on create branch again - previous form data persists
> feat: [pipe-24076]: fix branch dialog

- apps/design-system/src/subjects/views/execution/pipeline-execution-graph.tsx
- apps/design-system/src/subjects/views/pipeline-edit/nodes/custom-parallel-stage-group-content-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/nodes/custom-parallel-step-group-content-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/nodes/custom-serial-stage-group-content-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/nodes/custom-serial-step-group-content-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/nodes/custom-stage-content-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/nodes/custom-step-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-execution.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/parallel-group-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/serial-group-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/stage-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-nodes/step-node.tsx
- apps/design-system/src/subjects/views/pipeline-edit/types/common.ts
- apps/design-system/src/subjects/views/pipeline-graph/pipeline-graph-minimal.tsx
- apps/design-system/src/subjects/views/pipeline-graph/pipeline-graph.tsx
- apps/gitness/src/pages-v2/pipeline/pipeline-edit/components/pipeline-studio-graph-view.tsx
- packages/pipeline-graph/src/pipeline-graph-internal.tsx
- packages/pipeline-graph/src/render/render-svg-lines.ts
- packages/ui/src/views/pipeline-edit/components/graph-implementation/context/PipelineStudioNodeContext.tsx
- packages/ui/src/views/pipeline-edit/components/pipeline-studio-graph-view.tsx
- remove unused prop edgeClassName
- add globalData to context/provider
- use globalData in the nodes
- set globalData only for the execution graph
> Pipeline graph globalData - to distingvish between edit and execution

- packages/ui/src/shared-style-variables.css
* Update shared-style-variables.css
protonopia upd
* Update shared-style-variables.css
> Update shared-style-variables.css (#1027)

- packages/ui/src/views/pipeline-edit/components/graph-implementation/utils/yaml-to-pipeline-graph.tsx
process github job to harness stage
> feat: process github job to stage

- apps/design-system/src/subjects/views/pipeline-edit/hooks/useAnimatePipeline.tsx
- apps/design-system/src/subjects/views/pipeline-edit/mocks/animations/demoExecutionMock.tsx
- apps/design-system/src/subjects/views/pipeline-edit/nodes/types.ts
- apps/design-system/src/subjects/views/pipeline-edit/pipeline-execution.tsx
https://github.com/user-attachments/assets/0085f755-827d-44b9-aef9-1b037f07c128
> feat: Add pipeline studio animation

- packages/ui/src/views/pipeline-edit/components/graph-implementation/utils/yaml-to-pipeline-graph.tsx
pick from https://github.com/harness/canary/pull/1044
> feat: process github job to stage (#1044)

- apps/portal/src/content/docs/components/dialog.mdx
> docs: added support for dialog component

- apps/portal/src/content/docs/components/caption.mdx
> docs: added docs for caption

- apps/design-system/src/subjects/views/execution/execution-logs.tsx
- apps/gitness/src/routes.tsx
- packages/ui/src/views/execution/execution-status.tsx
- packages/ui/src/views/execution/pipeline-status.tsx
- packages/ui/tailwind.ts
https://github.com/user-attachments/assets/c3968b13-0c05-4931-9106-59c128ac50ff
> feat: blink dot, success state, timers

- apps/design-system/src/subjects/views/execution/execution-logs.tsx
- packages/ui/src/views/execution/pipeline-status.tsx
Move logic to design system. Fix views.
> fix: timer, architecture

- packages/pipeline-graph/examples/src/canvas/CanvasControls.tsx
- packages/pipeline-graph/src/context/canvas-provider.tsx
Uploading Screen Recording 2025-02-10 at 12.32.15.mov…
> Fix pipeline graph scale calculation

- packages/ui/src/components/treeview.tsx
- packages/ui/src/views/pipeline-edit/components/pipeline-studio-footer.tsx
> fix: fix border color pipeline studio, fix tree view of execution details

- packages/ui/src/views/repo/webhooks/webhook-create/components/create-webhooks-form-fields.tsx
fix webhook form issue - autocompleting fields
> feat: [pipe-24076]: fix webhook form issue

- packages/ui/src/components/chat/chat-diff-viewer.tsx
- packages/ui/src/components/dialog.tsx
- packages/ui/src/components/dropdown-menu.tsx
- packages/ui/src/components/manage-navigation/manage-navigation-search.tsx
- packages/ui/src/components/popover.tsx
- packages/ui/src/components/problems.tsx
- packages/ui/src/components/search-files.tsx
- packages/ui/src/components/sheet.tsx
- packages/ui/src/views/execution/execution-status.tsx
- packages/ui/src/views/layouts/SandboxLayout.tsx
- packages/ui/src/views/pipeline-edit/components/pipeline-studio-footer.tsx
- packages/ui/src/views/repo/webhooks/webhook-executions/repo-webhook-execution-details-page.tsx
> feat: restore components animations

- apps/gitness/package.json
- packages/canary/package.json
- packages/forms/package.json
- packages/ui/package.json
- packages/yaml-editor-playground/package.json
- packages/yaml-editor/package.json
- pnpm-lock.yaml
> Decrease react testing library version

- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- apps/gitness/src/pages-v2/pull-request/stores/pull-request-provider-store.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-panel.tsx
fix issue on loading when pr is closed
> feat: [pipe-24076]: fix issue on loading when pr is loading

- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-branch-badge.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-overview.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-system-comments.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-system-merge.tsx
fix scroll issue
https://github.com/user-attachments/assets/e68b72aa-d960-4f19-b3c5-7e0554db3580
> feat: [pipe-24077]: fix scroll issue

- apps/gitness/src/pages-v2/repo/repo-branch-rules-container.tsx
- packages/ui/src/views/auth/signup-page.tsx
- packages/ui/src/views/repo/repo-branch-rules/repo-branch-settings-rules-page.tsx
fixes form reset on submit
if form errors out on submit - data is persisted
> fix form reset on submit

- packages/ui/src/components/avatar.tsx
- packages/ui/src/components/navbar/navbar-user/index.tsx
- packages/ui/src/views/pipeline-edit/components/popover-commit-info.tsx
- packages/ui/src/views/profile-settings/profile-settings-general-page.tsx
- packages/ui/src/views/project/project-members/components/invite-member-dialog.tsx
- packages/ui/src/views/project/project-members/components/member-list.tsx
- packages/ui/src/views/repo/components/commits-list.tsx
- packages/ui/src/views/repo/components/file-last-change-bar.tsx
- packages/ui/src/views/repo/pull-request/compare/pull-request-compare-page.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-diff-viewer.tsx
- packages/ui/src/views/repo/pull-request/components/reviewers/pull-request-reviewers-header.tsx
- packages/ui/src/views/repo/pull-request/components/reviewers/pull-request-reviewers-item.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-comment-box.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-description-box.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-overview.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-system-comments.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-system-label-item.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-system-merge.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-system-reviewer-add.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-system-reviewer-delete.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-system-title.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-timeline-item.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/sections/pull-request-changes-section.tsx
- packages/ui/src/views/repo/repo-branch-rules/components/repo-branch-rules-fields.tsx
- packages/ui/src/views/repo/repo-branch/components/branch-list.tsx
- packages/ui/src/views/repo/repo-commit-details/repo-commit-details-view.tsx
- packages/ui/src/views/user-management/components/users-list.tsx
- added avatarVariants
- сleaned up the code where the component was used
> fix: fix avatar component at UI

- apps/gitness/package.json
- pnpm-lock.yaml
Fixes build failures for [Opensource_Canary_UI_Release_Build](https://harness0.harness.io/ng/account/l7B_kbSEQD2wjrM7PShm5w/all/orgs/PROD/projects/Harness/pipelines/Opensource_Canary_UI_Release_Build/executions?storeType=INLINE) image build and publish job.
> fix: Fix webpack config

- apps/gitness/src/AppMFE.tsx
> fix: toast provider for MFE

- packages/yaml-editor/package.json
- packages/yaml-editor/playground/index.html
- packages/yaml-editor/playground/src/common/content/pipeline-stage-approval.ts
- packages/yaml-editor/playground/src/common/content/react.ts
- packages/yaml-editor/playground/src/common/inline-actions/inline-actions-def.ts
- packages/yaml-editor/playground/src/common/schema/unified.json
- packages/yaml-editor/playground/src/common/theme/theme.ts
- packages/yaml-editor/playground/src/demo1/demo1.tsx
- packages/yaml-editor/playground/src/demo2/demo2.tsx
- packages/yaml-editor/playground/src/demo3/demo3.tsx
- packages/yaml-editor/playground/src/main.tsx
- packages/yaml-editor/playground/src/playground.css
- packages/yaml-editor/playground/src/playground.tsx
- packages/yaml-editor/vite.config.playground.ts
> Add playground to yaml-editor

- apps/design-system/src/pages/view-preview/view-settings.tsx
- apps/portal/src/content/docs/components/select.mdx
- packages/ui/src/components/select.tsx
- packages/ui/src/components/theme-selector-v2/theme-dialog.tsx
- packages/ui/src/components/theme-selector/color-select.tsx
- packages/ui/src/components/theme-selector/contrast-select.tsx
- packages/ui/src/components/theme-selector/mode-select.tsx
- packages/ui/src/views/labels/components/label-form-color-and-name-group.tsx
- packages/ui/src/views/pipeline-edit/components/pipeline-studio-footer.tsx
- packages/ui/src/views/pipelines/create-pipeline-dialog/create-pipeline-dialog.tsx
- packages/ui/src/views/profile-settings/components/profile-settings-token-create-dialog.tsx
- packages/ui/src/views/project/project-import.tsx
- packages/ui/src/views/project/project-members/components/invite-member-dialog.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-status-select-button.tsx
- packages/ui/src/views/repo/repo-branch/components/create-branch-dialog.tsx
- packages/ui/src/views/repo/repo-create/index.tsx
- packages/ui/src/views/repo/repo-import/repo-import-mulitple.tsx
- packages/ui/src/views/repo/repo-import/repo-import.tsx
This PR namespaces the `Select` components and adds docs.
fixes #792
> feat: namespace select and add docs

- apps/design-system/src/pages/view-preview/view-preview.tsx
- apps/design-system/src/subjects/views/repo-tags/repo-tags-list.tsx
- apps/design-system/src/subjects/views/repo-tags/repo-tags-store.ts
- apps/gitness/src/pages-v2/repo/repo-branch-list.tsx
- apps/gitness/src/pages-v2/repo/repo-tags-list-container.tsx
- apps/gitness/src/pages-v2/repo/stores/repo-tags-store.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/es/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/views/repo/repo-branch/components/create-branch-dialog.tsx
- packages/ui/src/views/repo/repo-branch/index.ts
- packages/ui/src/views/repo/repo-branch/repo-branch-list-view.tsx
- packages/ui/src/views/repo/repo-branch/types.ts
- packages/ui/src/views/repo/repo-tags/components/create-tags-dialog.tsx
- packages/ui/src/views/repo/repo-tags/components/repo-tags-list.tsx
- packages/ui/src/views/repo/repo-tags/repo-tags-list-page.tsx
- Various bug fixes and tech debt improvements across the Tags and Branches pages.
- Adds `preview` for tags page.  
https://github.com/user-attachments/assets/bd5a594f-d856-47a1-a83e-c9319dd29cd7
> Tag list and Branch list fixes

- apps/gitness/src/pages-v2/project/project-member-list.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-compare.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- apps/gitness/src/pages-v2/repo/repo-branch-rules-container.tsx
- packages/ui/src/views/repo/pull-request/components/reviewers/pull-request-reviewers-header.tsx
- Fixed adding reviewers for PR
- Added missing accountIdentifier query param for all the principals API call
- Fixed no users found for PR reviewers
> Fix mfe issues

- apps/gitness/src/components-v2/git-commit-dialog.tsx
- apps/gitness/src/components/GitBlame.tsx
- apps/gitness/src/pages-v2/pull-request/hooks/use-pr-conversation-labels.ts
- apps/gitness/src/pages-v2/repo/labels/hooks/use-get-repo-label-and-values-data.ts
- apps/gitness/src/pages-v2/repo/repo-settings-general-container.tsx
- packages/ui/src/components/search-files.tsx
- packages/ui/src/views/repo/components/time-ago-hover-card.tsx
- packages/ui/src/views/repo/pull-request/compare/components/pull-request-compare-form.tsx
- packages/ui/src/views/repo/repo-commit-details/components/commit-changes.tsx
- packages/ui/src/views/repo/repo-create/index.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-rules.tsx
Code bugbash fixes includes:
1. deleted file cache from repo sidebar
2. refetch labels on adding new label value
3. remove comment feature from commit details diff
4. search files in repo code with correct casing
5. [PIPE-25375]: fix drag and drop triggers PR create in compare page
6. [PIPE-25390]: fix rules search bar reloading
7. [PIPE-25379]: GMT time overlap fix in hover card
8. [PIPE-25391]: navigate to correct rule page on edit click
[PIPE-25375]: https://harness.atlassian.net/browse/PIPE-25375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PIPE-25390]: https://harness.atlassian.net/browse/PIPE-25390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PIPE-25379]: …
> fix: [PIPE-25375,PIPE-25390, PIPE-25379, PIPE-25391]: Code bugbash fixes

- apps/gitness/src/components-v2/app-shell.tsx
- apps/gitness/src/framework/hooks/useSpaceSSE.tsx
fix mfe issue where 'usespacesse' hook was missing the routing id in call in mfe
> fix: [pipe-25402]: fix 'usespacesse' hook for mfe

- apps/gitness/src/pages-v2/repo/repo-commits.tsx
- apps/gitness/src/pages-v2/repo/repo-settings-general-container.tsx
https://github.com/user-attachments/assets/6974be23-644a-4e63-b812-766df7bf7f94
> Repo settings page fixes

- packages/ui/src/components/text.tsx
This pull request removes the `deprecated` status of the `Text` component as there is currently no alternative approach available
> chore: remove deprecated status from Text component

- packages/ui/src/views/repo/pull-request/components/pull-request-diff-viewer.tsx
- packages/ui/src/views/repo/pull-request/details/components/common/pull-request-comment-view.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-panel.tsx
- packages/ui/src/views/repo/pull-request/details/pull-request-details-types.ts
fixes : 
[PIPE-25374]: ellipsis vertical icon for PR panel
[PIPE-25382]: PR diff comments proxy object issue in MFE
[PIPE-25374]: https://harness.atlassian.net/browse/PIPE-25374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PIPE-25382]: https://harness.atlassian.net/browse/PIPE-25382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [PIPE-25374,PIPE-25382]: PR diff comments in MFE and PR panel icon

- packages/ui/src/views/repo/components/branch-selector/branch-selector.tsx
- packages/ui/src/views/repo/repo-branch/components/create-branch-dialog.tsx
- packages/ui/src/views/repo/repo-tags/components/create-tags-dialog.tsx
This pull request makes minor corrections to the style mapping of the `BranchSelector` component and removes the unused `BranchChooser` component
**Before:**
**After:**
> feat: improve branch selector styles and create branch/tag dialogs

- apps/gitness/src/AppMFE.tsx
- apps/gitness/src/utils/path-utils.ts
Edit label page goes into an infinite loop when it encounters a SPACE character and other Special Characters in the label. This PR aims fixing that issue, but this still won't work for the following special Characters: #, %, / and \\
Need to ask the Product team if we need to support those characters in labels.
https://github.com/user-attachments/assets/e709b0ff-ecb8-4a40-92a0-82cd2bbb9dcf
> Fixed infinite loading issue for Edit Label (MFE Only)

- apps/gitness/src/pages-v2/pull-request/__tests__/pull-request-utils.test.ts
- apps/gitness/src/pages-v2/pull-request/pull-request-compare.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- apps/gitness/src/pages-v2/repo/transform-utils/__tests__/branch-transform.test.ts
- apps/gitness/src/pages-v2/repo/transform-utils/__tests__/pipeline-list-transform.test.ts
- apps/gitness/src/pages-v2/repo/transform-utils/__tests__/repo-list-transform.test.ts
- packages/ui/src/views/repo/pull-request/details/components/conversation/sections/pull-request-changes-section.tsx
Add unit tests in transform utils folder
> chore: add more tests in transform utils folder

- apps/portal/src/content/docs/components/hover-card.mdx
- packages/ui/src/components/hover-card.tsx
- packages/ui/src/views/repo/components/time-ago-hover-card.tsx
This PR namespaces the `HoverCard` components and adds documentation.
Fixes #1146
> feat: namespace and document `HoverCard` components

- apps/portal/src/content/docs/components/toggle.mdx
This PR adds documentation for the `Toggle` component.
Fixes #1190
> feat: Add `Toggle` component docs

- apps/portal/src/content/docs/components/radial-select.mdx
- packages/ui/src/views/components/RadialSelect.tsx
- packages/ui/src/views/index.ts
- packages/ui/src/views/secrets/secrets-header.tsx
> feat: update name to radio select

- packages/ui/src/views/unified-pipeline-studio/components/entity-form/entity-form-section-layout.tsx
- packages/ui/src/views/unified-pipeline-studio/components/entity-form/unified-pipeline-studio-entity-form.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/GroupInput.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/ListInput.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/common/InputLabel.tsx
> Form inputs styling

- apps/design-system/src/subjects/views/secrets/secrets.tsx
- packages/ui/src/views/secrets/create-secret/create-secret.tsx
- packages/ui/src/views/secrets/index.ts
- packages/ui/src/views/secrets/secrets-header.tsx
- packages/ui/src/views/secrets/types.ts
Adds the `edit-secret` view. Works with pre-filled data.
> Edit secret

- apps/gitness/src/components-v2/app-shell.tsx
- apps/gitness/src/framework/hooks/useSelectedSpaceId.ts
- apps/gitness/src/utils/__tests__/path-utils.test.ts
- packages/ui/src/views/landing-page.tsx
- Fixed selected Project issue (Selected project was not being retained when Menu Item was clicked)
- Fixed project selection dropdown click issue (Only text is clickable, instead the menu item should be clickable)
- Added tests for decodeURIComponentIfValid util function
Selected Project issue - Before fix:
https://github.com/user-attachments/assets/6cc57b72-c0b6-4b70-8358-7601065f1c89
Selected Project issue - After fix:
https://github.com/user-attachments/assets/8f290022-7e84-4e8e-a8e9-401a195b686a
> Bug fixes and tests

- apps/portal/src/content/docs/components/textarea.mdx
- packages/ui/locales/en/views.json
This PR adds docs for the `Textarea` component.
fixes #1220
> feat: add `Textarea` docs

- apps/portal/src/content/docs/components/spacer.mdx
- packages/ui/src/components/spacer.tsx
This PR adds documentation for the `Spacer` component.
fixes #1231
> feat: document `Spacer` component

- packages/pipeline-graph/package.json
- packages/pipeline-graph/src/context/container-node-provider.tsx
- packages/pipeline-graph/src/index.ts
- packages/pipeline-graph/src/pipeline-graph-internal.tsx
- packages/pipeline-graph/src/pipeline-graph.tsx
- packages/pipeline-graph/src/render/render-svg-lines.ts
- packages/pipeline-graph/src/types/container-node.ts
- packages/ui/package.json
- packages/ui/src/components/pipeline-nodes/components/collapsed-group-node.tsx
- packages/ui/src/components/pipeline-nodes/components/floating-add-button.tsx
- packages/ui/src/components/pipeline-nodes/parallel-group-node.tsx
- packages/ui/src/components/pipeline-nodes/serial-group-node.tsx
- packages/ui/src/components/pipeline-nodes/stage-node.tsx
- packages/ui/src/components/pipeline-nodes/step-node.tsx
- packages/ui/src/views/unified-pipeline-studio/components/graph-implementation/context/UnifiedPipelineStudioNodeContext.tsx
- Main change in the [render-svg-lines.ts](https://github.com/harness/canary/pull/1243/files#diff-7e12e8a1d81f0625afffe2f02ba8a512d0f64723c43c01496783a25169d77049)
- Types fixed
> Pipeline graph - edges fix

- apps/gitness/src/pages-v2/project/project-settings-layout.tsx
- apps/gitness/src/routes.tsx
- packages/ui/src/views/empty-page.tsx
- packages/ui/src/views/project/project-settings-tab-nav.tsx
Implemented the following for Sidebar changes in MFE:
- Coming soon page for "Search"
- Manage repositories page
https://github.com/user-attachments/assets/21a00bfe-fa1f-4b7b-a1c7-6f93e4117d29
> Sidebar changes for MFE

- packages/ui/package.json
Go back to proper Semantic versioning to use patch version.
> fix: Fix package/ui version

- apps/design-system/src/pages/view-preview/view-preview.tsx
- apps/design-system/src/subjects/views/connectors/connectors.tsx
- apps/design-system/src/subjects/views/connectors/mock-connectors-data.json
- apps/design-system/src/subjects/views/secrets/secrets.tsx
- apps/design-system/src/subjects/views/secrets/types.ts
- packages/ui/src/views/connectors/connector-header.tsx
- packages/ui/src/views/connectors/connector-reference/connector-reference.tsx
- packages/ui/src/views/connectors/index.ts
- packages/ui/src/views/connectors/types.ts
- packages/ui/src/views/index.ts
- Adds the connector reference view
https://github.com/user-attachments/assets/3f32f8c5-708f-45d6-88ce-caef675e3485
> Connectors Reference

- apps/design-system/src/subjects/views/repo-create-rule.tsx
- apps/gitness/src/framework/hooks/useGetSpaceParam.ts
- apps/gitness/src/pages-v2/project/labels/hooks/use-fill-label-store-with-project-label-values-data.ts
- apps/gitness/src/pages-v2/project/labels/project-label-form-container.tsx
- apps/gitness/src/pages-v2/project/labels/project-labels-list-container.tsx
- apps/gitness/src/pages-v2/project/project-rules-create-container.tsx
- apps/gitness/src/pages-v2/project/project-rules-list-container.tsx
- apps/gitness/src/pages-v2/project/stores/project-rules-store.tsx
- apps/gitness/src/pages-v2/repo/repo-branch-rules-container.tsx
- apps/gitness/src/pages-v2/repo/stores/repo-branch-rules-store.tsx
- apps/gitness/src/routes.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/views/project/index.ts
- packages/ui/src/views/project/project-rules/project-rules-page.tsx
- packages/ui/src/views/project/project-settings-tab-nav.tsx
- packages/ui/src/views/repo/repo-branch-rules/repo-branch-settings-rules-page.tsx
- packages/ui/src/views/repo/repo-branch-rules/types.ts
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-rules.tsx
- packages/ui/src/views/repo/repo-settings/types.ts
https://github.com/user-attachments/assets/9ad3d4ec-2cfa-4b92-bdca-ed00ee51100c
> feat: Project scoped branch rules page 

- packages/ui/package.json
> chore: bump package

- apps/design-system/src/subjects/views/secrets/mock-secrets-data.json
- packages/ui/src/views/platform/entity-reference-component.tsx
- packages/ui/src/views/platform/entity-reference-list.tsx
- packages/ui/src/views/secrets/create-secret/create-secret.tsx
- packages/ui/src/views/secrets/secret-reference/secret-reference.tsx
Error and scroll fixes on secrets drawer.
> Style fixes - Secrets Page

- packages/ui/src/components/drawer.tsx
Similar change as https://github.com/harness/canary/pull/1292 for `Drawer` component
> fix: Fix scroll issue in `Drawer` component

- packages/ui/src/views/connectors/connector-entity-form.tsx
- packages/ui/src/views/connectors/connectors-right-drawer.tsx
add api error to connector rightdrawer as a prop
> feat: [pipe-26013]: add api error to rightdrawer

- packages/ui/package.json
> chore: bump ui package

- packages/ui/src/views/unified-pipeline-studio/components/graph-implementation/nodes/step-content-node.tsx
- packages/ui/src/views/unified-pipeline-studio/index.ts
> Pipeline studio updates

- packages/ui/src/components/more-submenu.tsx
- packages/ui/src/components/settings-menu.tsx
Fix for the case when Settings menu (popup) is opened and you click on Settings menu at sidebar
> fix menu close in sidebar

- packages/ui/src/components/chat/chat.tsx
- packages/ui/src/components/pipeline-nodes/start-node.tsx
- packages/ui/src/components/scroll-area.tsx
- packages/ui/src/components/toggle-group.tsx
- packages/ui/src/components/toggle.tsx
- packages/ui/src/icons/chat-avatar-light-theme.svg
- packages/ui/src/views/execution/step-execution.tsx
- packages/ui/src/views/unified-pipeline-studio/components/graph-implementation/canvas/canvas-controls.tsx
- packages/ui/src/views/unified-pipeline-studio/components/unified-pipeline-studio-layout.tsx
- packages/ui/src/views/unified-pipeline-studio/components/visual-yaml-toggle.tsx
- packages/ui/src/views/unified-pipeline-studio/unified-pipeline-studio-internal.tsx
- **Toggle Theme Support**
- Added light theme support to Toggle components
- Updated `toggleVariants` with new theme variants (light/dark)
- Added conditional styling for toggle state based on theme
- **Chat Component Enhancements**
- Added light theme avatar support (`chat-avatar-light-theme.svg`)
- Implemented conditional avatar rendering based on theme
- Added new SVG asset for light theme chat avatar
- **UI Component Refinements**
- Updated StartNode styling (background color from `bg-background-3` to `bg-background-1`)
- Changed play icon color from `text-icons-success` to `text-icons-4`
- Modified ScrollArea thumb color (`bg-background-9` → `bg-background-13`)
- **Code Quality**
- Improved class ordering consistency
- Added theme context where needed
> design fixes

- packages/ui/src/components/file-toolbar-actions.tsx
> Fix button group css

- packages/ui/src/views/layouts/main-content-layout.tsx
> fix: inset layout corners

- packages/ui/src/components/tabnav.tsx
> fix: fix summary line

- packages/ui/src/components/file-toolbar-actions.tsx
> Fix: Fix button group border color

- packages/ui/src/components/file-toolbar-actions.tsx
https://github.com/user-attachments/assets/f79452a3-820e-4b21-9077-8b718537bd16
https://github.com/user-attachments/assets/79614c55-78e4-4617-b423-1d7c37cbd3f0
> Fix: Ensuring button group css style matches UX

- packages/ui/src/views/connectors/connector-entity-form.tsx
- packages/ui/src/views/connectors/connector-reference/connector-reference.tsx
- packages/ui/src/views/connectors/connectors-pallete-drawer.tsx
- packages/ui/src/views/unified-pipeline-studio/components/entity-form/entity-form-section-layout.tsx
- packages/ui/src/views/unified-pipeline-studio/components/palette-drawer/components/step-palette-content-layout.tsx
fix connector form and pallette
> feat: fix connector form and pallette

- packages/ui/src/components/more-submenu.tsx
- packages/ui/src/components/settings-menu.tsx
**Fixed click on overlay of More and Settings menus**
> fix click on overlay of More and Settings menus

- apps/design-system/src/subjects/views/connectors/connectors-ref.tsx
update connector ref design system with create con form
> feat: update connector ref design system with create con form

- packages/ui/locales/fr/views.json
Fixes the failing GitHub Action to publish NPM package due to `fr` translation files modified during build process.
> fix: Add missing `fr` translations to fix `pnpm build`

- packages/ui/src/views/connectors/connector-entity-form.tsx
- packages/ui/src/views/connectors/connectors-pallete-drawer.tsx
- packages/ui/src/views/unified-pipeline-studio/components/entity-form/entity-form-section-layout.tsx
- packages/ui/src/views/unified-pipeline-studio/components/palette-drawer/components/step-palette-content-layout.tsx
revert issue in spacing in step form
> fix: spacing in step form

- packages/ui/src/shared-style-variables.css
- packages/ui/src/views/labels/components/label-form-color-and-name-group.tsx
- packages/ui/src/views/labels/components/label-marker.tsx
- packages/ui/tailwind.ts
> fix labels colors

- packages/ui/src/shared-style-variables.css
- packages/ui/src/styles.css
- packages/ui/src/views/repo/repo-sidebar/index.tsx
- rolled back unnecessary changes of button color tokens for dark theme
- removed redundant wrapper of Create new file button, that was causing styles issue
- removed junk comments
Before/after:
> fix buttons colors

- packages/ui/src/views/connectors/connector-entity-form.tsx
- packages/ui/src/views/connectors/connectors-pallete-drawer.tsx
- packages/ui/src/views/unified-pipeline-studio/components/entity-form/entity-form-layout.tsx
- packages/ui/src/views/unified-pipeline-studio/components/palette-drawer/components/step-form-layout.tsx
fix styling in connector ref form
> feat: [pipe-26411]: fix styling

- packages/filters/src/index.ts
- packages/filters/src/router-context.tsx
- packages/filters/src/useRouter.ts
- packages/ui/src/context/router-context.tsx
Wrapper filters router-context under ui package router-context-provider for filter based view components
> fix: added router-context for filters

- packages/ui/package.json
> chore: bump ver

- apps/portal/src/components/docs-page/example-layout.tsx
- apps/portal/src/components/docs-page/example.tsx
- apps/portal/src/components/layout/HeaderActions.astro
- apps/portal/src/content/docs/components/accordion.mdx
- apps/portal/src/styles.css
- apps/portal/src/tailwind.css
This PR reverts the changes made in #1393 in the `portal` app.
> fix: Revert invalid class changes

- apps/design-system/src/subjects/views/unified-pipeline-studio/run-pipeline-drawer-content.tsx
- apps/design-system/src/subjects/views/unified-pipeline-studio/unified-pipeline-studio.tsx
- packages/ui/src/components/drawer.tsx
- packages/ui/src/views/index.ts
- packages/ui/src/views/run-pipeline/index.ts
- packages/ui/src/views/run-pipeline/run-pipeline-drawer-content.tsx
- packages/ui/src/views/run-pipeline/run-pipeline-from-inputs.tsx
- packages/ui/src/views/run-pipeline/utils/form-utils.tsx
- packages/ui/src/views/run-pipeline/utils/inputs-utils.ts
- packages/ui/src/views/run-pipeline/utils/yaml-utils.ts
- packages/ui/src/views/run-pipeline/visual-view.tsx
- packages/ui/src/views/run-pipeline/yaml-view.tsx
- packages/yaml-editor/src/index.ts
https://github.com/user-attachments/assets/72885589-b046-4678-820d-08419bb46c25
> Run pipeline view

- apps/design-system/src/utils/connectors/common-connector-utils.ts
- packages/ui/package.json
- packages/ui/src/views/connectors/connector-details/connector-details-configuration.tsx
- packages/ui/src/views/connectors/connector-details/connector-details-page.tsx
- packages/ui/src/views/connectors/connector-details/types.ts
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/ArrayInput.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/BooleanInput.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/ListInput.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/NumberInput.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/RadialInput.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/SelectInput.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/TextAreaInput.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/TextInput.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/common/InputTooltip.tsx
> fix: add tooltips for form inputs

- apps/portal/src/content/docs/components/tooltip.mdx
- packages/ui/src/components/tooltip.tsx
https://github.com/user-attachments/assets/aadd4a4c-eb48-4666-8ecf-fea0aecfb3b6
> fix: tooltip documentation

- packages/ui/src/views/connectors/connector-reference/connector-reference.tsx
- packages/ui/src/views/connectors/types.ts
- packages/ui/src/views/platform/entity-reference-component.tsx
- packages/ui/src/views/platform/entity-reference-list.tsx
- `Connector-ref` icons added
- Resolved minor padding issues on `secrets ref` / `connector-ref`
- Removed failure filter for connectors
> feat: add connector icons and minor fixes to styes

- packages/ui/src/views/layouts/PullRequestLayout.tsx
fix nav links in pr page
and bug for navigation that was introduced in this pr:
https://github.com/harness/canary/pull/1181
> fix: fix nav links in pr page

- packages/ui/src/components/markdown-viewer/CodeSuggestionBlock.tsx
- packages/ui/src/components/markdown-viewer/index.tsx
- packages/ui/src/components/markdown-viewer/style.css
- packages/ui/src/views/repo/pull-request/details/components/common/pull-request-comment-view.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-overview.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/regular-and-code-comment.tsx
fix issue in suggestions block
> fix: [pipe-26605]: fix issue in suggestions block

- apps/gitness/src/pages-v2/webhooks/webhook-list.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/views/repo/webhooks/webhook-list/components/repo-webhook-list.tsx
- packages/ui/src/views/repo/webhooks/webhook-list/repo-webhook-list-page.tsx
- packages/ui/src/views/repo/webhooks/webhook-list/types.ts
https://github.com/user-attachments/assets/85bbb04b-15b9-46ca-b7fe-a12ae20eeb3c
> fix: webhook page nav regression

- apps/design-system/src/subjects/views/connectors/connector-details.tsx
- apps/design-system/src/subjects/views/connectors/mock-connector-ref-list.ts
- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/views/connectors/connector-details/connector-details-header.tsx
- packages/ui/src/views/connectors/connector-details/connector-details-page.tsx
- packages/ui/src/views/connectors/connector-details/connector-details-references-list.tsx
- packages/ui/src/views/connectors/connector-details/connector-details-references-page.tsx
- packages/ui/src/views/connectors/connector-details/types.ts
- packages/ui/src/views/connectors/connector-test-connection/connector-test-connection-dialog.tsx
add connector details ref list page
https://github.com/harness/canary/pull/1458/files
> feat: [pipe-26591]: add connector details ref list page

- apps/design-system/src/pages/view-preview/app-view-wrapper.tsx
- apps/design-system/src/pages/view-preview/repo-view-wrapper.tsx
- apps/design-system/src/pages/view-preview/root-view-wrapper.tsx
- apps/design-system/src/pages/view-preview/view-preview.tsx
- apps/design-system/src/subjects/views/unified-pipeline-studio/run-pipeline-drawer-content.tsx
- apps/design-system/src/subjects/views/unified-pipeline-studio/unified-pipeline-studio.tsx
- packages/forms/package.json
- packages/forms/playground/src/examples/debug-example/debug-example.tsx
- packages/forms/playground/src/examples/debug-example/form-definition.tsx
- packages/forms/playground/src/helpers/update-values-btn.tsx
- packages/forms/playground/src/playground.tsx
- packages/forms/src/core/components/RootForm.tsx
- packages/forms/src/core/validation/zod-validation.ts
- packages/ui/src/components/problems.tsx
- packages/ui/src/views/layouts/main-content-layout.tsx
- packages/ui/src/views/run-pipeline/run-pipeline-drawer-content.tsx
- packages/ui/src/views/run-pipeline/run-pipeline-from-inputs.tsx
- packages/ui/src/views/run-pipeline/utils/inputs-utils.ts
- packages/ui/src/views/run-pipeline/visual-view.tsx
- packages/ui/src/views/run-pipeline/yaml-view.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/NumberInput.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/common/InputError.tsx
- packages/ui/src/views/unified-pipeline-studio/components/unified-pipeline-studio-layout.tsx
- packages/ui/src/views/unified-pipeline-studio/components/unified-pipeline-studio-yaml-view.tsx
- packages/yaml-editor/src/components/YamlEditor.tsx
- packages/yaml-editor/src/constants/monaco-common-default-options.ts
- packages/yaml-editor/src/hooks/useProblems.tsx
- packages/yaml-editor/src/hooks/useSchema.tsx
- packages/yaml-editor/src/utils/schema-utils.ts
- pipeline studio layout fix
- run pipeline form updated
- required field message fix
- validation improvement (all validation are optional by default as we have explicit check for required)
- onValidationChange colback adder
- DebugExample Added
- multiple schema supported
- problems trigger fixed (on marker change editor fires event in all components)
- number input improved
- run pipeline form - improved flow (wip)
Run pipeline form (validation):
Debug example:
> Multiple updates - run pipeline form, validation, yaml-editor, forms

- packages/ui/src/views/repo/pull-request/components/pull-request-diff-viewer.tsx
fix suggestion type on pr changes
> fix: fix suggestion type

- apps/portal/astro.config.ts
- apps/portal/src/components/CompactIconGrid.astro
- apps/portal/src/components/docs-page/component-example.tsx
- apps/portal/src/components/docs-page/example.tsx
- apps/portal/src/components/layout/PageFrame.astro
- apps/portal/src/content/docs/components/accordion.mdx
- apps/portal/src/content/docs/components/badge.mdx
- apps/portal/src/styles.css
This PR updates the `Badge` component docs after the implementation of the `Badge` component changed.
|Before|After|
|------|------|
|![Before](https://github.com/user-attachments/assets/78bd3c30-7c85-42d5-967c-7c40a705b9a6)|![After](https://github.com/user-attachments/assets/0ece2d14-2470-48ea-b7f7-61b98501d5e0)|
fixes #1463
> fix: Update `Badge` component docs

- apps/design-system/src/pages/view-preview/view-settings.module.css
- apps/portal/src/components/ColorPalette.astro
- packages/ui/src/components/alert-dialog.tsx
- packages/ui/src/components/chat/chat-diff-viewer.tsx
- packages/ui/src/components/dialog.tsx
- packages/ui/src/components/drawer.tsx
- packages/ui/src/components/input.tsx
- packages/ui/src/components/pipeline-nodes/components/custom-port.tsx
- packages/ui/src/components/pipeline-nodes/step-node.css
- packages/ui/src/components/tabnav.tsx
- packages/ui/src/components/textarea.tsx
- packages/ui/src/styles.css
- packages/ui/src/views/unified-pipeline-studio/components/unified-pipeline-studio-graph-view.tsx
- packages/ui/tailwind-design-system.ts
- packages/yaml-editor/src/components/BlameEditor.tsx
- packages/yaml-editor/src/utils/blame-editor-utils.ts
This PR replaces --canary variables with their --cn equivalents as part of the new design system.
Find the mappings in the following sheet for the replaced variables:
https://docs.google.com/spreadsheets/d/1NwmVrROomYGjbaujxL5xje09wwFsA81H0t5dYTTu-so/edit?gid=0#gid=0
> Replace --canary variables with their --cn equivalents

- packages/ui/src/styles.css
Replaced --canary-tw CSS variables with --cn-tw for consistency with the new design system
> Replace --canary-tw with --cn-tw

- packages/ui/src/components/badge/badge.tsx
- packages/ui/src/components/hover-card.tsx
- packages/ui/src/components/index.ts
- packages/ui/src/components/time-ago-hover-card.tsx
- packages/ui/src/utils/utils.ts
- packages/ui/src/views/repo/components/time-ago-hover-card.tsx
- adjusted the timestamp popup to match the new design
- added an arrow-pointer to the `HoverCard` component
Before/after:
> add timestamp popup design review

- packages/ui/src/components/problems.tsx
- packages/ui/src/views/run-pipeline/index.ts
- packages/ui/src/views/run-pipeline/run-pipeline-drawer-content.tsx
- packages/ui/src/views/run-pipeline/utils/index.ts
- packages/ui/src/views/run-pipeline/utils/inputs-utils.ts
- packages/ui/src/views/run-pipeline/visual-view.tsx
- packages/ui/src/views/unified-pipeline-studio/components/entity-form/entity-form-layout.tsx
- packages/ui/src/views/unified-pipeline-studio/components/entity-form/entity-form-section-layout.tsx
- packages/ui/src/views/unified-pipeline-studio/components/entity-form/unified-pipeline-studio-entity-form.tsx
- Drawer forms layout
- Add/Edit Template flow
- Style fix
> Multiple updates - pipeline studio

- apps/gitness/src/pages-v2/repo/repo-code.tsx
fix: repo code route from files summary
> fix: repo code route from files summary

- apps/gitness/src/components-v2/breadcrumbs/breadcrumbs.tsx
- packages/ui/src/components/app-sidebar/sidebar-search-legacy.tsx
- packages/ui/src/components/app-sidebar/sidebar-search/sidebar-search.tsx
- packages/ui/src/components/markdown-viewer/index.tsx
- packages/ui/src/components/markdown-viewer/style.css
- packages/ui/src/components/navbar-skeleton/root.tsx
- packages/ui/src/components/search-box.tsx
- packages/ui/src/components/sidebar/sidebar.tsx
- packages/ui/src/components/table.tsx
- packages/ui/src/styles.css
- packages/ui/tailwind-design-system.ts
Fixed a few UI issues found in the new layout:
- Fixed table body background color
- Fixed Inset border color
- Fixed Markdown Editor background color
- Fixed Sidebar, Topbar and Body background color
After Fixes:
https://github.com/user-attachments/assets/28ddb3ce-e321-4817-8675-2436ca616634
> UI fixes for the new layout

- apps/gitness/src/components-v2/file-content-viewer.tsx
> Fixed border not appearing issue in Code Editor

- apps/portal/src/content/docs/components/tabs.mdx
- packages/ui/src/components/tabnav.tsx
- packages/ui/src/components/tabs.tsx
- packages/ui/src/views/connectors/connector-details/connector-details-page.tsx
- packages/ui/src/views/execution/step-execution.tsx
- packages/ui/src/views/layouts/PullRequestLayout.tsx
- packages/ui/src/views/repo/components/branch-selector-v2/branch-selector-dropdown.tsx
- packages/ui/src/views/repo/components/branch-selector/branch-selector-dropdown.tsx
- packages/ui/src/views/repo/pull-request/compare/components/pull-request-compare-form.tsx
- packages/ui/src/views/repo/pull-request/compare/pull-request-compare-page.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-comment-box.tsx
- packages/ui/src/views/repo/repo-summary/components/clone-repo-dialog.tsx
Used NavLink in PR Tabs for the better accessibility, usability and performance
> fix pr tabs

- packages/ui/src/components/search-box.tsx
- packages/ui/src/components/table.tsx
- packages/ui/src/views/components/FilterGroup.tsx
- packages/ui/src/views/connectors/connectors-list/connectors-list-page.tsx
- packages/ui/src/views/connectors/connectors-list/connectors-list.tsx
> Connectors list design changes to match figma

- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/views/secrets/secrets-list/secrets-list-page.tsx
- packages/ui/src/views/secrets/secrets-list/secrets-list.tsx
https://github.com/user-attachments/assets/9f07f19f-4536-4fcc-931d-c46264430205
> feat: match secrets list closely to figma

- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/views/connectors/connector-details/connector-details-activities-list.tsx
fix text in connector details activity list
> feat: [pipe-26591]: fix text in connector details activity list 

- packages/ui/tailwind-design-system.ts
- packages/ui/tailwind-utils-config/components/badge.ts
> Update font style for Badge component

- apps/design-system/src/subjects/views/unified-pipeline-studio/template-list.store.ts
- packages/ui/src/views/run-pipeline/run-pipeline-drawer-content.tsx
- packages/ui/src/views/unified-pipeline-studio/components/entity-form/unified-pipeline-studio-entity-form.tsx
- packages/ui/src/views/unified-pipeline-studio/components/palette-drawer/components/step-palette-section.tsx
- packages/ui/src/views/unified-pipeline-studio/components/palette-drawer/uinfied-pipeline-step-palette-drawer.tsx
- packages/ui/src/views/unified-pipeline-studio/context/unified-pipeline-studio-context.tsx
- packages/ui/src/views/unified-pipeline-studio/unified-pipeline-studio.tsx
- Template version
- Delete empty "with"
- Error handling
- Added SkeletonList (Edit step, Run pipeline form)
> Global templates update

- apps/portal/src/content/docs/components/switch.mdx
- packages/ui/src/components/switch.tsx
- packages/ui/src/views/repo/webhooks/webhook-list/components/repo-webhook-list.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/BooleanInput.tsx
- packages/ui/tailwind-design-system.ts
- packages/ui/tailwind-utils-config/components/index.ts
- packages/ui/tailwind-utils-config/components/switch.ts
This PR modifies the Switch component based on the [new design system changes](https://www.figma.com/design/AIgjIyUzcuZzuVnuoOyhQE/Harness-Design-System--3.0-?node-id=622-85847&p=f&t=buWz95FoNgYqDKfY-0) and updates its usage across the app to reflect the migration changes.
https://github.com/user-attachments/assets/1f2a4356-6fb3-4350-beb7-0572b23e08f1
> Switch component migration to the new design system

- packages/ui/src/views/connectors/connectors-list/connectors-list.tsx
- packages/ui/src/views/secrets/secrets-list/secrets-list.tsx
- Add missing `navigate` function on Connector & Secret list item click.
> fix: Misc fixes for Connectors & Secrets list views - part 1

- packages/ui/tailwind-utils-config/components/switch.ts
Add cursor not allowed to the switch component when disabled
> Switch component cursor not allowed

- apps/design-system/src/utils/connectors/aws-kms-connector.tsx
- packages/forms/package.json
- packages/forms/src/core/utils/utils.ts
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/SelectInput.tsx
Group Input default values 
Custom disabled for Select Input
> Group Input default values - Custom disabled for Select Input

- apps/design-system/src/subjects/views/pull-request-list/pull-request-list-store.ts
- apps/design-system/src/subjects/views/pull-request-list/pull-request-list.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-list.tsx
- apps/gitness/src/pages-v2/pull-request/stores/pull-request-list-store.tsx
- apps/gitness/src/pages-v2/repo/labels/hooks/use-populate-label-store.ts
- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/components/checkbox.tsx
- packages/ui/src/components/dropdown-menu.tsx
- packages/ui/src/components/filters/filter-box-wrapper.tsx
- packages/ui/src/components/filters/filter-select.tsx
- packages/ui/src/components/filters/filters-field.tsx
- packages/ui/src/components/filters/types.ts
- packages/ui/src/components/filters/utils.ts
- packages/ui/src/components/radio.tsx
- packages/ui/src/views/components/FilterGroup.tsx
- packages/ui/src/views/repo/components/list-control-bar.tsx
- packages/ui/src/views/repo/constants/filter-options.ts
- packages/ui/src/views/repo/pull-request/components/labels/index.tsx
- packages/ui/src/views/repo/pull-request/components/labels/labels-filter.tsx
- packages/ui/src/views/repo/pull-request/pull-request-list-page.tsx
- packages/ui/src/views/repo/pull-request/pull-request.types.ts
- packages/ui/tsconfig.json
- Created a custom type under filters group
- Added labels-field as part of pr-list-page
> feat: added labels filter under pr-list-page

- packages/ui/package.json
> fix: bump ui version

- packages/ui/src/components/button.tsx
- packages/ui/src/components/counter-badge.tsx
- packages/ui/src/components/pagination/pagination-primitive.tsx
- packages/ui/src/components/split-button.tsx
- packages/ui/src/components/status-badge/__tests__/status-badge.test.tsx
- packages/ui/src/components/status-badge/status-badge.tsx
- packages/ui/tailwind-design-system.ts
- packages/ui/tailwind-utils-config/components/badge.ts
- packages/ui/tailwind-utils-config/components/button.ts
Add `-cn` prefix to the component classes.
---
---
---
> Add cn prefix to badge and button classes

- apps/portal/src/content/docs/components/switch.mdx
- packages/ui/src/components/switch.tsx
- packages/ui/src/views/repo/webhooks/webhook-list/components/repo-webhook-list.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/BooleanInput.tsx
- packages/ui/tailwind-utils-config/components/switch.ts
- Prefixed switch classes with `cn-`
- Added optional prop
- Changed `description` to `caption` for consistency with other components
- Changed html `label` to `Label` component
> Switch Component Changes

- packages/core-design-system/design-tokens/$themes.json
- packages/core-design-system/design-tokens/breakpoint/desktop.json
- packages/core-design-system/design-tokens/mode/dark/default-deuteranopia.json
- packages/core-design-system/design-tokens/mode/dark/default-protanopia.json
- packages/core-design-system/design-tokens/mode/dark/default-tritanopia.json
- packages/core-design-system/design-tokens/mode/dark/default.json
- packages/core-design-system/design-tokens/mode/dark/dimmer-deuteranopia.json
- packages/core-design-system/design-tokens/mode/dark/dimmer-protanopia.json
- packages/core-design-system/design-tokens/mode/dark/dimmer-tritanopia.json
- packages/core-design-system/design-tokens/mode/dark/dimmer.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast-deuteranopia.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast-protanopia.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast-tritanopia.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast.json
- packages/core-design-system/design-tokens/mode/light/default-deuteranopia.json
- packages/core-design-system/design-tokens/mode/light/default-protanopia.json
- packages/core-design-system/design-tokens/mode/light/default-tritanopia.json
- packages/core-design-system/design-tokens/mode/light/default.json
- packages/core-design-system/design-tokens/mode/light/dimmer-deuteranopia.json
- packages/core-design-system/design-tokens/mode/light/dimmer-protanopia.json
- packages/core-design-system/design-tokens/mode/light/dimmer-tritanopia.json
- packages/core-design-system/design-tokens/mode/light/dimmer.json
- packages/core-design-system/design-tokens/mode/light/high-contrast-deuteranopia.json
- packages/core-design-system/design-tokens/mode/light/high-contrast-protanopia.json
- packages/core-design-system/design-tokens/mode/light/high-contrast-tritanopia.json
- packages/core-design-system/design-tokens/mode/light/high-contrast.json
Updates for semantic typography styles
> Editing tokens

- apps/design-system/src/pages/view-preview/repo-files-view-wrapper.tsx
- apps/design-system/src/subjects/views/repo-files/components/repo-file-content-viewer.tsx
- apps/design-system/src/subjects/views/repo-files/components/repo-file-edit.tsx
- apps/gitness/src/components-v2/branch-selector-container.tsx
- apps/gitness/src/components-v2/create-branch-dialog.tsx
- apps/gitness/src/components-v2/file-content-viewer.tsx
- apps/gitness/src/components-v2/file-editor.tsx
- apps/gitness/src/pages-v2/repo/repo-branch-list.tsx
- apps/gitness/src/pages-v2/repo/repo-code.tsx
- apps/gitness/src/pages-v2/repo/repo-sidebar.tsx
- apps/gitness/src/pages-v2/repo/repo-summary.tsx
- apps/gitness/src/pages-v2/repo/stores/repo-branches-store.ts
- packages/ui/src/views/repo/components/branch-selector-v2/branch-selector-dropdown.tsx
- packages/ui/src/views/repo/components/branch-selector/branch-selector.tsx
- packages/ui/src/views/repo/repo-branch/components/branch-list.tsx
- packages/ui/src/views/repo/repo-branch/components/create-branch-dialog.tsx
- packages/ui/src/views/repo/repo-branch/types.ts
- packages/ui/src/views/repo/repo-files/index.tsx
- packages/ui/src/views/repo/repo-sidebar/index.tsx
- packages/ui/src/views/repo/repo-summary/components/clone-repo-dialog.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
- packages/ui/src/views/repo/repo.types.ts
- packages/ui/src/views/secrets/components/calendar-input-view.tsx
Fixes multiple bugs including:
1. Branch selector refactor in `repo-files`
2. Calendar input fixed
3. View Rules option removed
4. Create token error handling for MFE
> Bug fixes #3

- apps/design-system/src/subjects/views/connectors/connectors-ref.tsx
- apps/design-system/src/subjects/views/secrets/secrets.tsx
- apps/design-system/src/utils/connectors/github-connector.tsx
- packages/ui/package.json
- packages/ui/src/views/connectors/connector-reference/connector-reference.tsx
- packages/ui/src/views/connectors/connectors-list/utils.ts
- packages/ui/src/views/platform/entity-reference-component.tsx
- packages/ui/src/views/secrets/secret-reference/secret-reference.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/GroupInput.tsx
fixes : 
1. entity reference search
2. Group input - error message on error inside an input
> fix: entity reference search

- apps/gitness/src/RouteDefinitions.ts
- apps/gitness/src/components-v2/file-content-viewer.tsx
- apps/gitness/src/pages-v2/project/labels/hooks/use-fill-label-store-with-project-label-values-data.ts
- apps/gitness/src/pages-v2/repo/labels/hooks/use-get-repo-label-and-values-data.ts
- apps/gitness/src/pages-v2/repo/repo-commits.tsx
- apps/gitness/src/pages-v2/repo/stores/commit-details-store.ts
- apps/gitness/src/routes.tsx
- packages/ui/src/utils/utils.ts
- packages/ui/src/views/repo/repo-commit-details/components/commit-diff.tsx
- packages/ui/src/views/repo/repo-summary/components/clone-repo-dialog.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
- Multiple `p1/p2` bugs fixed.
> Bug fixes #5

- packages/ui/src/components/tag.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-item-description.tsx
- packages/ui/tailwind-utils-config/components/tag.ts
- packages/ui/tailwind-utils-config/utilities/typography.ts
- Fixed empty value in split tag
- Replaced button to tag in the PR List page
- Added `user-select: none`
- Don't show `cursor: pointer` by default
- Updated typography to use the new tokens
- Fixed icon size change issue when the text is truncated
https://github.com/user-attachments/assets/1ef1008f-ddcb-4941-973f-c28e169ae06b
> Tag component fixes

- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/components/sorts/multi-sort.tsx
- packages/ui/src/components/sorts/sort-context.tsx
- packages/ui/src/components/sorts/sort-select.tsx
- packages/ui/src/components/sorts/sort.tsx
- packages/ui/src/components/sorts/type.ts
- packages/ui/src/views/components/FilterGroup.tsx
- packages/ui/src/views/connectors/connectors-list/connectors-list-page.tsx
- packages/ui/src/views/connectors/connectors-list/types.ts
- packages/ui/src/views/repo/components/list-control-bar.tsx
> feat: added support for sort in connectors-list-page

- apps/gitness/src/components-v2/file-editor.tsx
- apps/gitness/src/components-v2/git-commit-dialog.tsx
- apps/gitness/src/framework/routing/types.ts
- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- apps/gitness/src/pages-v2/repo/repo-summary.tsx
- apps/gitness/src/pages-v2/repo/repo-tags-list-container.tsx
- apps/gitness/src/routes.tsx
- packages/ui/src/components/git-commit-dialog/git-commit-dialog.tsx
- packages/ui/src/views/repo/components/branch-selector-v2/branch-selector.tsx
- packages/ui/src/views/repo/pull-request/compare/components/pull-request-compare-button.tsx
- packages/ui/src/views/repo/pull-request/compare/pull-request-compare-page.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-panel.tsx
- packages/ui/src/views/repo/repo-branch/components/create-branch-dialog.tsx
- packages/ui/src/views/repo/repo-summary/components/summary-panel.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
- packages/ui/src/views/repo/repo-tags/components/repo-tags-list.tsx
- packages/ui/src/views/repo/repo-tags/repo-tags-list-page.tsx
Multiple bug fixes across. 
1. Adds merge errors if any to UI 
2. Resetting branch name in `create-branch` modal fixed. 
3. Commit changes dialog reset on close. Error does not persist, neither do values. 
4. Create Pull req button now works across all tabs. 
5. `Repo-summary` panel now clicable 
6. `learn-more-about-pr` link added, navigates to a new tab. 
7. `view-repo` at this point in history fixed
8. `tags-list` flicker fixed. 
9. SSH clone tab disabled unless its passed down from BE.
> Bug fixes #6

- packages/ui/src/components/filters/filters-field.tsx
> fix: update checkbox-filter label alignment

- packages/ui/package.json
- packages/ui/src/views/components/RadioSelect.tsx
- packages/ui/src/views/connectors/connector-header.tsx
- packages/ui/src/views/connectors/connectors-pallete-drawer.tsx
- packages/ui/src/views/delegates/delegate-selector/delegate-selector-form.tsx
- packages/ui/src/views/index.ts
- packages/ui/src/views/secrets/secrets-header.tsx
> fix: connector custom titles

- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- apps/gitness/src/pages-v2/pull-request/stores/pull-request-provider-store.tsx
- apps/gitness/src/pages-v2/repo/repo-branch-list.tsx
- packages/ui/src/components/split-button.tsx
- packages/ui/src/views/labels/components/labels-list-view.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-panel.tsx
- packages/ui/src/views/repo/pull-request/details/pull-request-details-types.ts
- packages/ui/src/views/repo/repo-branch/components/branch-list.tsx
- packages/ui/src/views/repo/repo-tags/components/repo-tags-list.tsx
- packages/ui/src/views/repo/repo-tags/repo-tags-list-page.tsx
Multiple bugs fixed across the app - 
1. Search, avatar, fixed on `tags-list`
2. Titled added to label so we see full path on hover
3. Merge methods now enabled/disabled based on API 
4. After merge show correct `restore`/`delete` branch btn based on rules
5. Rework logic for ^ to make it more robust and technically sound, avoid race conditions
6. Fix `PR` link on `branch-list`
7. Added `status-checks` to br list API
8. deafult br no longer has a `open-pr` option
9. Branches now sorted by last commit.
> Bug fixes #7

- apps/portal/src/content/docs/components/button.mdx
- packages/ui/src/components/button.tsx
- packages/ui/tailwind-utils-config/components/button.ts
> Refactor Button component and add Transparent variant

- packages/forms/src/core/transformers/transformers.ts
- packages/forms/src/core/utils/transform-utils.tsx
- packages/forms/src/types/types.ts
- packages/ui/src/views/connectors/connector-entity-form.tsx
- packages/ui/src/views/secrets/secret-entity-form.tsx
- packages/ui/src/views/unified-pipeline-studio/components/entity-form/entity-form-layout.tsx
- packages/ui/src/views/unified-pipeline-studio/components/entity-form/unified-pipeline-studio-entity-form.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/GroupInput.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/SelectInput.tsx
- packages/ui/src/views/unified-pipeline-studio/components/graph-implementation/context/UnifiedPipelineStudioNodeContext.tsx
- packages/ui/src/views/unified-pipeline-studio/components/stage-config/form-definition/stage-form-definition.ts
- packages/ui/src/views/unified-pipeline-studio/components/stage-config/unified-pipeline-studio-stage-config-form.tsx
- packages/ui/src/views/unified-pipeline-studio/components/steps/types.ts
- packages/ui/src/views/unified-pipeline-studio/components/unified-pipeline-stage-config-drawer.tsx
- packages/ui/src/views/unified-pipeline-studio/components/unified-pipeline-step-drawer.tsx
- packages/ui/src/views/unified-pipeline-studio/components/unified-pipeline-studio-yaml-view.tsx
- packages/ui/src/views/unified-pipeline-studio/context/unified-pipeline-studio-context.tsx
- packages/ui/src/views/unified-pipeline-studio/types/right-drawer-types.ts
- packages/ui/src/views/unified-pipeline-studio/unified-pipeline-studio-internal.tsx
- packages/ui/src/views/unified-pipeline-studio/unified-pipeline-studio.tsx
- packages/ui/src/views/unified-pipeline-studio/utils/inline-actions.ts
> Add stage configuration drawer - supported add/edit

- apps/design-system/src/subjects/views/repo-files/components/repo-file-edit.tsx
- apps/design-system/src/subjects/views/repo-files/components/repo-files-wrapper.tsx
- apps/gitness/src/components-v2/branch-selector-container.tsx
- apps/gitness/src/components-v2/create-branch-dialog.tsx
- apps/gitness/src/components-v2/file-content-viewer.tsx
- apps/gitness/src/components-v2/file-editor.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-layout.tsx
- apps/gitness/src/pages-v2/repo/repo-code.tsx
- apps/gitness/src/pages-v2/repo/repo-sidebar.tsx
- apps/gitness/src/pages-v2/repo/transform-utils/__tests__/branch-transform.test.ts
- apps/gitness/src/pages-v2/repo/transform-utils/branch-transform.ts
- packages/ui/locales/en/component.json
- packages/ui/locales/fr/component.json
- packages/ui/src/components/file-control-bars/file-viewer-control-bar.tsx
- packages/ui/src/views/layouts/PullRequestLayout.tsx
- packages/ui/src/views/repo/components/branch-selector-v2/branch-selector-dropdown.tsx
- packages/ui/src/views/repo/components/branch-selector-v2/branch-selector.tsx
- packages/ui/src/views/repo/components/branch-selector-v2/types.ts
- packages/ui/src/views/repo/components/path-action-bar.tsx
- packages/ui/src/views/repo/pull-request/compare/pull-request-compare-page.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-header-edit-dialog.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-header.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-side-bar.tsx
- packages/ui/src/views/repo/repo-branch/components/create-branch-dialog.tsx
- packages/ui/src/views/repo/repo-branch/types.ts
- packages/ui/src/views/repo/repo-files/index.tsx
- packages/ui/src/views/repo/repo-list/repo-list-page.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
- packages/ui/src/views/repo/repo-tags/components/repo-tags-list.tsx
1. Fixes on tags page (minor)
2. Labels removed during PR creation
3. Add description added to created PR
4. `branch.commiter` changes to `branch.author`
5. Create new / edit file option disabled on tags
6. implemented create branch on repo-files.
> Bug fixes #8

- packages/forms/src/core/components/RootForm.tsx
- packages/forms/src/core/transformers/transformers.ts
- packages/ui/src/views/unified-pipeline-studio/utils/inline-actions.ts
- Move Edit stage before Add step - Yaml annotation
- update output transformer to clean up null values
- cleanup
> Stage config related updates

- packages/ui/src/components/logo.tsx
- packages/ui/src/views/connectors/components/ConnectorsPalleteSection.tsx
- packages/ui/src/views/connectors/connector-entity-form.tsx
- packages/ui/src/views/connectors/connectors-list/utils.ts
- packages/ui/src/views/connectors/connectors-pallete-drawer.tsx
- packages/ui/src/views/delegates/components/delegate-connectivity-list.tsx
- packages/ui/src/views/delegates/delegate-selector/delegate-selector-form.tsx
- packages/ui/src/views/secrets/secrets-header.tsx
fix: delegates and connector styles, add helm logo
> fix: delegates and connector styles, add helm logo

- packages/ui/src/views/platform/input-reference-component.tsx
fix: input reference title tooltip
> fix: input reference title tooltip

- apps/gitness/webpack.config.cjs
> chore: Update webpack config to include content hash

- apps/design-system/src/subjects/views/multi-select-demo.tsx
- apps/portal/src/content/docs/components/multi-select-v2.mdx
- packages/ui/src/components/form-input/components/form-multi-select-v2.tsx
- packages/ui/src/components/multi-select-v2.tsx
- packages/ui/src/views/repo/repo-branch-rules/components/repo-branch-rules-fields.tsx
- packages/ui/src/views/repo/repo-branch-rules/types.ts
- packages/ui/tailwind-utils-config/components/multi-select-v2.ts
https://github.com/user-attachments/assets/73ce8598-e4a0-4a8a-967b-908002e9e52b
1. Adds error/warning theme
2. Removes dropdown when no options are provided
3. Adds documentation
4. Adds internal search 
5. Fixes caption/error states
> Minor fixes to `multi-select`

- apps/portal/src/content/docs/components/link.mdx
- packages/ui/tailwind-utils-config/components/link.ts
- removed `visited` state
- reduced number of examples
> remove visited state from Link

- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/views/delegates/components/delegate-connectivity-list.tsx
- packages/ui/src/views/delegates/delegate-selector/delegate-selector-form.tsx
new multiselect onboard to delegate selector form
> fix: new multiselect onboard to delegate selector form

- apps/portal/src/content/docs/components/pagination.mdx
- packages/ui/src/components/pagination/pagination.tsx
> Remove the truncateLimit prop from Pagination and set its default value to 5

- packages/ui/src/views/repo/components/repo-header.tsx
> Code repository header fix

- apps/portal/package.json
- apps/portal/src/components/docs-page/component-example-with-form.tsx
- apps/portal/src/components/docs-page/component-example.tsx
- apps/portal/src/components/docs-page/index.ts
- apps/portal/src/content/docs/components/button.mdx
- apps/portal/src/content/docs/components/form.mdx
- packages/ui/src/components/button.tsx
- packages/ui/src/components/form-input/components/form-number-input.tsx
- packages/ui/src/components/form-input/index.ts
- packages/ui/src/components/form-primitives/form-wrapper.tsx
- packages/ui/src/components/inputs/number-input.tsx
- packages/ui/src/components/pagination/pagination.tsx
- packages/ui/tailwind-utils-config/components/form-shared-styles.ts
- pnpm-lock.yaml
https://github.com/user-attachments/assets/e5ffe86e-a970-4d6b-a9e5-37f5a39a3ebc
> Add FormInput.Number component

- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/views/repo/repo-summary/repo-empty-view.tsx
- packages/ui/src/views/repo/repo-tags/repo-tags-list-page.tsx
Updated "Tag":
Also updated misspelled "Credentials":
> updated text 'tag' to 'Tag'

- packages/ui/src/views/repo/pull-request/components/reviewers/pull-request-reviewers-item.tsx
> CODE-3693: fix pr reviewers list text overflow

- packages/ui/src/components/button.tsx
- packages/ui/src/components/pagination/pagination-primitive.tsx
https://github.com/user-attachments/assets/7df59cdd-df78-4b0e-ad2b-efd73a0b79b2
> Update pagination page links with button styles

- apps/portal/src/content/docs/components/accordion.mdx
- packages/ui/src/components/accordion/accordion.tsx
- packages/ui/tailwind-utils-config/components/accordion.ts
- removed `Accordion.TriggerIcon` and `Accordion.TriggerLogo`
- added `prefix` prop to `Accordion.Trigger`
- adjusted `Accordion`'s documentation
> add prefix prop to accordion component

- packages/pipeline-graph/playground/src/demo6-top-align.tsx
- packages/pipeline-graph/playground/src/nodes-simple-top-allign/ta-simple-parallel-group-node.tsx
- packages/pipeline-graph/playground/src/nodes-simple-top-allign/ta-simple-step-node.tsx
- packages/pipeline-graph/playground/src/playground.tsx
- packages/pipeline-graph/playground/src/sample-data/pipeline-top-align.tsx
- packages/pipeline-graph/src/components/nodes/leaf-container.tsx
- packages/pipeline-graph/src/components/nodes/parallel-container.tsx
- packages/pipeline-graph/src/components/nodes/port.tsx
- packages/pipeline-graph/src/components/nodes/serial-container.tsx
- packages/pipeline-graph/src/context/container-node-provider.tsx
- packages/pipeline-graph/src/index.ts
- packages/pipeline-graph/src/pipeline-graph-internal.tsx
- packages/pipeline-graph/src/pipeline-graph.tsx
- packages/pipeline-graph/src/utils/layout-utils.ts
- Extend layout feature to support top alignment
- Port position
https://github.com/user-attachments/assets/4e499b17-dd36-4cfd-aecb-af6c9f597c93
> Pipeline graph layout - top alignment

- apps/portal/src/content/docs/components/form.mdx
- apps/portal/src/content/docs/components/radio.mdx
- packages/ui/src/components/form-input/components/form-radio.tsx
- packages/ui/src/components/form-input/index.ts
- packages/ui/src/components/git-commit-dialog/git-commit-dialog.tsx
- packages/ui/src/components/radio.tsx
- packages/ui/src/views/repo/repo-create/index.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-form.tsx
- packages/ui/src/views/repo/webhooks/webhook-create/components/create-webhooks-form-fields.tsx
- packages/ui/src/views/repo/webhooks/webhook-create/repo-webhook-create-page.tsx
- packages/ui/src/views/repo/webhooks/webhook-create/types.ts
- packages/ui/tailwind-utils-config/components/form-shared-styles.ts
- packages/ui/tailwind-utils-config/components/radio.ts
> Add FormInput Radio component

- apps/portal/src/content/docs/components/form.mdx
- packages/ui/src/components/checkbox.tsx
- packages/ui/src/components/form-input/components/form-checkbox.tsx
- packages/ui/src/components/form-input/index.ts
- packages/ui/src/views/labels/label-form-page.tsx
- packages/ui/src/views/labels/types.ts
- packages/ui/src/views/project/project-import.tsx
- packages/ui/src/views/repo/repo-branch-rules/components/repo-branch-rules-fields.tsx
- packages/ui/src/views/repo/repo-import/repo-import-mulitple.tsx
- packages/ui/src/views/repo/repo-import/repo-import.tsx
- packages/ui/tailwind-utils-config/components/checkbox.ts
> Add form checkbox component

- packages/core-design-system/design-tokens/mode/dark/default-deuteranopia.json
- packages/core-design-system/design-tokens/mode/dark/default-protanopia.json
- packages/core-design-system/design-tokens/mode/dark/default-tritanopia.json
- packages/core-design-system/design-tokens/mode/dark/default.json
- packages/core-design-system/design-tokens/mode/dark/dimmer-deuteranopia.json
- packages/core-design-system/design-tokens/mode/dark/dimmer-protanopia.json
- packages/core-design-system/design-tokens/mode/dark/dimmer-tritanopia.json
- packages/core-design-system/design-tokens/mode/dark/dimmer.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast-deuteranopia.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast-protanopia.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast-tritanopia.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast.json
update hover and selected color for brand set
> update hover and selected color for brand set

- packages/ui/src/views/unified-pipeline-studio/components/pipeline-config/form-definition/pipeline-form-definition.ts
- packages/ui/src/views/unified-pipeline-studio/components/pipeline-config/unified-pipeline-studio-pipeline-config-form.tsx
- packages/ui/src/views/unified-pipeline-studio/components/stage-config/form-definition/stage-form-definition.ts
- packages/ui/src/views/unified-pipeline-studio/components/unified-pipeline-pipeline-config-drawer.tsx
- packages/ui/src/views/unified-pipeline-studio/components/unified-pipeline-studio-yaml-view.tsx
- packages/ui/src/views/unified-pipeline-studio/context/unified-pipeline-studio-context.tsx
- packages/ui/src/views/unified-pipeline-studio/types/right-drawer-types.ts
- packages/ui/src/views/unified-pipeline-studio/unified-pipeline-studio-internal.tsx
- packages/ui/src/views/unified-pipeline-studio/unified-pipeline-studio.tsx
https://github.com/user-attachments/assets/e00d2354-5c7a-4592-b7e3-6e595cbcc64f
> Pipeline configuration

- apps/portal/src/content/docs/components/status-badge.mdx
- packages/ui/src/components/status-badge/status-badge.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-header.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-panel.tsx
- packages/ui/tailwind-utils-config/components/badge.ts
> Add icon to StatusBadge

- packages/ui/src/views/platform/components/entity-reference-filter.tsx
> fix: Handle filter dropdown overflow

- apps/portal/src/content/docs/components/checkbox.mdx
- apps/portal/src/content/docs/components/radio.mdx
- packages/ui/src/components/checkbox.tsx
- packages/ui/src/components/radio.tsx
- packages/ui/tailwind-utils-config/components/checkbox.ts
- packages/ui/tailwind-utils-config/components/radio.ts
The error states were added later to the Figma designs for Radio and Checkbox. This PR implements those error states.
https://github.com/user-attachments/assets/3c02353f-6038-45d0-9071-51c709e76692
> Error states for Radio and Checkbox

- apps/design-system/src/subjects/views/unified-pipeline-studio/template-list.store.ts
- packages/ui/src/views/unified-pipeline-studio/components/palette-drawer/uinfied-pipeline-step-palette-drawer.tsx
- packages/ui/src/views/unified-pipeline-studio/components/steps/harness-steps.tsx
- packages/ui/src/views/unified-pipeline-studio/components/steps/partials/container-partial.ts
- packages/ui/src/views/unified-pipeline-studio/unified-pipeline-studio.tsx
fix: Templates search/pagination in pipeline studio , remove duplicate group and parallel steps
> fix: Templates search/pagination in pipeline studio

- apps/design-system/src/subjects/views/unified-pipeline-studio/template-list.store.ts
- packages/ui/src/views/unified-pipeline-studio/components/palette-drawer/uinfied-pipeline-step-palette-drawer.tsx
- packages/ui/src/views/unified-pipeline-studio/unified-pipeline-studio.tsx
fix: add loading state for templates api
> fix: add loading state for templates api

- packages/ui/src/components/logo.tsx
- packages/ui/src/views/connectors/connectors-list/utils.ts
> feat: add rancher logo

- packages/core-design-system/design-tokens/components/desktop/base/tooltip.json
> tooltip py fix

- packages/filters/package.json
- packages/filters/src/Filters.tsx
- packages/filters/src/types.ts
+ Added functionality to reset specific filters
+ bumped filters version to 0.0.3
> feat: [CHAOS-8185]: Added functionality to reset specific filters

- packages/ui/tailwind-utils-config/components/link.ts
> fix: link focus outline

- packages/ui/tailwind-utils-config/components/accordion.ts
- Fix nested accordion arrow open state and 
- Remove border from the last child
> Fix nested accordion arrow open state, remove border from the last child

- apps/portal/src/content/docs/components/alert.mdx
- packages/ui/locales/en/component.json
- packages/ui/locales/fr/component.json
- packages/ui/src/components/alert/AlertRoot.tsx
- packages/ui/tailwind-utils-config/components/alert.ts
- update min-height value for expandable variant
- update layout 
- add css variables for fade gradient
- update documentation
> Update component Alert

- apps/design-system/src/subjects/views/unified-pipeline-studio/run-pipeline-drawer-content.tsx
- packages/ui/src/views/run-pipeline/run-pipeline-drawer-content.tsx
- packages/ui/src/views/run-pipeline/run-pipeline-from-inputs.tsx
- packages/ui/src/views/run-pipeline/utils/__tests__/inputs-utils.test.tsx
- packages/ui/src/views/run-pipeline/utils/index.ts
- packages/ui/src/views/run-pipeline/utils/inputs-utils.ts
- packages/ui/src/views/run-pipeline/utils/types.ts
This PR adds support for grouping inputs based on a "layout" property.
> feat: Add layout support for inputs

- packages/core-design-system/design-tokens/components/desktop/base/drawer.json
- packages/core-design-system/design-tokens/components/desktop/base/sidebar.json
> increased drawer fade height

- packages/ui/src/views/connectors/connector-details/connector-details-header.tsx
fix: logov2 for connector details page
> fix: logov2 for connector details page

- apps/portal/src/components/docs-page/example.tsx
- apps/portal/src/styles.css
https://github.com/user-attachments/assets/8362f97a-ebba-4784-926a-24e5d6415242
> Update portal code UI and add line numbers

- apps/portal/src/content/docs/components/select.mdx
- packages/ui/src/components/form-primitives/select.tsx
Update component Select:
- remove base className
- add triggerClassName for trigger element
- add rootClassName for root container
> Add custom class name props for root and trigger Select component

- apps/design-system/src/subjects/views/unified-pipeline-studio/run-pipeline-drawer-content.tsx
- packages/ui/src/views/run-pipeline/utils/__tests__/inputs-utils.test.tsx
- packages/ui/src/views/run-pipeline/utils/inputs-utils.ts
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/accordion-form-input.tsx
- packages/ui/src/views/unified-pipeline-studio/components/form-inputs/index.ts
- packages/ui/src/views/unified-pipeline-studio/components/stage-config/unified-pipeline-studio-stage-config-form.tsx
- Improve accordion form input
- Update parser
- Prevent stage form render before values are provided
> Improve accordion form input

- packages/ui/package.json
> Bump UI version

- packages/core-design-system/design-tokens/components/desktop/base/alert.json
- packages/core-design-system/design-tokens/components/desktop/base/input.json
- packages/core-design-system/design-tokens/mode/dark/default-deuteranopia.json
- packages/core-design-system/design-tokens/mode/dark/default-protanopia.json
- packages/core-design-system/design-tokens/mode/dark/default-tritanopia.json
- packages/core-design-system/design-tokens/mode/dark/default.json
- packages/core-design-system/design-tokens/mode/dark/dimmer-deuteranopia.json
- packages/core-design-system/design-tokens/mode/dark/dimmer-protanopia.json
- packages/core-design-system/design-tokens/mode/dark/dimmer-tritanopia.json
- packages/core-design-system/design-tokens/mode/dark/dimmer.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast-deuteranopia.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast-protanopia.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast-tritanopia.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast.json
- packages/core-design-system/design-tokens/mode/light/default-deuteranopia.json
- packages/core-design-system/design-tokens/mode/light/default-protanopia.json
- packages/core-design-system/design-tokens/mode/light/default-tritanopia.json
- packages/core-design-system/design-tokens/mode/light/default.json
- packages/core-design-system/design-tokens/mode/light/dimmer-deuteranopia.json
- packages/core-design-system/design-tokens/mode/light/dimmer-protanopia.json
- packages/core-design-system/design-tokens/mode/light/dimmer-tritanopia.json
- packages/core-design-system/design-tokens/mode/light/dimmer.json
- packages/core-design-system/design-tokens/mode/light/high-contrast-deuteranopia.json
- packages/core-design-system/design-tokens/mode/light/high-contrast-protanopia.json
- packages/core-design-system/design-tokens/mode/light/high-contrast-tritanopia.json
- packages/core-design-system/design-tokens/mode/light/high-contrast.json
horizontal input label max-width added
> horizontal input label max-width added

- apps/gitness/src/AppMFE.tsx
- apps/gitness/src/components-v2/mfe/side-bar.tsx
- apps/gitness/src/framework/context/MFEContext.tsx
- apps/gitness/src/routes.tsx
- packages/ui/src/components/app-sidebar/sidebar-user.tsx
- packages/ui/src/views/repo/repo-summary/components/summary-panel.tsx
- packages/ui/src/views/sidebar-view/sidebar-view.tsx
- Add theme modal
- Add language selection
- Add Profile settings page
https://github.com/user-attachments/assets/430c0fb9-140d-460f-b99e-fa44e6f621d9
> Fix theme and language modal and repo created time display

- apps/gitness/src/components/FileExplorer.tsx
- packages/ui/src/components/copy-button/use-copy-button.tsx
https://github.com/user-attachments/assets/34fc5b2f-514d-449a-8823-0f940902d1f4
> fix: minor bug fixes

- apps/portal/src/content/docs/components/drawer.mdx
- apps/portal/src/content/docs/components/scroll-area.mdx
- packages/ui/src/components/drawer/DrawerBody.tsx
- packages/ui/src/components/drawer/DrawerContent.tsx
- packages/ui/src/components/scroll-area.tsx
- packages/ui/tailwind-utils-config/components/drawer.ts
https://github.com/user-attachments/assets/2a8ac28d-c64b-4fb5-ab70-c055dea10f56
> Update Drawer component: add 'xs' size, add scroll gradient event

- apps/gitness/src/components-v2/mfe/side-bar.tsx
https://github.com/user-attachments/assets/01a26551-b444-4eec-acd4-ad5a8f40330f
> Fix side bar theme switch in mfe

- packages/ui/src/components/manage-navigation/index.tsx
- packages/ui/src/components/manage-navigation/manage-navigation-search.tsx
https://github.com/user-attachments/assets/f83cf85d-70f7-4d0c-8df1-2ea92a4464b7
> Fix manage navigation modal

- apps/gitness/src/hooks/useLoadMFEStyles.ts
> Fix code highlight issue in MFE

- apps/design-system/src/subjects/views/secrets/mock-secrets-data.json
- apps/gitness/src/routes.tsx
- packages/ui/src/components/stacked-list.tsx
- packages/ui/src/views/connectors/connector-header.tsx
- packages/ui/src/views/connectors/connector-reference/connector-reference.tsx
- packages/ui/src/views/platform/entity-reference-component.tsx
- packages/ui/src/views/secrets/secret-reference/secret-reference.tsx
1. Fix breadcrumbs on `profile-settings` page
2. Add truncation to title in `entity-ref`
3. Remove periods from cards
> Fix multiple minor issues

- packages/ui/src/views/delegates/components/delegate-connectivity-list.tsx
- packages/ui/src/views/delegates/delegate-selector/delegate-selector-form.tsx
https://github.com/user-attachments/assets/ff1af7cf-ad1c-48a1-bef3-345cf0233627
> Update DelegateConnectivityList and DelegateSelectorForm for correct drawer view

- apps/design-system/src/subjects/views/unified-pipeline-studio/run-pipeline-drawer-content.tsx
- packages/forms/src/core/utils/utils.ts
- packages/ui/src/views/run-pipeline/types.ts
- packages/ui/src/views/run-pipeline/utils/form-utils.tsx
- packages/ui/src/views/run-pipeline/utils/inputs-utils.ts
fix: input ui config and forms default value collection for group/accordion
> fix: input ui config and forms default value collection for group/accordion

- apps/gitness/src/pages-v2/pull-request/pull-request-changes.tsx
- packages/ui/src/views/repo/pull-request/details/components/changes/pull-request-changes-filter.tsx
- packages/ui/src/views/repo/pull-request/details/components/changes/pull-request-changes.tsx
- packages/ui/src/views/repo/pull-request/details/pull-request-changes-page.tsx
https://github.com/user-attachments/assets/ee9b23e2-d61f-4320-85a5-47b2aac695b5
1. Makes changed files in PR clickable, navigates to the files page.  
2. Fixes the commits dropdown on the PR page, can now select multiple commits.
> Bug bash fixes

- packages/ui/src/components/filters/filter-select.tsx
- packages/ui/src/components/filters/filters-bar/actions/variants/checkbox.tsx
- packages/ui/src/components/filters/filters-bar/actions/variants/text-field.tsx
- packages/ui/src/components/searchable-dropdown/searchable-dropdown.tsx
- packages/ui/src/views/components/FilterGroup.tsx
- packages/ui/src/views/connectors/connectors-list/connectors-list.tsx
- packages/ui/src/views/repo/components/list-control-bar.tsx
- packages/ui/src/views/repo/pull-request/pull-request-list-page.tsx
- packages/ui/tailwind-utils-config/components/drawer.ts
1. Fixes sort and filter dropdown issues
2. Updated drawer fix when there is no footer or header
> fix: added minor issue fixes in ui pkg

- packages/core-design-system/design-tokens/core/typography.json
- packages/core-design-system/design-tokens/mode/dark/default-deuteranopia.json
- packages/core-design-system/design-tokens/mode/dark/default-protanopia.json
- packages/core-design-system/design-tokens/mode/dark/default-tritanopia.json
- packages/core-design-system/design-tokens/mode/dark/default.json
- packages/core-design-system/design-tokens/mode/dark/dimmer-deuteranopia.json
- packages/core-design-system/design-tokens/mode/dark/dimmer-protanopia.json
- packages/core-design-system/design-tokens/mode/dark/dimmer-tritanopia.json
- packages/core-design-system/design-tokens/mode/dark/dimmer.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast-deuteranopia.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast-protanopia.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast-tritanopia.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast.json
- packages/core-design-system/design-tokens/mode/light/default-deuteranopia.json
- packages/core-design-system/design-tokens/mode/light/default-protanopia.json
- packages/core-design-system/design-tokens/mode/light/default-tritanopia.json
- packages/core-design-system/design-tokens/mode/light/default.json
- packages/core-design-system/design-tokens/mode/light/dimmer-deuteranopia.json
- packages/core-design-system/design-tokens/mode/light/dimmer-protanopia.json
- packages/core-design-system/design-tokens/mode/light/dimmer-tritanopia.json
- packages/core-design-system/design-tokens/mode/light/dimmer.json
- packages/core-design-system/design-tokens/mode/light/high-contrast-deuteranopia.json
- packages/core-design-system/design-tokens/mode/light/high-contrast-protanopia.json
- packages/core-design-system/design-tokens/mode/light/high-contrast-tritanopia.json
- packages/core-design-system/design-tokens/mode/light/high-contrast.json
sidebar gradient fade for scroll added
> sidebar-fade

- packages/core-design-system/design-tokens/breakpoint/desktop.json
body line-height changed from normal to snug
> body line-height changed from normal to snug

- apps/design-system/src/subjects/views/repo-branches/index.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- apps/gitness/src/pages-v2/repo/repo-branch-list.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/components/pagination/pagination-primitive.tsx
- packages/ui/src/components/pagination/pagination.tsx
- packages/ui/src/views/labels/components/label-form-color-and-name-group.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-header.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-list-header.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-list.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-comment-box.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-panel.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/sections/panel-accordion-show-button.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/sections/pull-request-changes-section.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/sections/pull-request-checks-section.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/sections/pull-request-line-title.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/sections/pull-request-merge-section.tsx
- packages/ui/src/views/repo/pull-request/pull-request-list-page.tsx
- packages/ui/src/views/repo/repo-branch/repo-branch-list-view.tsx
- packages/ui/src/views/repo/repo-branch/types.ts
- packages/ui/src/views/repo/repo-settings/repo-settings-layout.tsx
- packages/ui/src/views/repo/repo-tags/components/repo-tags-list.tsx
- packages/ui/src/views/repo/repo-tags/repo-tags-list-page.tsx
> Bug bash issue fixes

- apps/portal/src/content/docs/components/accordion.mdx
- packages/ui/src/components/accordion/accordion.tsx
> feat: Accordion Card Variant

- packages/ui/src/views/unified-pipeline-studio/components/palette-drawer/components/step-palette-content-layout.tsx
- packages/ui/src/views/unified-pipeline-studio/components/palette-drawer/unified-pipeline-step-palette-drawer.tsx
- packages/ui/src/views/unified-pipeline-studio/components/unified-pipeline-step-drawer.tsx
- Fix spacing between sections
- Disable exit prompt on step drawer due to incorrect behaviour.
https://github.com/user-attachments/assets/e075366e-61ec-42db-a367-42f59e65e919
> fix: Fix usability issues on Step drawer

- packages/ui/package.json
> chore: bump ui version

- packages/ui/src/views/run-pipeline/types.ts
- packages/ui/src/views/run-pipeline/utils/inputs-utils.ts
fix: default options from options/items/enum and connectorTypes from oneOf
> fix: default options from options/items/enum and connectorTypes from oneOf

- .github/workflows/build-and-deploy-storybook.yml
- apps/gitness/webpack.config.cjs
- packages/ui/package.json
- packages/ui/vite-base.config.ts
- pnpm-lock.yaml
Reverts harness/canary#1890Revert "fix: ui and gitness shared dependencies sharing fix"
> Revert "fix: ui and gitness shared dependencies sharing fix"

- packages/ui/src/views/connectors/connectors-list/connectors-list.tsx
https://github.com/user-attachments/assets/0aefe3cd-8447-4b54-8b5f-7fb7a1bc9aaf
> fix: disable link on button cells in connectors-list

- .github/workflows/build-and-deploy-storybook.yml
- packages/ui/package.json
- packages/ui/vite-base.config.ts
- pnpm-lock.yaml
`react-dom` should not be bundled into ui package.
> chore: Restoring changes from PR #1890

- packages/core-design-system/design-tokens/breakpoint/desktop.json
- packages/core-design-system/design-tokens/components/desktop/base/table.json
In this PR I provided all necessary tokens for table header and rows update requested by Traceable team
> caption strong typography style added

- packages/ui/src/components/filters/filter-box-wrapper.tsx
- packages/ui/src/components/filters/filters-bar/actions/variants/calendar-field.tsx
- packages/ui/src/components/filters/filters-bar/actions/variants/combo-box.tsx
- packages/ui/src/components/filters/filters-field.tsx
- packages/ui/src/components/skeletons/skeleton-table.tsx
- packages/ui/src/views/connectors/connectors-list/filter-options.tsx
- packages/ui/src/views/repo/pull-request/components/labels/labels-filter.tsx
- packages/ui/src/views/repo/pull-request/pull-request-list-page.tsx
https://github.com/user-attachments/assets/53224c92-eae0-4d51-a211-92656d6f01c2
> fix: Updated filters to auto-close on selection of values

- packages/ui/src/views/run-pipeline/utils/inputs-utils.ts
fix: input output transform and default inputs for pipeline inputs
> fix: input output transform and default inputs for pipeline inputs

- apps/gitness/src/pages-v2/pull-request/pull-request-compare.tsx
- packages/ui/src/views/repo/pull-request/compare/pull-request-compare-page.tsx
https://github.com/user-attachments/assets/42722c42-a886-453b-ac53-80a89504e08c
> fix: pr conversation routing

- apps/gitness/src/components-v2/breadcrumbs/breadcrumbs.tsx
- apps/gitness/src/components-v2/mfe/app-shell.tsx
- apps/gitness/src/components-v2/standalone/app-shell.tsx
- packages/ui/src/views/layouts/main-content-layout.tsx
This reverts commit f52114cb2f39d4d67c72b4ae833957b0b02ff009.
> revert: Revert "Fix mfe navbar (#1903)"

- packages/ui/src/views/run-pipeline/utils/inputs-utils.ts
fix: input output transform for key-value-pairs
> fix: input output transform for key-value-pairs

- packages/ui/package.json
> fix: bump ui package

- apps/design-system/src/pages/view-preview/view-preview.tsx
- apps/design-system/src/subjects/views/search-page/search-page-preview.tsx
- apps/design-system/src/subjects/views/search-page/search-results-store.ts
- apps/gitness/src/pages-v2/search-page.tsx
- apps/gitness/src/routes.tsx
- packages/ui/src/views/index.ts
- packages/ui/src/views/search/components/search-results-list.tsx
- packages/ui/src/views/search/index.ts
- packages/ui/src/views/search/search-page.tsx
Adds a basic search page with preview
> feat: add Token Search page

- packages/ui/src/components/tooltip.tsx
> Add portal for tooltip component

- apps/gitness/src/hooks/useGitRef.ts
Before fix:
https://github.com/user-attachments/assets/deea88d4-33ed-4668-9357-5f7d0cd58119
After fix:
https://github.com/user-attachments/assets/f3d6ab58-303e-4f5f-ae8d-8e0bd9bc9a96
> Fix tab highlight while creating or editing a file

- packages/filters/src/Filters.tsx
Fixed issue when updating query-params does not get picked by filters lib
Adding and deleting a filter to qp should get updated by filters UI
> fix: synced filters with query-params

- apps/gitness/src/components-v2/file-editor.tsx
- packages/ui/src/components/path-breadcrumbs.tsx
- packages/ui/src/views/repo/components/path-action-bar.tsx
https://github.com/user-attachments/assets/ad4996f9-3a5c-4367-b109-0f513e07688f
> fix: create folder in nested routes 

- apps/gitness/src/pages-v2/search-page.tsx
fixes new url format:
- removes `gateway` prefix
- add `refs/heads` prefix for branches
> fix: search with new urls

- packages/forms/playground/src/examples/runtime-example/form-definition.tsx
- packages/forms/playground/src/examples/runtime-example/runtime-example.tsx
- packages/forms/playground/src/implementation/factory/factory.tsx
- packages/forms/playground/src/implementation/inputs/common/types.ts
- packages/forms/playground/src/implementation/inputs/group-input.tsx
- packages/forms/src/core/index.ts
- packages/forms/src/core/utils/default-value-utils.ts
Uploading Screen Recording 2025-07-21 at 18.37.16.mov…
> Auto hide group if no inputs visible

- packages/ui/src/components/no-data.tsx
- packages/ui/src/views/labels/components/labels-list-view.tsx
- packages/ui/src/views/labels/labels-list-page.tsx
- packages/ui/src/views/layouts/content-layout-with-sidebar.tsx
- packages/ui/src/views/layouts/webhooks-settings-layout.tsx
- packages/ui/src/views/repo/repo-settings/repo-settings-layout.tsx
> fix empty page max height

- packages/ui/src/components/repo-subheader.tsx
- packages/ui/src/views/execution/execution-tabs.tsx
- packages/ui/src/views/project/project-settings-tab-nav.tsx
- packages/ui/src/views/unified-pipeline-studio/components/unified-pipeline-studio-panel.tsx
- packages/ui/tailwind-utils-config/components/tabs.ts
> Add border bottom as default for Tabs underlined variant

- packages/core-design-system/design-tokens/breakpoint/desktop.json
Updated layout tokens, added new values and changed previous values.
lg –> xl
xl –> 2xl
2xl –> 3xl
> updated layout values

- apps/gitness/src/pages-v2/repo/repo-commits.tsx
- packages/ui/src/views/repo/components/commits-list.tsx
- packages/ui/src/views/repo/repo-commits/repo-commits-view.tsx
https://github.com/user-attachments/assets/7a60657a-bf39-4551-a3c9-badded5cc4a7
> Add pr link in the title - commit listing page

- packages/ui/src/components/favorite.tsx
- packages/ui/tailwind-design-system.ts
https://github.com/user-attachments/assets/204abd20-2aa6-4726-8190-57c3769adeb2
https://github.com/user-attachments/assets/0079dc8c-2a85-4c6d-b13b-9c56d9e87aeb
> Add correct yellow color to icons

- packages/ui/src/views/repo/repo-summary/repo-empty-view.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
1. Generate Clone Credentials Dialog
- Display Error validation where the max token limit is reached after clicking the Generate Clone Credentials button.
2. Link Text Styling
- Updated the link texts styling for consistency (`here.` and `create an API token`).
https://github.com/user-attachments/assets/2f2e58ab-8046-4de0-8e38-b77fc399883d
> Error display for maximum token limit and apply styles to link text.

- packages/ui/src/components/alert-dialog.tsx
- packages/ui/src/components/dialog.tsx
- packages/ui/tailwind-utils-config/components/dialog.ts
[Design](https://www.figma.com/design/AIgjIyUzcuZzuVnuoOyhQE/Harness-Design-System--3.0--BETA?node-id=1474-31261&m=dev)
- fixed layout paddings
- fixed X button styles and position
- fixed content paddings (it has padding compensation for the focused state)
> adjust dialog component to design

- apps/design-system/src/subjects/views/pull-request-conversation/pull-request-conversation.tsx
- apps/gitness/src/pages-v2/pull-request/__tests__/pull-request-utils.test.ts
- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-utils.ts
- apps/gitness/src/pages-v2/pull-request/stores/pull-request-provider-store.tsx
- apps/gitness/src/pages-v2/pull-request/types.ts
- apps/gitness/src/types.ts
- packages/ui/src/components/avatar.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-panel.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-system-comments.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/sections/components/code-owners-section.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/sections/components/commons.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/sections/components/default-reviewers-section.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/sections/pull-request-changes-section.tsx
- packages/ui/src/views/repo/pull-request/details/pull-request-details-types.ts
- packages/ui/src/views/repo/pull-request/details/pull-request-utils.ts
feat: PR conversation panel default reviewers
feat: avatar with tooltip for PR panel reviewers section
> feat: PR conversation panel default reviewers and avatar with tooltip

- apps/design-system/src/subjects/views/pull-request-conversation/pull-request-conversation.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-panel.tsx
This PR adds `Revert` button next to the `Delete Branch` button, once the Pull Request is merged.
https://github.com/user-attachments/assets/ae464837-da3a-4af5-a6ac-2cd6b0e8c269
> Revert Pull Request

- apps/design-system/src/subjects/views/repo-general-settings/use-repo-rules-store.ts
- apps/gitness/src/pages-v2/repo/repo-settings-general-container.tsx
- apps/gitness/src/pages-v2/repo/stores/repo-settings-store.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-security.tsx
- packages/ui/src/views/repo/repo-settings/repo-settings-general-page.tsx
- packages/ui/src/views/repo/repo-settings/types.ts
https://github.com/user-attachments/assets/732fc8f4-2748-469a-9010-95743c0753a7
> feat: add vulnerability scanning checkbox with api

- apps/gitness/src/pages-v2/pull-request/hooks/usePRChecksDecision.ts
- apps/gitness/src/pages-v2/pull-request/pull-request-conversation.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-data-provider.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-utils.ts
- apps/gitness/src/pages-v2/pull-request/stores/pull-request-provider-store.tsx
- apps/gitness/src/pages-v2/pull-request/types.ts
- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-panel.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/sections/pull-request-checks-section.tsx
- packages/ui/src/views/repo/pull-request/details/pull-request-details-types.ts
- packages/ui/src/views/repo/pull-request/pull-request.types.ts
- packages/ui/src/views/repo/repo-branch-rules/components/repo-branch-rules-data.tsx
- packages/ui/src/views/repo/repo-branch-rules/types.ts
fix: pull request panel checks section
> fix: pull request panel checks section

- apps/gitness/src/pages-v2/project/project-rules-list-container.tsx
- apps/gitness/src/pages-v2/repo/repo-settings-rules-list-container.tsx
- apps/gitness/src/pages-v2/repo/stores/repo-settings-store.tsx
- apps/gitness/src/utils/rule-url-utils.ts
- packages/ui/src/views/project/project-rules/project-rules-page.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-rules.tsx
- packages/ui/src/views/repo/repo-settings/repo-settings-rules-page.tsx
- packages/ui/src/views/repo/repo-settings/types.ts
https://github.com/user-attachments/assets/d65f221f-7cf5-49f5-ab32-d5dee990ce25
> fix: routing into rule-details from parent scope

- apps/design-system/src/subjects/views/repo-list/repo-list.tsx
- apps/gitness/src/pages-v2/repo/repo-list.tsx
- packages/ui/src/components/scope/scope-tag.tsx
- packages/ui/src/components/scope/utils.ts
- packages/ui/src/views/common/types.ts
- packages/ui/src/views/repo/repo-list/repo-list-page.tsx
- packages/ui/src/views/repo/repo-list/repo-list.tsx
- packages/ui/src/views/repo/repo-list/types.ts
- Adds Sorting, this is still WIP to support multiple sort criteria.
https://github.com/user-attachments/assets/3087ba2c-5e06-4143-ab15-94cacd749650
- Repositions `Favorite` Star button to near to bottom right on the repository information row.
- Adds `Scope Tag` with scope and repo path info.
https://github.com/user-attachments/assets/3810295f-82f4-482f-b293-e776a8a7479c
> feat: Miscellaneous changes on Repository Listing page

- apps/gitness/src/pages-v2/project/pull-request/pull-request-list.tsx
- apps/gitness/src/pages-v2/pull-request/pull-request-list.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/views/repo/pull-request/pull-request-list-page.tsx
- packages/ui/src/views/repo/pull-request/pull-request.types.ts
https://github.com/user-attachments/assets/67a46e35-a0a4-41b1-9d82-3dfb44ff8e04
> feat: added filter logic

- packages/core-design-system/design-tokens/mode/dark/default-deuteranopia.json
- packages/core-design-system/design-tokens/mode/dark/default-protanopia.json
- packages/core-design-system/design-tokens/mode/dark/default-tritanopia.json
- packages/core-design-system/design-tokens/mode/dark/default.json
- packages/core-design-system/design-tokens/mode/dark/dimmer-deuteranopia.json
- packages/core-design-system/design-tokens/mode/dark/dimmer-protanopia.json
- packages/core-design-system/design-tokens/mode/dark/dimmer-tritanopia.json
- packages/core-design-system/design-tokens/mode/dark/dimmer.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast-deuteranopia.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast-protanopia.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast-tritanopia.json
- packages/core-design-system/design-tokens/mode/dark/high-contrast.json
- packages/core-design-system/design-tokens/mode/light/default-deuteranopia.json
- packages/core-design-system/design-tokens/mode/light/default-protanopia.json
- packages/core-design-system/design-tokens/mode/light/default-tritanopia.json
- packages/core-design-system/design-tokens/mode/light/default.json
- packages/core-design-system/design-tokens/mode/light/dimmer-deuteranopia.json
- packages/core-design-system/design-tokens/mode/light/dimmer-protanopia.json
- packages/core-design-system/design-tokens/mode/light/dimmer-tritanopia.json
- packages/core-design-system/design-tokens/mode/light/dimmer.json
- packages/core-design-system/design-tokens/mode/light/high-contrast-deuteranopia.json
- packages/core-design-system/design-tokens/mode/light/high-contrast-protanopia.json
- packages/core-design-system/design-tokens/mode/light/high-contrast-tritanopia.json
- packages/core-design-system/design-tokens/mode/light/high-contrast.json
shadow color correction for light mode
> shadow color correction

- packages/ui/src/components/stacked-list.tsx
- packages/ui/src/components/table.tsx
- packages/ui/src/styles/styles.css
- packages/ui/src/views/repo/repo-list/repo-list.tsx
- packages/ui/tailwind-design-system.ts
- packages/ui/tailwind-utils-config/components/table-v2.ts
- packages/ui/tailwind-utils-config/components/time-ago-card.ts
- Added logic and styles for table row focus when the row acts as a link.
- Added focus styles for the StackedList component.
> Add focus-visible logic for table row link type

- packages/ui/src/components/skeletons/components/skeleton.tsx
> Temporarily apply the background from the token to the skeleton

- packages/ui/src/components/markdown-viewer/index.tsx
- packages/ui/src/components/markdown-viewer/style.css
> add md view design review

- packages/ui/src/components/markdown-viewer/style.css
> fix suggestion code background

- packages/core-design-system/design-tokens/breakpoint/desktop.json
- packages/core-design-system/design-tokens/components/desktop/base/btn.json
commit-width for commit button added
mono-font styles for commit button also added
> commit-width added

- packages/ui/src/components/stacked-list.tsx
- packages/ui/src/views/pipelines/execution-list/execution-list.tsx
- packages/ui/src/views/pipelines/pipeline-list/pipeline-list.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-item-title.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-list.tsx
- packages/ui/src/views/repo/repo-commit-details/components/commit-changes.tsx
- packages/ui/src/views/repo/repo-list/repo-list.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-rules.tsx
- packages/ui/src/views/repo/repo-summary/repo-summary.tsx
> Fix truncating text at StackedList.Field

- apps/portal/src/content/docs/components/dialog.mdx
- packages/ui/src/components/commit-suggestions-dialog/commit-suggestions-dialog.tsx
- packages/ui/src/components/dialog.tsx
- packages/ui/src/components/manage-navigation/index.tsx
- packages/ui/src/components/theme-selector-v2/theme-dialog.tsx
- packages/ui/src/views/connectors/components/connector-test-connection-dialog.tsx
- packages/ui/src/views/pipelines/create-pipeline-dialog/create-pipeline-dialog.tsx
- packages/ui/src/views/profile-settings/components/profile-settings-keys-create-dialog.tsx
- packages/ui/src/views/profile-settings/components/profile-settings-token-create-dialog.tsx
- packages/ui/src/views/repo/components/commits-list.tsx
- packages/ui/src/views/repo/components/token-dialog/clone-credential-dialog.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-header-edit-dialog.tsx
- packages/ui/src/views/repo/repo-branch/components/create-branch-dialog.tsx
- packages/ui/src/views/repo/repo-commits/repo-commits-view.tsx
- packages/ui/src/views/repo/repo-create/default-branch-dialog.tsx
- packages/ui/src/views/repo/repo-tags/components/create-tag/create-tag-dialog.tsx
- packages/ui/src/views/user-management/components/dialogs/components/edit-user/edit-user.tsx
- packages/ui/src/views/user-management/components/dialogs/components/remove-admin.tsx
- packages/ui/src/views/user-management/components/dialogs/components/reset-password/reset-password.tsx
- packages/ui/tailwind-utils-config/components/dialog.ts
- reduced the amount of unnecessary wrappers for the `Dialog` body
- added default gaps between items inside `Dialog` body
- fixed multiple UI issues among the dialogs in the app
- used Layout component instead of tailwind `flex` classnames
> Dialog design review

- packages/ui/src/components/scope/scope-tag.tsx
- packages/ui/src/components/stacked-list.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-header.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-item-description.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-item-title.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-list.tsx
> Fix PR title layout at list and in PR page

- packages/ui/src/components/no-data.tsx
- packages/ui/src/components/stacked-list.tsx
- packages/ui/src/components/time-ago-card.tsx
- packages/ui/src/views/repo/repo-list/repo-list.tsx
> Align PR list with design

- packages/ui/src/components/markdown-viewer/style.css
> Change comment markdown size text

- packages/ui/src/components/markdown-viewer/style.css
> Update comments markdown typography styles

- packages/ui/tailwind-utils-config/components/checkbox.ts
- packages/ui/tailwind-utils-config/components/radio.ts
> Add focus state for Radio and Checkbox

- packages/ui/tailwind-utils-config/components/dropdown-menu.ts
> Fix dropdown content height on small screen heights

- packages/ui/src/components/dialog.tsx
- packages/ui/src/components/form-primitives/textarea.tsx
- packages/ui/src/views/repo/components/file-last-change-bar.tsx
- packages/ui/src/views/repo/repo-summary/components/edit-repo-details-dialog.tsx
- packages/ui/tailwind-utils-config/components/switch.ts
- Fixed focus on the File Last Change bar
- Fixed Description dialog bugs and autofocus
- Added focus state to the Switch
> Fix some design diffs and bugs at Summary page + add focus to Switch

- packages/ui/src/components/checkbox.tsx
- packages/ui/src/components/dropdown-menu.tsx
- packages/ui/tailwind-utils-config/components/checkbox.ts
> Fix checkbox icon size

- apps/design-system/src/subjects/views/repo-files/components/repo-file-edit.tsx
- apps/design-system/src/subjects/views/repo-files/components/repo-files-wrapper.tsx
- apps/gitness/src/components-v2/GitBlame.tsx
- apps/gitness/src/components-v2/file-content-viewer.tsx
- apps/gitness/src/components-v2/file-editor.tsx
- apps/gitness/src/pages-v2/repo/repo-code.tsx
- apps/gitness/src/pages-v2/repo/repo-sidebar.tsx
- apps/gitness/src/utils/git-utils.ts
- packages/ui/src/components/button-group.tsx
- packages/ui/src/components/file-control-bars/file-viewer-control-bar.tsx
- packages/ui/src/components/file-explorer.tsx
- packages/ui/src/components/path-breadcrumbs.tsx
- packages/ui/src/components/search-files.tsx
- packages/ui/src/styles/styles.css
- packages/ui/src/views/components/contributors.tsx
- packages/ui/src/views/repo/components/draggable-sidebar-divider.tsx
- packages/ui/src/views/repo/components/path-action-bar.tsx
- packages/ui/src/views/repo/repo-files/repo-files-view.tsx
- packages/yaml-editor/src/components/CodeEditor.tsx
- fixed loader for the File preview (table skeleton -> spinner)
- rewrote files search from custom component to dropdown
- fixed layout of different components
- fixed markdown preview overflow issue
- fixed styles of the resizer component
> add repo files design review

- packages/ui/src/components/inputs/text-input.tsx
> Fix text-input autofocus at Dialog

- apps/design-system/src/subjects/views/labels/project-labels-list.tsx
- apps/gitness/src/pages-v2/project/labels/project-labels-list-container.tsx
- apps/gitness/src/pages-v2/project/rules/project-branch-rules-container.tsx
- apps/gitness/src/pages-v2/repo/labels/labels-list-container.tsx
- packages/ui/src/components/layout.tsx
- packages/ui/src/styles/styles.css
- packages/ui/src/views/labels/components/labels-list-view.tsx
- packages/ui/src/views/labels/labels-list-page.tsx
- packages/ui/src/views/layouts/content-layout-with-sidebar.tsx
- packages/ui/src/views/layouts/webhooks-settings-layout.tsx
- packages/ui/src/views/profile-settings/profile-settings-general-page.tsx
- packages/ui/src/views/profile-settings/profile-settings-keys-page.tsx
- packages/ui/src/views/profile-settings/profile-settings-layout.tsx
- packages/ui/src/views/project/project-general/project-general-page.tsx
- packages/ui/src/views/repo/repo-branch-rules/components/repo-branch-rules-fields.tsx
- packages/ui/src/views/repo/repo-branch-rules/repo-branch-settings-rules-page.tsx
- packages/ui/src/views/repo/repo-commits/repo-commits-view.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-rules.tsx
- packages/ui/src/views/repo/repo-settings/repo-settings-general-page.tsx
- packages/ui/src/views/repo/repo-settings/repo-settings-layout.tsx
- packages/ui/src/views/repo/repo-settings/repo-settings-rules-page.tsx
- packages/ui/src/views/repo/repo-tag-rules/components/repo-tag-rules-fields.tsx
- packages/ui/src/views/repo/repo-tag-rules/repo-tag-settings-rules-page.tsx
- packages/ui/src/views/repo/webhooks/webhook-create/repo-webhook-create-page.tsx
- packages/ui/src/views/repo/webhooks/webhook-executions/repo-webhook-execution-details-page.tsx
- packages/ui/src/views/repo/webhooks/webhook-executions/repo-webhook-executions-list-page.tsx
- packages/ui/src/views/repo/webhooks/webhook-list/repo-webhook-list-page.tsx
- packages/ui/tailwind-utils-config/components/form-shared-styles.ts
- main settings wrapper is now using SandboxLayout.Content as base
- settings forms either have width 570px, or take available space, depending on design
- all forms wrapped into Layout component with proper gap
- reduced unnecessary wrappers
> Settings container refactoring

- packages/ui/src/views/repo/components/file-last-change-bar.tsx
> remove unnecessary checkmark

- packages/ui/src/components/dropdown-menu.tsx
> add props to dropdown subcontent

- packages/ui/src/components/filters/filter-box-wrapper.tsx
> Change Delete filter Dropdown to Button

- packages/ui/src/components/dropdown-menu.tsx
- packages/ui/src/components/search-files.tsx
- packages/ui/src/components/tabs.tsx
- packages/ui/src/utils/get-shadow-active-element.ts
- packages/ui/src/utils/index.ts
- packages/ui/tailwind-utils-config/components/tabs.ts
https://github.com/user-attachments/assets/92bdda2b-4b79-4e02-a914-f2005c881fa1
> Fix navigation in a Tabs within Shadow DOM

- apps/gitness/src/pages-v2/project/labels/project-label-form-container.tsx
- apps/gitness/src/pages-v2/repo/labels/label-form-container.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/components/form-primitives/select.tsx
- packages/ui/src/views/labels/components/label-form-color-and-name-group.tsx
- packages/ui/src/views/labels/components/label-tag.tsx
- packages/ui/src/views/labels/components/labels-list-view.tsx
- packages/ui/src/views/labels/label-form-page.tsx
- packages/ui/src/views/project/project-import.tsx
- packages/ui/src/views/repo/pull-request/components/labels/pull-request-labels-header.tsx
- packages/ui/src/views/repo/repo-import/repo-import-mulitple.tsx
- packages/ui/src/views/repo/repo-import/repo-import.tsx
> Fix labels form

- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-system-comments.tsx
- packages/ui/src/views/repo/pull-request/details/components/conversation/pull-request-timeline-item.tsx
> Fix display of long reviewer lists in the PR Overview

- packages/ui/src/components/stacked-list.tsx
- packages/ui/src/views/repo/components/commits-list.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-item-title.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-list-header.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-list.tsx
- packages/ui/src/views/repo/pull-request/pull-request-list-page.tsx
- packages/ui/src/views/repo/pull-request/pull-request.types.ts
- packages/ui/src/views/repo/repo-list/repo-list.tsx
- packages/ui/src/views/repo/repo-settings/components/repo-settings-general-rules.tsx
> Fix PR list layout and implement absolute Link logic for StackedItem

- packages/ui/src/views/repo/components/branch-selector-v2/branch-selector-dropdown.tsx
> fix view all branches keydown event behavior

- packages/ui/src/views/repo/components/branch-info-bar.tsx
- packages/ui/src/views/repo/repo-summary/components/clone-repo-dialog.tsx
> Switching from using Dropdown to Popover

- packages/ui/tailwind-utils-config/components/tabs.ts
> Fix z-index for focused Tabs

- packages/ui/src/components/node-group.tsx
- packages/ui/src/views/layouts/PullRequestLayout.tsx
- packages/ui/src/views/repo/components/commits-list.tsx
- packages/ui/src/views/repo/pull-request/compare/pull-request-compare-page.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-header.tsx
[Design](https://www.figma.com/design/aEt78xD47RR94NxLz5Imd0/Pull-Request?node-id=10443-35316&m=dev)
> add pr commits design review

- packages/ui/src/views/repo/components/CommitTitleWithPRLink.tsx
- packages/ui/tailwind-utils-config/components/stacked-list.ts
- packages/ui/tailwind-utils-config/components/tag.ts
> Fixed applying label filters when clicking on a label from the PR list

- packages/ui/src/views/layouts/SecretDetailsLayout.tsx
> Refactor getSecretInfo to use custom dialog trigger for delete action

- apps/design-system/src/subjects/views/secrets/secrets.tsx
- apps/portal/src/components/layout/ThemeSelector.tsx
- apps/portal/src/content/docs/components/accordion.mdx
- apps/portal/src/content/docs/components/stacked-list.mdx
- packages/forms/package.json
- packages/forms/src/core/components/InputComponentRenderer.tsx
- packages/ui/package.json
- packages/ui/src/components/accordion/accordion.tsx
- packages/ui/src/components/card-select.tsx
- packages/ui/src/components/drawer/DrawerContent.tsx
- packages/ui/src/views/platform/components/entity-reference-filter.tsx
- packages/ui/src/views/platform/entity-reference-component.tsx
- packages/ui/src/views/platform/entity-reference-list.tsx
- packages/ui/src/views/platform/types.ts
- packages/ui/src/views/secrets/secret-reference/secret-reference.tsx
- packages/ui/tailwind-utils-config/components/accordion.ts
- packages/ui/tailwind-utils-config/components/multi-select.ts
- packages/ui/tailwind-utils-config/components/stacked-list.ts
- `Drawer` gets focused on open now
- fixed `Accordion` Trigger/Content focus UI issues
- made a small change in `InputComponentRenderer.tsx` to fix an issue with `key` prop in mapped items
- fixed UI and keyboard navigation in EntityReference form
> add secrets-related fixes

- packages/ui/src/views/repo/repo-commit-details/repo-commit-details-view.tsx
> Update commmit details Title font

- packages/ui/src/views/repo/pull-request/components/pull-request-side-bar.tsx
- packages/ui/src/views/repo/pull-request/components/reviewers/pull-request-reviewers-item.tsx
- packages/ui/src/views/repo/pull-request/components/reviewers/pull-request-reviewers-list.tsx
- packages/ui/src/views/repo/pull-request/components/reviewers/reviewer-info.tsx
> Update reviewers list in pr view

- packages/ui/src/views/repo/components/draggable-sidebar-divider.tsx
- packages/ui/src/views/repo/pull-request/compare/components/pull-request-compare-diff-list.tsx
- packages/ui/src/views/repo/pull-request/components/pull-request-diff-sidebar.tsx
- packages/ui/src/views/repo/pull-request/details/pull-request-changes-page.tsx
- packages/ui/src/views/repo/repo-files/repo-files-view.tsx
- packages/ui/src/views/repo/repo-sidebar/index.tsx
> Fix draggable sidebar style

- packages/ui/package.json
> bump ui package version

- apps/portal/src/components/docs-page/component-example.tsx
- packages/ui/locales/en/views.json
- packages/ui/locales/fr/views.json
- packages/ui/src/components/no-data.tsx
- packages/ui/src/context/component-context.tsx
- packages/ui/src/views/layouts/SecretDetailsLayout.tsx
- packages/ui/src/views/secrets/secrets-list/secrets-list-page.tsx
- packages/ui/src/views/secrets/secrets-list/secrets-list.tsx
- packages/ui/tailwind-utils-config/components/drawer.ts
> add return of the focus to the drawer trigger

- packages/ui/src/views/platform/input-reference-component.tsx
> input reference component update

- packages/ui/src/components/inputs/number-input.tsx
- packages/ui/src/views/platform/entity-reference-list.tsx
> Fix entity-reference-list Load more size and number-input buttons rounded style
